{
 "title": "Historical Action Recommendations",
 "description": "Proof of Concept",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "scope",
    "label": "Scope",
    "query": "SELECT name as __text, oid as __value\nFROM entity\nWHERE ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND entity.type IN ('COMPUTE_CLUSTER', 'STORAGE_CLUSTER', 'K8S_CLUSTER', 'BUSINESS_ACCOUNT', 'RESOURCE_GROUP')\nGROUP BY name, oid\nORDER BY 1"
   },
   {
    "name": "entityType",
    "label": "Entity Type",
    "query": "SELECT regexp_replace(entity_type::text, '_NONE_', 'ALL') AS __text, entity_type AS __value\nFROM pending_action_stats\nWHERE ($__timeFrom(),$__timeTo()) OVERLAPS (time, time)\nORDER BY 1"
   },
   {
    "name": "environmentType",
    "label": "Environment Type",
    "query": "SELECT environment_type::text AS __text, environment_type AS __value\nFROM pending_action_stats\nWHERE ($__timeFrom(),$__timeTo()) OVERLAPS (time, time)\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Recommendations Over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('hour', time) as time\n      ,SUM(prior_action_count + new_action_count - cleared_action_count) FILTER (where type = 'MOVE') as \"MOVE\"\n      ,SUM(prior_action_count + new_action_count - cleared_action_count) FILTER (where type = 'PROVISION') as \"PROVISION\"\n      ,SUM(prior_action_count + new_action_count - cleared_action_count) FILTER (where type = 'RESIZE') as \"RESIZE\"\n      ,SUM(prior_action_count + new_action_count - cleared_action_count) FILTER (where type = 'DEACTIVATE') as \"DEACTIVATE\"\n      ,SUM(prior_action_count + new_action_count - cleared_action_count) FILTER (where type = 'DELETE') as \"DELETE\"\n      ,SUM(prior_action_count + new_action_count - cleared_action_count) FILTER (where type = 'SCALE') as \"SCALE\"\n  FROM pending_action_stats JOIN action_group ON pending_action_stats.action_group = action_group.id\n WHERE scope_oid = $scope AND entity_type = ${entityType:singlequote} AND environment_type = ${environmentType:singlequote} AND $__timeFilter(time)\n GROUP BY 1\n"
    }
   ]
  },
  {
   "title": "New Recommendations Over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('hour', time) as time\n      ,SUM(new_action_count) FILTER (where type = 'MOVE') as \"MOVE\"\n      ,SUM(new_action_count) FILTER (where type = 'PROVISION') as \"PROVISION\"\n      ,SUM(new_action_count) FILTER (where type = 'RESIZE') as \"RESIZE\"\n      ,SUM(new_action_count) FILTER (where type = 'DEACTIVATE') as \"DEACTIVATE\"\n      ,SUM(new_action_count) FILTER (where type = 'DELETE') as \"DELETE\"\n      ,SUM(new_action_count) FILTER (where type = 'SCALE') as \"SCALE\"\n  FROM pending_action_stats JOIN action_group ON pending_action_stats.action_group = action_group.id\n WHERE scope_oid = $scope AND entity_type = ${entityType:singlequote} AND environment_type = ${environmentType:singlequote} AND $__timeFilter(time)\n GROUP BY 1\n"
    }
   ]
  },
  {
   "title": "Cleared Recommendations Over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('hour', time) as time\n      ,SUM(cleared_action_count) FILTER (where type = 'MOVE') as \"MOVE\"\n      ,SUM(cleared_action_count) FILTER (where type = 'PROVISION') as \"PROVISION\"\n      ,SUM(cleared_action_count) FILTER (where type = 'RESIZE') as \"RESIZE\"\n      ,SUM(cleared_action_count) FILTER (where type = 'DEACTIVATE') as \"DEACTIVATE\"\n      ,SUM(cleared_action_count) FILTER (where type = 'SCALE') as \"SCALE\"\n      ,SUM(cleared_action_count) FILTER (where type = 'DELETE') as \"DELETE\"\n  FROM pending_action_stats JOIN action_group ON pending_action_stats.action_group = action_group.id\n WHERE scope_oid = $scope AND entity_type = ${entityType:singlequote} AND environment_type = ${environmentType:singlequote} AND $__timeFilter(time)\n GROUP BY 1\n"
    }
   ]
  }
 ]
}