spring:
  application:
    name: ClusterMgrMain
# the path for Spring Cloud Actuator
management:
  context-path: /service
# the port for incoming API calls:
server:
  port: 8080
loader:
  path:
    "config/,lib/,file:/public/,file:/stuff"
# parameters for the ClusterManager process
clustermgr:
  # Name for this Ops Manager node - to be overridden via the command line options when ClusterMgrMain is launched
  node_name:
    default
  # Connection parameters for the Consul server. Docker port mapping will be required between this
  #     Docker image and Consul Docker image
  consul:
    host: ${consul_host}
    port: 8500