uuid PT_Consistent_Scaling_VM_1 73694609002109
start 1-26 17:00

0 0:00 resize   PT_Consistent_Scaling_VM_1 5.00 7.00
0 0:00 execute  PT_Consistent_Scaling_VM_1 5.00 7.00

0 9:00 resize  PT_Consistent_Scaling_VM_1 7 6
0 9:00 execute PT_Consistent_Scaling_VM_1 7 6

0 11:00 power PT_Consistent_Scaling_VM_1 off
0 18:00 power PT_Consistent_Scaling_VM_1 on

0 19:00 resize  PT_Consistent_Scaling_VM_1 6 2
0 21:00 execute PT_Consistent_Scaling_VM_1 6 2

1 0:00 stop

