uuid PT_Consistent_Scaling_VM_1 73694609002109
uuid PT_Consistent_Scaling_VM_2 73694609002111

start 1-26 15:00
0 0:00 resize   PT_Consistent_Scaling_VM_1 6.00 3.00
0 0:00 execute  PT_Consistent_Scaling_VM_1 6.00 3.00
0 0:00 resize   PT_Consistent_Scaling_VM_2 3 2.25
0 0:00 execute  PT_Consistent_Scaling_VM_2 3 2.25

0 0:30 resize   PT_Consistent_Scaling_VM_2 2.25 1.50
0 0:30 execute  PT_Consistent_Scaling_VM_2 2.25 1.50

0 9:00 resize  PT_Consistent_Scaling_VM_1 3.00 1.00
0 9:00 execute PT_Consistent_Scaling_VM_1 3.00 1.00

0 11:00 power PT_Consistent_Scaling_VM_1 off
0 18:00 power PT_Consistent_Scaling_VM_1 on

0 19:30 resize   PT_Consistent_Scaling_VM_2 1.50 1.00
0 19:30 execute  PT_Consistent_Scaling_VM_2 1.50 1.00

1 0:00 stop

