# Testing new inline power state in events

0 0:00 resize VM-A 1.00 2.00
0 0:10 execute VM-A 1.00 2.00
0 0:20 power VM-A off
0 0:30 execute VM-A 2.00 5.00
0 0:40 execute VM-A 5.00 3.00
0 0:50 power VM-A on

#  0- 9 investment = 0, savings = 0
# 10-19 investment = 1, total investment = 1
# 20-29 investment = 0, total investment = 1
# 30-39 investment = 0, total investment = 1
# 40-49 investment = 0, total investment = 1
# 50-59 investment = 1, total investment = 2
