package com.vmturbo.protoc.plugin.common.generator;

import org.stringtemplate.v4.ST;

/**
 * This class contains templates required for code generation.
 */
class Templates {
    private Templates() {}

    static ST file() {
        return new ST(FILE_TEMPLATE);
    }

    private static final String FILE_TEMPLATE =
        "// Generated by the <pluginName> compiler plugin.  DO NOT EDIT!\n" +
        "// source: <protoSourceName>\n" +
        "package <pkgName>;" +

        "<imports>" +
        "@javax.annotation.Generated(" +
                "value = \"by <pluginName> compiler plugin\"," +
                "comments = \"Source: <protoSourceName>\")" +
        "public class <outerClassName> {" +
            "<messageCode>" +
            "<enumCode>" +
            "<serviceCode>" +
        "}";
}
