#!/usr/bin/python
import socket
import sys

clientsocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
clientsocket.connect(('localhost', 2181))
clientsocket.send('ruok')
data = clientsocket.recv(128)
clientsocket.close()
if "imok" == data:
  sys.exit()
else:
  sys.exit(1)
