#!/usr/bin/python2
# Readiness check for zookeeper. Based on sending the "ruok" command to zookeeper.
# See https://zookeeper.apache.org/doc/r3.4.10/zookeeperAdmin.html.
import socket
import sys

clientsocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
clientsocket.connect(('localhost', 2181))
clientsocket.send('ruok')
data = clientsocket.recv(128)
clientsocket.close()
# a response of "imok" means the server is healthy.
if "imok" == data:
  sys.exit()
else:
  sys.exit(1)
