ALTER TABLE plan_reserved_instance_bought ADD COLUMN per_instance_fixed_cost DOUBLE;

ALTER TABLE plan_reserved_instance_bought ADD COLUMN per_instance_recurring_cost_hourly DOUBLE;

ALTER TABLE plan_reserved_instance_bought ADD COLUMN per_instance_amortized_cost_hourly DOUBLE;
