
use vmtdb;


delete from standard_reports ;
go

SET IDENTITY_INSERT standard_reports ON

INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (140,'Host/VM - 30 Days Stats vs Thresholds','This report shows daily average utilization measurements for the past 30 days. Averages are grouped into two sections. One rolled up for physical machines and another rolled up for virtual machines.','30 days average utilization stats vs thresholds','Capacity Management/Hosts','daily_infra_30_days_avg_stats_vs_thresholds_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (145,'Hosting Summary by Physical Machine','This report shows the ratio of VMs per Host over the prior 60 days, and shows the most recent measured hosting levels for each host.','Infra 60 Day Hosting Ratios','Workload Balancing','daily_infra_60_days_hosting_bar','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (146,'Monthly Overview with Cluster Summary','This report shows monthly statistics for the enterprise as a whole, and a monthly summary for each cluster.','Monthly Overview with Cluster Summary','Capacity Management/Hosts','monthly_cluster_summary','Monthly',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (147,'Monthly Overview','This report shows monthly statistics for the enterprise.','Monthly Overview','Capacity Management/Hosts','monthly_summary','Monthly',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (148,'VM Over/Under Provisioning','This report shows Virtual Machines that are over and under provisioned as indicated by their utilization of CPU and Memory','VM Over/Under Provisioning','Capacity Management/VMs','daily_vm_over_under_prov_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (150,'VM Rightsizing Recommendations','This report shows rightsizing recommendations for Virtual Machines based on time range and threshold settings','VM Rightsizing Recommendations','Capacity Management/VMs','daily_vm_rightsizing_advice_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (153,'Utilization Day Over Day by Hour','This report shows average hourly utilization measurements compared day-over-day for the two days indicated. All machines in the infrastructure are included in the averages.','Utilization Day Over Day by Hour','Performance Management/Enterprise','daily_infra_utilization_day_over_day_by_hour_line','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (154,'Utilization Levels by Hour','This report shows by-hour averages for CPU and Memory utlization measurements for Physical and Virtual machines. Averages are rolled up for all machines.','Infra Utilization Levels by Hour','Performance Management/Enterprise','daily_infra_utilization_levels_by_hour_line','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (155,'Host/VM - Top Bottom Utilized','This report shows the top and bottom physical and virtual machines by their Price Index measurements. Price Index is a derived value that reflects the consumption levels of key compute resources taken in combination. Larger values indicate machines on which resources are most utilized.','Host/VM Top Bottom Utilized','Performance Management/Hosts','daily_pm_vm_top_bottom_utilized_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (156,'Host/VM - Resource Utilization Heatmap','This report shows the hottest physical and virtual machines according to their Price Index measurements.  Price Index is a derived value that reflects the consumption levels of key compute resources taken in combination. Larger values indicate machines on which resources are most utilized.','Host/VM Utilization Heatmap','Capacity Management/Hosts','daily_pm_vm_utilization_heatmap_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (160,'Utilization Week Over Week by Day','This report shows average daily utilization measurements compared week-over-week for the two weeks indicated. All machines in the infrastructure are included in the averages.','Infra Utilization Week Over Week by Day','Performance Management/Enterprise','weekly_infra_utilization_week_over_week_by_day_line','Weekly',NULL);
-- INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (162,'Host/VM - Day Over Day','This report shows differences between average daily utilization measurements compared day-over-day for the two days indicated. All machines having differences of 5.0% or more are included, with those that are most different appearing closest to the top.','Host/VM Day Over Day','Performance Management/Hosts','daily_pm_vm_day_over_day_grid');
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (165,'Host Top Bottom Capacity','Shows a capacity-centered view of CPU and Memory utilization, providing actual quantities both used and in reserve.  ','Host Top Bottom Capacity','Capacity Management/Hosts','daily_pm_top_bottom_capacity_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (166,'VM Top Bottom Capacity','Shows a capacity-centered view of VCPU and VMemory utilization, providing actual quantities both used and in reserve.  ','VM Top Bottom Capacity','Capacity Management/VMs','daily_vm_top_bottom_capacity_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (167,'Storage Top Bottom Capacity','This report shows the top and bottom data stores based on their level of consumption as of the date indicated.','Storage Top Bottom Capacity','Capacity Management/Storage','daily_storage_top_bottom_capacity_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (168,'Host Top CPU Ready Queue','Shows top machines by CPU ready queue utilization ','Host Top CPU Ready Queue','Performance Management/Hosts','daily_pm_top_cpu_ready_queue_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (169,'Top Host Utilization by Resource','Shows top machines by utilization of each resource type','Top Host Utilization by Resource','Performance Management/Hosts','daily_pm_top_resource_utilization_bar','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (170,'Host/VM Groups - 30 Day Stats vs Thresholds','Shows a roll-up of average utilization values per day for 30 days for each grouping of machines.  Values are highlighted where they cross certain threshold values that may indicate a condition of over utilization of resources. ','Machine Groups 30 Day Avg Stats vs Thresholds','Capacity Management/Hosts','daily_cluster_30_days_avg_stats_vs_thresholds_grid','Daily',NULL);
-- INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (171,'Host/VM Groups - Day Over Day','Compares measurements for each machine group day-over-day and shows cases where there are noticeable differences. ','Machine Groups Day Over Day','Performance Management/Hosts','daily_cluster_day_over_day_grid');
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (172,'Storage Associated with Dormant VMs','This report shows the amounts of storage used by virtual machines that have been dormant for several days.  This storage has the potential to be reclaimed, depending upon the final disposition of such VMs. ','Storage Associated with Dormant VMs','Capacity Management/Storage','daily_potential_storage_waste_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (173,'Storage Top Disk Consumption','This report presents two independent views of information related to VDisk storage. The first highlights data stores that possess the largest amounts of VDisk storage.  The second lists Virtual Machines organized most to least in terms of their consumption of VDisk storage. ','Storage Top Disk','Capacity Management/Storage','daily_digest_storage_top_disk_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (175,'Storage Top Log Consumption','This report presents two independent views of information related to Log storage. The first highlights data stores that possess the largest amounts of Log storage.  The second lists Virtual Machines organized most to least in terms of their consumption of Log storage. ','Storage Top Log','Capacity Management/Storage','daily_digest_storage_top_log_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (176,'Storage Top Snapshot Consumption','This report presents two independent views of information related to Snapshot storage. The first highlights data stores that possess the largest amounts of Snapshot storage.  The second lists Virtual Machines organized most to least in terms of their consumption of Snapshot storage. ','Storage Top Snapshot','Capacity Management/Storage','daily_digest_storage_top_snapshot_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (177,'Storage Top Swap Consumption','This report presents two independent views of information related to Swap storage. The first highlights data stores that possess the largest amounts of Swap storage.  The second lists Virtual Machines organized most to least in terms of their consumption of Swap storage. ','Storage Top Swap','Capacity Management/Storage','daily_digest_storage_top_swap_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (178,'Storage Wasted Allocations','This report presents data stores that possess the largest amounts of wasted storage.  Wasted storage is taken as storage used for purposes not directly associated with supporting the operation of a VM.','Storage Waste','Capacity Management/Storage','daily_digest_storage_top_unused_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (179,'Storage Access IO Latency','This report presents two independent views of information related to Latency in accessing storage. The first highlights data stores having the largest amounts of storage access latency.  The second lists Virtual Machines organized most to least in terms of latency in accessing storage. ','Digest Storage Top Latency','Performance Management/Storage','daily_digest_storage_top_latency_grid','Daily',NULL);
INSERT INTO standard_reports (id,title,description,short_desc,category,filename,period,day_type) VALUES (180,'Storage Access IOPS','This report presents two independent views of information related to IOPS for storage. The first highlights data stores that possess the largest usage of IOPS.  The second lists Virtual Machines organized most to least in terms of their use of IOPS related to storage. ','Digest Storage Top Latency','Performance Management/Storage','daily_digest_storage_top_iops_grid','Daily',NULL);

SET IDENTITY_INSERT standard_reports OFF
go



delete from user_reports where id in (7,10,13,16);
go

SET IDENTITY_INSERT user_reports ON

INSERT INTO user_reports (id,title,category,short_desc,description,xml_descriptor,period,day_type) VALUES (7,'Top 20 Hosts by CPU','Capacity Management','Top 20 Hosts by CPU','Top 20 Hosts by CPU during the most recent prior hour','<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<user_report>\n  <title>&gt;Top 20 Hosts by CPU</title>\n  <table>user_pm_stats_by_hour</table>\n  <limit>20</limit>\n  <fields>\n    <field>instance_name</field>\n    <field>property_type</field>\n    <field>avg_value</field>\n    <field>recorded_on</field>\n    <field>hour_number</field>\n  </fields>\n  <filter_by>\n    <filter>\n      <field>property_type</field>\n      <op>equal</op>\n      <value>CPU</value>\n    </filter>\n  </filter_by>\n  <order_by>\n    <order>\n      <field>recorded_on</field>\n      <direction>desc</direction>\n      <order>1</order>\n    </order>\n    <order>\n      <field>hour_number</field>\n      <direction>desc</direction>\n      <order>2</order>\n    </order>\n    <order>\n      <field>avg_value</field>\n      <direction>desc</direction>\n      <order>3</order>\n    </order>\n  </order_by>\n</user_report>\n','Daily',NULL);
INSERT INTO user_reports (id,title,category,short_desc,description,xml_descriptor,period,day_type) VALUES (10,'Top 20 VMs by Storage','Capacity Management','Top 20 VMs by Storage','Top 20 VMs by Storage (M Bytes) from the most recent hourly values recorded','<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<user_report>\n  <title>&gt;Top 20 VMs by Storage</title>\n  <table>user_vm_stats_by_hour</table>\n  <limit>20</limit>\n  <fields>\n    <field>instance_name</field>\n    <field>property_type</field>\n    <field>avg_value</field>\n    <field>recorded_on</field>\n    <field>hour_number</field>\n  </fields>\n  <filter_by>\n    <filter>\n      <field>property_type</field>\n      <op>equal</op>\n      <value>StorageAmount</value>\n    </filter>\n    <filter>\n      <field>property_subtype</field>\n      <op>equal</op>\n      <value>used</value>\n    </filter>\n  </filter_by>\n  <order_by>\n    <order>\n      <field>recorded_on</field>\n      <direction>desc</direction>\n      <order>1</order>\n    </order>\n    <order>\n      <field>hour_number</field>\n      <direction>desc</direction>\n      <order>2</order>\n    </order>\n    <order>\n      <field>avg_value</field>\n      <direction>desc</direction>\n      <order>3</order>\n    </order>\n  </order_by>\n</user_report>\n','Daily',NULL);
INSERT INTO user_reports (id,title,category,short_desc,description,xml_descriptor,period,day_type) VALUES (13,'Top 20 VMs by CPU','Capacity Management','Top 20 VMs by CPU','Top 20 VMs by CPU most recently recorded','<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<user_report>\n  <title>&gt;Top 20 VMs by CPU</title>\n  <table>user_vm_stats_by_hour</table>\n  <limit>20</limit>\n  <fields>\n    <field>instance_name</field>\n    <field>property_type</field>\n    <field>avg_value</field>\n    <field>recorded_on</field>\n    <field>hour_number</field>\n  </fields>\n  <filter_by>\n    <filter>\n      <field>property_type</field>\n      <op>equal</op>\n      <value>VCPU</value>\n    </filter>\n  </filter_by>\n  <order_by>\n    <order>\n      <field>recorded_on</field>\n      <direction>desc</direction>\n      <order>1</order>\n    </order>\n    <order>\n      <field>hour_number</field>\n      <direction>desc</direction>\n      <order>2</order>\n    </order>\n    <order>\n      <field>avg_value</field>\n      <direction>desc</direction>\n      <order>3</order>\n    </order>\n  </order_by>\n</user_report>\n','Daily',NULL);
INSERT INTO user_reports (id,title,category,short_desc,description,xml_descriptor,period,day_type) VALUES (16,'Host Utilization for Prior Day','Capacity Management','Host Utilization Sumary for Prior Day','Host Utilization for Prior Day, listing each property having a non-zero level of utilization','<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<user_report>\n  <title>&gt;Host Utilization for Prior Day</title>\n  <table>user_pm_stats_by_day</table>\n  <limit>500</limit>\n  <fields>\n    <field>instance_name</field>\n    <field>property_type</field>\n    <field>capacity</field>\n    <field>avg_value</field>\n    <field>recorded_on</field>\n  </fields>\n  <filter_by>\n    <filter>\n      <field>avg_value</field>\n      <op>greater than</op>\n      <value>0.00</value>\n    </filter>\n    <filter>\n      <field>recorded_on</field>\n      <op>equal</op>\n      <value>convert(date, dbo.date_sub(dbo.now(),1))</value>\n    </filter>\n    <filter>\n      <field>property_subtype</field>\n      <op>equal</op>\n      <value>utilization</value>\n    </filter>\n  </filter_by>\n  <order_by>\n    <order>\n      <field>property_type</field>\n      <direction>asc</direction>\n      <order>1</order>\n    </order>\n    <order>\n      <field>instance_name</field>\n      <direction>asc</direction>\n      <order>2</order>\n    </order>\n  </order_by>\n</user_report>\n','Daily',NULL);

SET IDENTITY_INSERT user_reports OFF
go



delete from on_demand_reports ;
go

SET IDENTITY_INSERT on_demand_reports ON

INSERT INTO on_demand_reports (id,obj_type,scope_type,short_desc,filename,description,category,title) VALUES (1,'PhysicalMachine','Group','Host Group Summary','pm_group_profile','Host Group Summary','Performance Management/Hosts','Host Group Summary');
INSERT INTO on_demand_reports (id,obj_type,scope_type,short_desc,filename,description,category,title) VALUES (2,'PhysicalMachine','Instance','Host Summary','pm_profile','Host Summary','Performance Management/Hosts','Host Summary');
INSERT INTO on_demand_reports (id,obj_type,scope_type,short_desc,filename,description,category,title) VALUES (3,'Storage','Group','Datastore Group Summary','sd_group_profile','Datastore Group Summary','Performance Management/Storage','Datastore Group Summary');
INSERT INTO on_demand_reports (id,obj_type,scope_type,short_desc,filename,description,category,title) VALUES (4,'Storage','Instance','Data Store Summary','sd_profile','Data Store Summary','Performance Management/Storage','Data Store Summary');
INSERT INTO on_demand_reports (id,obj_type,scope_type,short_desc,filename,description,category,title) VALUES (5,'VirtualMachine','Group','VM Group Summary','vm_group_profile','VM Group Summary','Performance Management/VMs','VM Group Summary');
INSERT INTO on_demand_reports (id,obj_type,scope_type,short_desc,filename,description,category,title) VALUES (6,'VirtualMachine','Instance','Virtual Machine Summary','vm_profile','Virtual Machine Summary','Performance Management/VMs','Virtual Machine Summary');
INSERT INTO on_demand_reports (id,obj_type,scope_type,short_desc,filename,description,category,title) VALUES (7,'PhysicalMachine','Group','Host Group Capacity Usage Projection','pm_group_capacity_usage_projection','Host Group Capacity Usage Projection','Capacity Management/Hosts','Host Group Capacity Usage Projection');
INSERT INTO on_demand_reports (id,obj_type,scope_type,short_desc,filename,description,category,title) VALUES (8,'PhysicalMachine','Group','Hosting Summary by Host Group','pm_group_hosting','Hosting Summary by Host Group','Capacity Management/Hosts','Hosting Summary by Host Group');

SET IDENTITY_INSERT on_demand_reports OFF
go