{
 "title": "Scope Table overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Latest_Write",
    "query": "select to_char( max(start), 'YYYY-MM-DD HH24:MI:SS.MS+00') from scope;"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Rows per Scope Type",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT scoped_type, (count(*) / SUM(count(*)) OVER ()) AS \"% of total\", count(*) as \"rows\"\nFROM scope\ngroup by scoped_type"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  count(*) as \"Total\", \n  count(*) filter (where finish = '9999-12-31 00:00:00+00') as \"Live\"\nfrom scope"
    }
   ]
  },
  {
   "title": "Latest Write",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select scoped_type, (count(*) / sum(count(*)) OVER ()) as percentage\nfrom scope\nwhere start = '${Latest_Write}'\ngroup by scoped_type\norder by percentage desc"
    }
   ]
  },
  {
   "title": "Latest Write with entity types",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select entity.type || ' -> ' || scoped_type as pair, (count(*) / sum(count(*)) OVER ()) as percentage\nfrom scope, entity\nwhere seed_oid = entity.oid and start = '${Latest_Write}'\ngroup by entity.type, scoped_type\norder by percentage desc"
    }
   ]
  },
  {
   "title": "Live vs Finished",
   "type": "barchart",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "select scoped_type, count(*) as Total, count(*) filter (where finish = '9999-12-31 00:00:00+00') as Live\nfrom scope\ngroup by scoped_type\norder by Total desc"
    }
   ]
  },
  {
   "title": "Number of Rows written (Cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT \n  start as time,  \n  count(*)\nFROM scope\nWHERE\n  (start, finish) overlaps ($__timeFrom(), $__timeTo())\ngroup by start\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of Rows written (per type)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT \n  start as time,\n  scoped_type as metric,\n  count(*) as \"numberOfRows\"\nFROM scope\nWHERE\n  (start, finish) overlaps ($__timeFrom(), $__timeTo())\ngroup by start, scoped_type\nhaving count(*) > 0\nORDER BY 1, 2"
    }
   ]
  }
 ]
}