{
 "title": "Consumption Summary of Physical Resources for Virtual Machines",
 "description": "Average consumption of physical resources for a group of virtual machines.",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "SELECT\n  name as __text,\n  oid as __value\nFROM entity\nWHERE\n  entity.type = 'GROUP'\n  AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND attrs -> 'member_types' ? 'VIRTUAL_MACHINE'\nGROUP BY name, oid\nORDER BY 1"
   },
   {
    "name": "GroupClause",
    "query": "SELECT CASE\n  WHEN ${Group:raw} + 0 = 0 THEN ''\n  ELSE concat('JOIN  scope s ',\n    'ON (m.entity_oid = s.scoped_oid ',\n    'AND m.time between s.start and s.finish ',\n    'AND s.seed_oid = ${Group:raw} + 0)')\nEND"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Average CPU usage measurement",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics_data AS (\n  SELECT m.time, m.entity_oid, m.consumed as value\n  FROM metric m, entity e\n  WHERE m.time  BETWEEN $__timeFrom() AND $__timeTo()\n    AND m.type = 'CPU'\n    AND e.oid = m.entity_oid\n    AND e.type = 'VIRTUAL_MACHINE'\n), daily_avg_metrics as (\n  SELECT\n    date_trunc('day', m.time) as \"time\",\n    m.entity_oid,\n    avg(m.value) as value\n    FROM metrics_data m\n    ${GroupClause:raw}\n  GROUP BY 1, 2\n)\nSELECT\n  daily_avg_metrics.time,\n  sum(daily_avg_metrics.value) as \"CPU Usage\"\nFROM daily_avg_metrics\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "graph",
   "description": "Average memory usage measurement",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics_data AS (\n  SELECT m.time, m.entity_oid, m.consumed as value\n  FROM metric m, entity e\n  WHERE m.time  BETWEEN $__timeFrom() AND $__timeTo()\n    AND m.type = 'MEM'\n    AND e.oid = m.entity_oid\n    AND e.type = 'VIRTUAL_MACHINE'\n), daily_avg_metrics as (\n  SELECT\n    date_trunc('day', m.time) as \"time\",\n    m.entity_oid,\n    avg(m.value) as value\n    FROM metrics_data m\n    ${GroupClause:raw}\n  GROUP BY 1, 2\n)\nSELECT\n  daily_avg_metrics.time,\n  sum(daily_avg_metrics.value) as \"Mem Usage\"\nFROM daily_avg_metrics\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "graph",
   "description": "Average storage used measurement",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics_data AS (\n  SELECT m.time, m.entity_oid, m.consumed as value\n  FROM metric m, entity e\n  WHERE m.time  BETWEEN $__timeFrom() AND $__timeTo()\n    AND m.type = 'STORAGE_AMOUNT'\n    AND e.oid = m.entity_oid\n    AND e.type = 'VIRTUAL_MACHINE'\n), daily_avg_metrics as (\n  SELECT\n    date_trunc('day', m.time) as \"time\",\n    m.entity_oid,\n    avg(m.value) as value\n    FROM metrics_data m\n    ${GroupClause:raw}\n  GROUP BY 1, 2\n)\nSELECT\n  daily_avg_metrics.time,\n  sum(daily_avg_metrics.value) as \"Storage Used\"\nFROM daily_avg_metrics\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage Access - IOPS",
   "type": "graph",
   "description": "Average storage IOPS measurement",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "IOPS" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics_data AS (\n  SELECT m.time, m.entity_oid, m.consumed as value\n  FROM metric m, entity e\n  WHERE m.time  BETWEEN $__timeFrom() AND $__timeTo()\n    AND m.type = 'STORAGE_ACCESS'\n    AND e.oid = m.entity_oid\n    AND e.type = 'VIRTUAL_MACHINE'\n), daily_avg_metrics as (\n  SELECT\n    date_trunc('day', m.time) as \"time\",\n    m.entity_oid,\n    avg(m.value) as value\n    FROM metrics_data m\n    ${GroupClause:raw}\n  GROUP BY 1, 2\n)\nSELECT\n  daily_avg_metrics.time,\n  sum(daily_avg_metrics.value) as \"Storage Access - IOPS\"\nFROM daily_avg_metrics\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Virtual Machine Physical Resource Usage",
   "type": "table-old",
   "description": "Average measurement for each VM in the selected group",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH metrics_data AS (\n  SELECT m.entity_oid, e.name as entity_name, m.consumed as value, m.type as metric_type\n  FROM metric m\n  JOIN entity e ON (e.oid = m.entity_oid)\n  ${GroupClause:raw}\n  WHERE m.time  BETWEEN $__timeFrom() AND $__timeTo()\n    AND m.type IN ('CPU', 'MEM', 'STORAGE_AMOUNT')\n    AND e.type = 'VIRTUAL_MACHINE'\n)\nSELECT\n  m.entity_name as \"VM Name\",\n  avg(m.value) FILTER (WHERE m.metric_type = 'MEM') AS \"Mem\",\n  avg(m.value) FILTER (WHERE m.metric_type = 'CPU') AS \"CPU\",\n  avg(m.value) FILTER (WHERE m.metric_type = 'STORAGE_AMOUNT') AS \"Storage\"\nFROM metrics_data m\nGROUP BY m.entity_oid, m.entity_name\nORDER BY m.entity_name"
    }
   ]
  }
 ]
}