{
 "title": "Consumption Summary of Physical Resources for Virtual Machines",
 "description": "Average consumption of physical resources for a group of virtual machines.",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "select name as __text, oid as __value from entity where entity.type = 'GROUP' and ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) group by name, oid order by 1"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Average CPU usage measurement ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time) as \"time\",\n  avg(metric.consumed) AS \"CPU Usage\"\nFROM metric, entity\nWHERE\n  $__timeFilter(\"time\") AND\n  metric.type = 'CPU' AND\n  metric.entity_oid = entity.oid AND\n  metric.entity_hash = entity.hash AND\n  entity.type = 'VIRTUAL_MACHINE' AND \n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (entity.scope && ARRAY[ [[Group]] ]::bigint[]) END\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "graph",
   "description": "Average memory usage measurement",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time) as \"time\",\n  avg(metric.consumed) AS \"Mem Usage\"\nFROM metric, entity\nWHERE\n  $__timeFilter(\"time\") AND\n  metric.type = 'MEM' AND\n  metric.entity_oid = entity.oid AND\n  metric.entity_hash = entity.hash AND\n  entity.type = 'VIRTUAL_MACHINE' AND \n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (entity.scope && ARRAY[ [[Group]] ]::bigint[]) END\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "graph",
   "description": "Average storage used measurement ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time) as \"time\",\n  avg(metric.consumed) AS \"Storage Usage\"\nFROM metric, entity\nWHERE\n  $__timeFilter(\"time\") AND\n  metric.type = 'STORAGE_AMOUNT' AND\n  metric.entity_oid = entity.oid AND\n  metric.entity_hash = entity.hash AND\n  entity.type = 'VIRTUAL_MACHINE' AND \n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (entity.scope && ARRAY[ [[Group]] ]::bigint[]) END\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage Access - IOPS",
   "type": "graph",
   "description": "Average storage IOPS measurement ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "IOPS" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time) as \"time\",\n  avg(metric.consumed) AS \"Storage Access - IOPS\"\nFROM metric, entity\nWHERE\n  $__timeFilter(\"time\") AND\n  metric.type = 'STORAGE_ACCESS' AND\n  metric.entity_oid = entity.oid AND\n  metric.entity_hash = entity.hash AND\n  entity.type = 'VIRTUAL_MACHINE' AND \n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (entity.scope && ARRAY[ [[Group]] ]::bigint[]) END\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Virtual Machine Physical Resource Usage ",
   "type": "table-old",
   "description": "Average measurement for each VM in the selected group  ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  e.name as \"VM Name\",\n  avg(m.consumed) FILTER (WHERE m.type = 'MEM') AS \"Mem\",\n  avg(m.consumed) FILTER (WHERE m.type = 'CPU') AS \"CPU\",\n  avg(m.consumed) FILTER (WHERE m.type = 'STORAGE_AMOUNT') AS \"Storage\"\nFROM metric as m, entity as e\nWHERE\n  $__timeFilter(m.time) AND\n  m.type IN ('MEM', 'CPU', 'STORAGE_AMOUNT') AND\n  m.entity_oid = e.oid AND\n  m.entity_hash = e.hash AND\n  e.type = 'VIRTUAL_MACHINE' AND \n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}