{
 "title": "Datastore Group Summary",
 "description": "Performance and capacity profile, including trends, for selected datastores.",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "SELECT\n  name as __text,\n  oid as __value\nFROM entity\nWHERE\n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND (type = 'STORAGE_CLUSTER'\n    OR (type = 'GROUP' AND attrs -> 'member_types' ? 'STORAGE'))\nORDER BY 1"
   },
   {
    "name": "JoinClause",
    "query": "SELECT\n  CASE WHEN '${Group:raw}' = '0'\n  THEN concat(\n    'JOIN entity e ON ',\n      'm.entity_oid = e.oid ',\n      'AND e.type = ''STORAGE'' ',\n      'AND ('$__timeFrom()', '$__timeTo()') OVERLAPS (e.first_seen, e.last_seen) ',\n  '')\n  ELSE concat(\n    'JOIN scope s ON ',\n      's.seed_oid = ${Group:raw} ',\n      'AND m.entity_oid = s.scoped_oid ',\n      'AND m.time BETWEEN s.start AND s.finish ',\n      'AND s.scoped_type = ''STORAGE'' ',\n      'AND ('$__timeFrom()', '$__timeTo()') OVERLAPS (s.start, s.finish) ',\n  '')\n  END"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Datastore Avg Consumption",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(used) AS \"Storage Used\",\n  sum(capacity) AS \"Storage Capacity\",\n  round((sum(used)/ NULLIF(sum(capacity), 0))::NUMERIC, 4) AS \"Utilization\"\nFROM\n   (\n    WITH unique_data as(\n    SELECT\n        m.entity_oid AS oid,\n        m.current,\n        m.capacity\n    FROM metric m\n    ${JoinClause:raw}\n    WHERE\n    -- fixed conditions\n    m.type = 'STORAGE_AMOUNT'\n    -- conditions involving dashboard vars\n    AND m.\"time\" BETWEEN timestamptz $__timeFrom() AND $__timeTo()\n    GROUP BY m.time, m.entity_oid, m.current, m.capacity\n    )\n    SELECT unique_data.oid, avg(unique_data.current) AS used, avg(unique_data.capacity)::NUMERIC AS capacity\n    FROM unique_data\n    GROUP BY unique_data.oid\n   ) AS data_tbl"
    }
   ]
  },
  {
   "title": "Datastore Performance Stats",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH metrics AS (\n   SELECT m.utilization, m.current, m.type\n   FROM metric m\n   ${JoinClause:raw}\n   WHERE\n     -- fixed conditions\n     m.type in ('STORAGE_AMOUNT','STORAGE_ACCESS','STORAGE_LATENCY')\n     -- conditions related to dashboard vars\n     AND m.\"time\" BETWEEN $__timeFrom() AND $__timeTo()\n   GROUP BY m.time, m.entity_oid, m.utilization, m.CURRENT, m.type\n  )\nSELECT\n  unnest(array['AVG','MIN','MAX']) as \"Aggregation\",\n  unnest(array[\n    avg(metrics.utilization) FILTER (WHERE metrics.type = 'STORAGE_AMOUNT'),\n    min(metrics.utilization) FILTER (WHERE metrics.type = 'STORAGE_AMOUNT'),\n    max(metrics.Utilization) FILTER (WHERE metrics.type = 'STORAGE_AMOUNT')\n  ]) AS \"Utilization\",\n  unnest(array[\n    avg(metrics.current) FILTER (WHERE metrics.type = 'STORAGE_ACCESS'),\n    min(metrics.current) FILTER (WHERE metrics.type = 'STORAGE_ACCESS'),\n    max(metrics.current) FILTER (WHERE metrics.type = 'STORAGE_ACCESS')\n  ]) AS \"IOPS\",\n  unnest(array[\n    avg(metrics.current) FILTER (WHERE metrics.type = 'STORAGE_LATENCY'),\n    min(metrics.current) FILTER (WHERE metrics.type = 'STORAGE_LATENCY'),\n    max(metrics.current) FILTER (WHERE metrics.type = 'STORAGE_LATENCY')\n  ]) AS \"Latency\"\nFROM metrics"
    }
   ]
  },
  {
   "title": "Datastore Consumption Trend",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics AS (\n   SELECT m.time, m.capacity, m.current\n   FROM metric m\n   ${JoinClause:raw}\n   WHERE\n     -- fixed conditions\n     m.type = 'STORAGE_AMOUNT'\n     -- conditions related to dashboard vars\n     AND \"time\" BETWEEN $__timeFrom() AND $__timeTo()\n     GROUP BY m.time, m.entity_oid, m.capacity, m.current\n)\nSELECT\n  date_trunc('hour', m.time) as \"time\",\n  ROUND((sum(m.current)/sum(m.capacity))::NUMERIC, 4) AS \"Storage Amount Used\"\nFROM metrics m\nGROUP BY date_trunc('hour', m.time)"
    }
   ]
  },
  {
   "title": "Datastore Performance Trends",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics AS (\n   SELECT m.time, m.current, m.type\n   FROM metric m\n   ${JoinClause:raw}\n   WHERE\n     -- fixed conditions\n     m.type IN ('STORAGE_ACCESS', 'STORAGE_LATENCY')\n     -- conditions related to dashboard vars\n     AND \"time\" BETWEEN $__timeFrom() AND $__timeTo()\n   GROUP BY m.time, m.entity_oid, m.current, m.type\n)\nSELECT\n  m.time,\n  avg(m.current) FILTER (WHERE m.type = 'STORAGE_ACCESS') AS \"IOPS Avg\",\n  avg(m.current) FILTER (WHERE m.type = 'STORAGE_LATENCY') AS \"Latency Avg\"\nFROM metrics m\nGROUP BY m.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Consumption Stats By Datastore",
   "type": "table",
   "description": "Average values.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n   SELECT e1.name entity_name, m.time, m.entity_oid, m.current, m.capacity, m.utilization, m.type\n   FROM metric m\n   ${JoinClause:raw}\n   JOIN entity e1 ON\n      e1.oid = m.entity_oid\n   WHERE\n     -- fixed conditions\n     m.type IN ('STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n     -- conditions related to dashboard vars\n     AND \"time\" BETWEEN $__timeFrom() AND $__timeTo()\n   GROUP BY e1.name, m.time, m.entity_oid, m.current, m.capacity, m.utilization, m.type\n)\nSELECT d.entity_name as \"Datastore\"\n            ,avg(d.capacity) FILTER (WHERE d.type = 'STORAGE_AMOUNT') AS \"Storage Capacity\"\n            ,avg(d.current) FILTER (WHERE d.type = 'STORAGE_AMOUNT') AS \"Storage Used\"\n            ,avg(d.utilization) FILTER (WHERE d.type = 'STORAGE_AMOUNT') as \"Storage Utilization\"\n            ,avg(d.current) FILTER (WHERE d.type = 'STORAGE_PROVISIONED') as \"Storage Provisioned\"\n            ,avg(d.current) FILTER (WHERE d.type = 'STORAGE_PROVISIONED') /\n                  NULLIF(avg(d.capacity) FILTER (WHERE d.type = 'STORAGE_AMOUNT'), 0) as \"Storage Over-Provisioned\"\nFROM data d\nGROUP BY d.entity_name\nORDER BY 4 DESC"
    }
   ]
  },
  {
   "title": "Performance Stats By Datastore",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n  SELECT e1.name as entity_name, m.current, m.type\n  FROM metric m\n  ${JoinClause:raw}\n  JOIN entity e1 ON\n    e1.oid = m.entity_oid\n  WHERE\n    -- fixed conditions\n    m.type IN ('STORAGE_ACCESS', 'STORAGE_LATENCY')\n    -- conditions related to dashboard vars\n    AND m.time BETWEEN $__timeFrom() AND $__timeTo()\n  GROUP BY e1.name, m.time, m.entity_oid, m.current, m.type\n)\nSELECT d.entity_name as \"Datastore\"\n            ,avg(d.current) FILTER (WHERE d.type = 'STORAGE_ACCESS') AS \"IOPS Avg\"\n            ,max(d.current) FILTER (WHERE d.type = 'STORAGE_ACCESS') AS \"IOPS Max\"\n            ,avg(d.current) FILTER (WHERE d.type = 'STORAGE_LATENCY') AS \"Latency Avg\"\n            ,max(d.current) FILTER (WHERE d.type = 'STORAGE_LATENCY') AS \"Latency Max\"\nFROM data d\nGROUP BY d.entity_name\nORDER BY 2 DESC"
    }
   ]
  }
 ]
}