{
 "title": "Datastore Summary",
 "description": "Performance and capacity profile for datastores.",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Datastore",
    "query": "select name as __text, oid as __value from entity where ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) and entity.type = 'STORAGE' group by name, oid order by 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Datastore Summary",
   "type": "table-old",
   "description": "Capacity is max value. Provisioned Used, Used, IOPS and Latency are average values. ",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \nmax(metric.capacity) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS \"Capacity\",\navg(metric.current) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') AS \"Provisioned Used\",\navg(metric.current) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS \"Used\",\navg(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS') AS \"IOPS\",\navg(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY') AS \"Latency\"\nFROM metric, entity\nWHERE   \n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  entity.type = 'STORAGE' and \n  entity.oid = $Datastore and \n  entity.oid = metric.entity_oid and\n  $__timeFilter(\"time\")\n"
    }
   ]
  },
  {
   "title": "Datastore Resource Utilization",
   "type": "table-old",
   "description": "Average, min and max values datastore utilization, IOPS and latency. ",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \nunnest(array['1','2','3']) as \"order\",\nunnest(array['AVG','MIN','MAX']) as \"Aggregation\",\nunnest(array[avg(metric.utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'),\nmin(metric.utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'),\nmax(metric.Utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT')\n]) AS \"Utilization\",\nunnest(array[avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS'),\nmin(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS'),\nmax(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS')\n]) AS \"IOPS\",\nunnest(array[avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY'),\nmin(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY'),\nmax(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY')\n]) AS \"Latency\"\nFROM metric, entity\nWHERE entity.type = 'STORAGE' and \nentity.oid = $Datastore and  \nentity.oid = metric.entity_oid and entity.hash = metric.entity_hash and\n  $__timeFilter(\"time\") and ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\nORDER BY \"order\" asc\n\n\n"
    }
   ]
  },
  {
   "title": "Virtual Machine Summary",
   "type": "table-old",
   "description": "Storage used, average and max IOPS and latency for VMs consuming resources from datastore. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n    max(sub.name) as \"VM Name\",\n    max(sub.value) FILTER (WHERE sub.type = 'STORAGE_AMOUNT') AS \"Storage Used\",\n    avg(sub.value) FILTER (WHERE sub.type = 'STORAGE_ACCESS') AS \"Avg IOPS\",\n    max(sub.value) FILTER (WHERE sub.type = 'STORAGE_ACCESS') AS \"Max IOPS\",\n    avg(sub.value) FILTER (WHERE sub.type = 'STORAGE_LATENCY') AS \"Avg Latency\",\n    max(sub.value) FILTER (WHERE sub.type = 'STORAGE_LATENCY') AS \"Max Latency\"\nFROM (\n        select entity.oid as oid,\n               entity.name as name,\n               metric.type as type,\n               sum(metric.consumed) as value \n          from metric, entity\n         WHERE entity.type = 'VIRTUAL_MACHINE'\n           and entity.scope && (array[ [[Datastore]] ])\n           and entity.oid = metric.entity_oid and entity.hash = metric.entity_hash \n           and (metric.type = 'STORAGE_LATENCY' or metric.type = 'STORAGE_ACCESS') \n           and $__timeFilter(\"time\") and ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n         GROUP BY time, 1, 2, 3\n       union\n        select entity.oid as oid,\n               max(entity.name) as name,\n               max(metric.type) as type,\n               sum(metric.consumed) as value \n          from metric, entity\n         WHERE entity.type = 'VIRTUAL_MACHINE' \n           and entity.scope && (array[ [[Datastore]] ])\n           and entity.oid = metric.entity_oid and entity.hash = metric.entity_hash and metric.type = 'STORAGE_AMOUNT'\n           and $__timeFilter(\"time\") and  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n         GROUP BY time, entity.oid\n) sub\ngroup by sub.oid"
    }
   ]
  },
  {
   "title": "Wasted Files on Datastore",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT path as \"File Path\",\n       file_size_kb as \"File Size\",\n       modification_time as \"Last Modified Time\"\n  FROM wasted_file\n WHERE storage_oid = $Datastore\n ORDER BY 2 DESC"
    }
   ]
  }
 ]
}