{
 "title": "Individual Host Cluster Summary",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Cluster",
    "query": "SELECT\n  name as __text,\n  oid as __value\nFROM\n  entity\nWHERE\n  entity.type = 'COMPUTE_CLUSTER'\n  AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Counts",
   "type": "table",
   "description": "This panel shows counts for the entire cluster based on the most recent date in the time selection",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with pm_counts as (\n  SELECT\n      count(distinct oid) as pm_count,\n      sum(cpus) as cpu_count,\n      sum(mem) as pm_mem\n  from\n      (\n      select\n          entity.oid,\n          avg((entity.attrs -> 'num_cpus')::int) as cpus,\n          avg(metric.capacity) as mem\n      from\n          metric, entity, scope\n      where\n          -- join conditions\n          metric.entity_oid = entity.oid\n          and entity.oid = scope.scoped_oid\n          and metric.time between scope.start and scope.finish\n          -- fixed conditions\n          and metric.type = 'MEM'\n          and scope.scoped_type = 'PHYSICAL_MACHINE'\n          -- conditions involving dashboard vars\n          and metric.time between timestamptz $__timeTo() - interval '1 hour' and $__timeTo()\n          and (timestamptz $__timeTo() - interval '1 hour', $__timeTo()) overlaps (scope.start, scope.finish)\n          and scope.seed_oid = ${Cluster:raw} + 0\n      group by 1) as pm_data\n),\n-- WITH...\nvm_counts as (\n  select\n      count(distinct oid) as vm_count, sum(vcpus) as vcpu_count, sum(vmem) as vm_vmem\n  from\n      (\n      select\n          entity.oid,\n          avg((attrs -> 'num_cpus')::int) as vcpus,\n          avg(capacity) as vmem\n      from\n          metric, entity, scope\n      where\n          -- join conditions\n          metric.entity_oid = entity.oid\n          and entity.oid = scope.scoped_oid\n          and metric.time between scope.start and scope.finish\n          -- fixed conditions\n          and metric.type = 'VMEM'\n          and scope.scoped_type = 'VIRTUAL_MACHINE'\n          -- conditions involving dashboard vars\n          and metric.time between timestamptz $__timeTo() - interval '1 hour' and $__timeTo()\n          and (timestamptz $__timeTo() - interval '1 hour', $__timeTo()) overlaps (scope.start, scope.finish)\n          and scope.seed_oid = ${Cluster:raw}\n      group by 1) as vm_data\n),\n-- WITH ...\nstorage_stats as (\n  select\n      sum(stor_used) as stor_used, sum(stor_cap) as stor_cap, sum(stor_prov) as stor_prov\n  from\n      (\n      select\n          entity.oid,\n          MAX(current) filter (where metric.type = 'STORAGE_AMOUNT') as stor_used,\n          MAX(capacity) filter (where metric.type = 'STORAGE_AMOUNT') as stor_cap,\n          MAX(current) filter (where metric.type = 'STORAGE_PROVISIONED') as stor_prov\n      from\n          metric, entity, scope\n      where\n          -- join conditions\n          metric.entity_oid = entity.oid\n          and entity.oid = scope.scoped_oid\n          and metric.time between scope.start and scope.finish\n          -- fixed conditions\n          and metric.type in ('STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n          and scope.scoped_type = 'STORAGE'\n          -- conditions involving dashboard vars\n          and metric.time between timestamptz $__timeTo() - interval '1 hour' and $__timeTo()\n          and (timestamptz $__timeTo() - interval '1 hour', $__timeTo()) overlaps (scope.start, scope.finish)\n          and scope.seed_oid = ${Cluster:raw}\n      group by 1) as stg_data\n)\nselect\npm_count as \"Hosts\",\nvm_count as \"VMs\",\npm_mem / 1024 / 1024 as \"Mem Capacity\",\nvm_vmem / 1024 / 1024 as \"VMem Provisioned\",\ncpu_count as \"Host CPUs\",\nvcpu_count as \"VCPUs Provisioned\",\nstor_cap / 1024 as \"Total Storage\",\n(stor_cap - stor_used)/ 1024 as \"Available Storage\",\nstor_prov / 1024 as \"Allocated Storage\"\nfrom\npm_counts, vm_counts, storage_stats"
    }
   ]
  },
  {
   "title": "VM and Host Count Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH pm_counts AS (\n    SELECT\n      date_trunc('day', metric.time) as time,\n      count(distinct oid) as pm_count\n    FROM\n        metric\n    JOIN scope ON metric.entity_oid = scope.scoped_oid\n        AND metric.time between scope.start and scope.finish\n    JOIN entity ON entity.oid = scope.seed_oid\n    WHERE\n      -- fixed conditions\n      metric.type = 'MEM'\n      AND scope.scoped_type = 'PHYSICAL_MACHINE'\n      AND metric.time - date_trunc('day', metric.time) < interval '10 minutes'\n      -- conditions involving dashboard vars\n      AND metric.time between timestamptz $__timeFrom() and $__timeTo()\n      AND ($__timeFrom(), $__timeTo()) OVERLAPS (scope.start, scope.finish)\n      AND scope.seed_oid = ${Cluster:raw} + 0\n    GROUP BY 1),\n-- WITH...\nvm_counts as (\n    SELECT\n       date_trunc('day', metric.time) as time,\n       count(distinct oid) as vm_count\n    FROM\n        metric\n    JOIN scope ON metric.entity_oid = scope.seed_oid\n        AND metric.time between scope.start and scope.finish\n        AND scope.scoped_type = 'COMPUTE_CLUSTER'\n    JOIN entity ON entity.oid = scope.seed_oid\n        AND entity.type = 'VIRTUAL_MACHINE'\n    WHERE\n      -- fixed conditions\n      metric.type = 'VMEM'\n      AND metric.time - date_trunc('day', metric.time) < interval '10 minutes'\n      -- conditions involving dashboard vars\n      AND metric.time between timestamptz $__timeFrom() and $__timeTo()\n      AND ($__timeFrom(), $__timeTo()) OVERLAPS (start, finish)\n      AND scope.scoped_oid = ${Cluster:raw}::bigint\n    GROUP BY 1)\nSELECT\n    pm_counts.time as time,\n    pm_count as \"Hosts\",\n    vm_count as \"VMs\"\nFROM\n    pm_counts, vm_counts\nWHERE\n    pm_counts.time = vm_counts.time"
    }
   ]
  },
  {
   "title": "Current Stats",
   "type": "table",
   "description": "This panel shows current Memory and Storage stats across the cluster, based on the most recent date in the time selection.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Storage Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   time,\n   sum(stor_cap) as \"Total Storage\",\n   sum(stor_used) as \"Used Storage\",\n   sum(stor_prov) as \"Allocated Storage\"\n FROM\n   (SELECT\n     date_trunc('day', metric.time) as time,\n     metric.entity_oid,\n     MAX(current) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') as stor_used,\n     MAX(capacity) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') as stor_cap,\n     MAX(current) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') as stor_prov\n   FROM\n     metric\n     JOIN scope ON metric.entity_oid = scope.scoped_oid\n       AND metric.time between scope.start and scope.finish\n   WHERE\n     -- fixed conditions\n     metric.type in ('STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n     AND scope.scoped_type = 'STORAGE'\n     -- conditions involving dashboard vars\n     AND metric.time between $__timeFrom() and $__timeTo()\n     AND ($__timeFrom(), $__timeTo()) OVERLAPS (scope.start, scope.finish)\n     AND scope.seed_oid = ${Cluster:raw}::bigint + 0\n   GROUP BY 1, 2) AS data\n GROUP BY 1"
    }
   ]
  },
  {
   "title": "Current Ratios",
   "type": "table",
   "description": "This panel shows current VM ratios across the cluster, based on the most recent date in the time selection.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "CPU and Mem Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', m.time) AS time,\n   sum(m.current) FILTER (WHERE m.type = 'CPU') /\n      sum(m.capacity) FILTER (WHERE m.type = 'CPU') * 100 AS \"CPU Utilization\",\n   sum(m.current) FILTER (WHERE m.type = 'MEM') /\n      sum(m.capacity) FILTER (WHERE m.type = 'MEM') * 100 AS \"Mem Utilization\"\nFROM metric m\nJOIN scope s ON\n   m.entity_oid = s.scoped_oid\n   AND m.time BETWEEN s.start AND s.finish\nWHERE\n   -- fixed conditions\n   m.type IN ('MEM', 'CPU')\n   AND s.scoped_type = 'PHYSICAL_MACHINE'\n   -- conditions related to dashboard vars\n   AND m.time BETWEEN $__timeFrom() AND $__timeTo()\n   AND ($__timeFrom(), $__timeTo() ) OVERLAPS (START, finish)\n   AND s.seed_oid = ${Cluster:raw}::bigint + 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}