{
 "title": "Individual Host Cluster Summary",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Cluster",
    "query": "SELECT name as __text,\n               oid as __value \nFROM entity\nWHERE entity.type = 'COMPUTE_CLUSTER' \nAND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) \nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Counts",
   "type": "table",
   "description": "This panel shows counts for the entire cluster based on the most recent date in the time selection",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with pm_counts as (\n    SELECT count(distinct oid) as pm_count\n          ,sum(cpus) as cpu_count\n          ,sum(mem) as pm_mem\n      FROM\n        (SELECT oid\n               ,avg((attrs -> 'num_cpus')::int) as cpus\n               ,avg(capacity) as mem\n           FROM entity\n          INNER JOIN LATERAL (\n            SELECT capacity\n              FROM metric \n             WHERE metric.entity_oid = entity.oid\n               AND metric.entity_hash = entity.hash \n               AND metric.type = 'MEM'\n               AND metric.time between timestamptz $__timeTo() - INTERVAL '1 hour' and $__timeTo()\n             LIMIT 1\n          ) as foo ON true \n          WHERE type = 'PHYSICAL_MACHINE'\n            AND (timestamptz $__timeTo() - INTERVAL '1 hour', $__timeTo() ) OVERLAPS (first_seen, last_seen)\n            AND scope && ARRAY[ [[Cluster]] ] \n          GROUP BY 1) as bar\n    ),\n\nvm_counts as (\n    SELECT count(distinct oid) as vm_count\n          ,sum(vcpus) as vcpu_count\n          ,sum(vmem) as vm_vmem\n      FROM\n        (SELECT oid\n               ,avg((attrs -> 'num_cpus')::int) as vcpus\n               ,avg(capacity) as vmem\n           FROM entity\n          INNER JOIN LATERAL (\n            SELECT capacity\n              FROM metric \n             WHERE metric.entity_oid = entity.oid\n               AND metric.entity_hash = entity.hash \n               AND metric.type = 'VMEM'\n               AND metric.time between timestamptz $__timeTo() - INTERVAL '1 hour' and $__timeTo()  \n          ) as foo ON true \n          WHERE type = 'VIRTUAL_MACHINE'\n            AND (timestamptz $__timeTo() - INTERVAL '1 hour', $__timeTo()) OVERLAPS (first_seen, last_seen)\n            AND scope && ARRAY[ [[Cluster]] ] \n          GROUP BY 1) as bar\n    ),\n\nstorage_stats as (\n    SELECT sum(stor_used) as stor_used\n          ,sum(stor_cap) as stor_cap\n          ,sum(stor_prov) as stor_prov\n      FROM\n        (SELECT oid\n               ,MAX(current) FILTER (WHERE foo.type = 'STORAGE_AMOUNT') as stor_used\n               ,MAX(capacity) FILTER (WHERE foo.type = 'STORAGE_AMOUNT') as stor_cap\n               ,MAX(current) FILTER (WHERE foo.type = 'STORAGE_PROVISIONED') as stor_prov\n           FROM entity\n          INNER JOIN LATERAL (\n            SELECT type\n                  ,current\n                  ,capacity\n              FROM metric \n             WHERE metric.entity_oid = entity.oid\n               AND metric.entity_hash = entity.hash \n               AND metric.type in ('STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n               AND metric.time between timestamptz $__timeTo() - INTERVAL '1 hour' and $__timeTo() \n          ) as foo ON true \n          WHERE entity.type = 'STORAGE'\n            AND (timestamptz $__timeTo() - INTERVAL '1 hour', $__timeTo()) OVERLAPS (first_seen, last_seen)\n            AND scope && ARRAY[ [[Cluster]] ] \n          GROUP BY 1) as bar\n    )\n\nSELECT pm_count as \"Hosts\"\n      ,vm_count as \"VMs\"\n      ,pm_mem/1024/1024 as \"Mem Capacity\"\n      ,vm_vmem/1024/1024 as \"VMem Provisioned\"\n      ,cpu_count as \"Host CPUs\"\n      ,vcpu_count as \"VCPUs Provisioned\"\n      ,stor_cap/1024 as \"Total Storage\"\n      ,(stor_cap - stor_used)/1024 as \"Available Storage\"\n      ,stor_prov/1024 as \"Allocated Storage\"\n  FROM pm_counts, vm_counts, storage_stats"
    }
   ]
  },
  {
   "title": "VM and Host Count Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with pm_counts as (\n     SELECT date_trunc('day', foo.time) as time\n           ,count(distinct oid) as pm_count\n       FROM entity\n      INNER JOIN LATERAL (\n        SELECT time\n          FROM metric \n         WHERE metric.entity_oid = entity.oid\n           AND metric.entity_hash = entity.hash \n           AND metric.type = 'MEM'\n           AND metric.time between timestamptz $__timeFrom() and $__timeTo() \n           AND metric.time - date_trunc('day', metric.time) < interval '10 minutes'\n      ) as foo ON true \n      WHERE type = 'PHYSICAL_MACHINE'\n        AND ($__timeFrom() , $__timeTo()) OVERLAPS (first_seen, last_seen)\n        AND scope && ARRAY[ [[Cluster]] ] \n      GROUP BY 1),\n\nvm_counts as (\n     SELECT date_trunc('day', foo.time) as time\n           ,count(distinct oid) as vm_count\n       FROM entity\n      INNER JOIN LATERAL (\n        SELECT time\n          FROM metric \n         WHERE metric.entity_oid = entity.oid\n           AND metric.entity_hash = entity.hash \n           AND metric.type = 'VMEM'\n           AND metric.time between timestamptz $__timeFrom() and $__timeTo() \n           AND metric.time - date_trunc('day', metric.time) < interval '10 minutes'\n      ) as foo ON true \n      WHERE type = 'VIRTUAL_MACHINE'\n        AND ($__timeFrom() , $__timeTo()) OVERLAPS (first_seen, last_seen)\n        AND scope && ARRAY[ [[Cluster]] ] \n      GROUP BY 1)\n\nSELECT pm_counts.time as time\n      ,pm_count as \"Hosts\"\n      ,vm_count as \"VMs\"\n  FROM pm_counts, vm_counts\n WHERE pm_counts.time = vm_counts.time"
    }
   ]
  },
  {
   "title": "Current Stats",
   "type": "table",
   "description": "This panel shows current Memory and Storage stats across the cluster, based on the most recent date in the time selection.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Storage Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time\n      ,sum(stor_cap) as \"Total Storage\"\n      ,sum(stor_used) as \"Used Storage\"\n      ,sum(stor_prov) as \"Allocated Storage\"\n  FROM\n    (SELECT date_trunc('day', foo.time) as time\n           ,oid\n           ,MAX(current) FILTER (WHERE foo.type = 'STORAGE_AMOUNT') as stor_used\n           ,MAX(capacity) FILTER (WHERE foo.type = 'STORAGE_AMOUNT') as stor_cap\n           ,MAX(current) FILTER (WHERE foo.type = 'STORAGE_PROVISIONED') as stor_prov\n       FROM entity\n      INNER JOIN LATERAL (\n        SELECT time\n               ,type\n               ,current\n               ,capacity\n          FROM metric \n         WHERE metric.entity_oid = entity.oid\n           AND metric.entity_hash = entity.hash \n           AND metric.type in ('STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n           AND metric.time between timestamptz $__timeFrom() and $__timeTo()\n      ) as foo ON true \n      WHERE entity.type = 'STORAGE'\n        AND ($__timeFrom() , $__timeTo()) OVERLAPS (first_seen, last_seen)\n        AND scope && ARRAY[ [[Cluster]] ] \n      GROUP BY 1,2) as bar\n GROUP BY 1"
    }
   ]
  },
  {
   "title": "Current Ratios",
   "type": "table",
   "description": "This panel shows current VM ratios across the cluster, based on the most recent date in the time selection.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "CPU and Mem Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": " SELECT date_trunc('day', foo.time) as time\n       ,sum(current) FILTER (WHERE foo.type = 'CPU') /\n            sum(capacity) FILTER (WHERE foo.type = 'CPU') * 100 as \"CPU Utilization\"\n       ,sum(current) FILTER (WHERE foo.type = 'MEM') /\n            sum(capacity) FILTER (WHERE foo.type = 'MEM') * 100 as \"Mem Utilization\"\n   FROM entity\n  INNER JOIN LATERAL (\n    SELECT time\n          ,type\n          ,current\n          ,capacity\n      FROM metric \n     WHERE metric.entity_oid = entity.oid\n       AND metric.entity_hash = entity.hash \n       AND metric.type IN ('MEM', 'CPU')\n       AND metric.time between timestamptz $__timeFrom() and $__timeTo()  \n  ) as foo ON true \n  WHERE entity.type = 'PHYSICAL_MACHINE'\n    AND (timestamptz $__timeTo(), $__timeTo() ) OVERLAPS (first_seen, last_seen)\n    AND scope && ARRAY[ [[Cluster]] ] \n  GROUP BY 1"
    }
   ]
  }
 ]
}