{
 "title": "Monthly Overview and Cluster Summary",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "table",
   "description": "This panel presents statistics for the virtual enterprise as a whole. Values are provided showing month over month with growth.",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with this_month_vms as (\n  SELECT\n      DISTINCT oid\n  FROM entity e\n  INNER JOIN LATERAL (\n      SELECT true\n        FROM metric\n        WHERE\n        metric.entity_oid = e.oid\n        and metric.time between timestamptz $__timeTo() - interval '1 hour' and $__timeTo()\n        LIMIT 1\n  ) as foo ON true WHERE\n    (type = 'VIRTUAL_MACHINE') and\n    (environment = 'ON_PREM') and\n    (timestamptz $__timeTo() - interval '1 hour', $__timeTo()) OVERLAPS (first_seen, last_seen)),\n  last_month_vms as (\n  SELECT\n          distinct oid\n  FROM entity e\n  INNER JOIN LATERAL (\n      SELECT true\n        FROM metric\n        WHERE\n        metric.entity_oid = e.oid\n        and metric.time between timestamptz $__timeTo() - interval '1 month' - interval '1 hour'\n                            and timestamptz $__timeTo() - interval '1 month'\n        LIMIT 1\n  ) as foo on true WHERE\n    (type = 'VIRTUAL_MACHINE') and\n    (environment = 'ON_PREM') and\n    (timestamptz $__timeTo() - interval '1 month' - interval '1 hour',\n     timestamptz $__timeTo() - interval '1 month') OVERLAPS (first_seen, last_seen)),\n  this_month_pm_count as (\n  SELECT\n          count(distinct oid) as pmCount\n  FROM entity e\n  INNER JOIN LATERAL (\n      SELECT true\n        FROM metric\n        WHERE\n        metric.entity_oid = e.oid\n        and metric.time between timestamptz $__timeTo() - interval '1 hour' and $__timeTo()\n        LIMIT 1\n  ) as foo ON true WHERE\n    (type = 'PHYSICAL_MACHINE') and\n    (timestamptz $__timeTo() - interval '1 hour', $__timeTo()) OVERLAPS (first_seen, last_seen)),\n  last_month_pm_count as (\n  SELECT\n          count(distinct oid) as pmCount\n  FROM entity e\n  INNER JOIN LATERAL (\n      SELECT true\n        FROM metric\n        WHERE\n        metric.entity_oid = e.oid\n        and metric.time between timestamptz $__timeTo() - interval '1 month' - interval '1 hour'\n                            and timestamptz $__timeTo() - interval '1 month'\n        LIMIT 1\n  ) as foo on true WHERE\n    (type = 'PHYSICAL_MACHINE') and\n    (timestamptz $__timeTo() - interval '1 month' - interval '1 hour',\n     timestamptz $__timeTo() - interval '1 month') OVERLAPS (first_seen, last_seen))\n  select month as time, pmCount as \"Host Count\", vmCount as \"VM Count\", vmCount::float4/nullif(pmCount,0) as \"VMs Per Host\",\n  vmsAdded \"VMs Added This Month\", vmsRemoved \"VMs Removed This Month\"\n  from\n  (SELECT\n    timestamptz $__timeTo() as month,\n          (select pmCount from this_month_pm_count) as pmCount,\n          (select count(oid) from this_month_vms) as vmCount,\n          (select count(*)\n      from (\n      select oid from this_month_vms\n      except\n      select oid from last_month_vms\n      )  foo\n    ) as vmsAdded,\n    (select count(*)\n      from (\n      select oid from last_month_vms\n      except\n      select oid from this_month_vms\n      )  foo\n    ) as vmsRemoved\n\n  union\n  SELECT\n    timestamptz $__timeTo() - interval '1 month' as month,\n          (select pmCount from last_month_pm_count) as pmCount,\n          (select count(oid) from last_month_vms) as vmCount,\n          -1 as vmsAdded,\n          -1 as vmsRemoved\n  ) foo\n"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "WITH curStorage AS (\n  SELECT DISTINCT oid\n  FROM entity e\n  WHERE\n    type = 'STORAGE'\n    AND (timestamptz $__timeTo() - interval '1 hour', timestamptz $__timeTo())\n      OVERLAPS (first_seen, last_seen)\n),\n-- WITH...\ncurVMCount AS (\n  SELECT count(DISTINCT oid) AS vmCount\n  FROM entity e\n  INNER JOIN LATERAL (\n    SELECT true\n    FROM metric\n    WHERE\n      metric.entity_oid = e.oid\n      AND metric.time BETWEEN timestamptz $__timeTo() - interval '1 hour' AND timestamptz $__timeTo()\n    LIMIT 1\n  ) AS metric ON TRUE\n  WHERE\n    type = 'VIRTUAL_MACHINE'\n    AND environment = 'ON_PREM'\n    AND (timestamptz $__timeTo() - interval '1 hour', timestamptz $__timeTo())\n      OVERLAPS (first_seen, last_seen)\n),\n-- WITH...\ncurAmount AS (\n  SELECT\n    timestamptz $__timeTo() as time,\n    sum(metric.capacity) as total,\n    sum(metric.current) as used,\n    sum(metric.capacity) - sum(metric.current) as available,\n    avg(metric.utilization) as utilization\n  FROM curStorage as entity\n  INNER JOIN LATERAL (\n    SELECT metric.type, metric.current, metric.capacity, metric.utilization\n    FROM metric\n    WHERE metric.entity_oid = entity.oid\n      AND metric.type = 'STORAGE_AMOUNT'\n      AND metric.provider_oid IS NULL\n      AND metric.time BETWEEN timestamptz $__timeTo() - interval '1 hour' AND timestamptz $__timeTo()\n    LIMIT 1\n  ) as metric ON TRUE\n),\n-- WITH...\ncurAlloc AS (\n  SELECT sum(metric.current) AS allocated\n  FROM curStorage as entity\n  INNER JOIN LATERAL (\n    SELECT metric.type, metric.current, metric.capacity, metric.utilization\n    FROM metric\n    WHERE\n      metric.entity_oid = entity.oid\n      AND metric.type = 'STORAGE_PROVISIONED'\n      AND metric.provider_oid IS NULL\n      AND metric.time BETWEEN timestamptz $__timeTo() - interval '1 hour' AND timestamptz $__timeTo()\n    LIMIT 1\n  ) AS metric ON TRUE\n),\n-- WITH...\nmonthStorage AS (\n  SELECT DISTINCT oid\n  FROM entity e\n  WHERE\n    type = 'STORAGE'\n    AND (\n      timestamptz $__timeTo() - interval '1 hour' - interval '1 month',\n      timestamptz $__timeTo() - interval '1 month'\n    ) OVERLAPS (first_seen, last_seen)\n),\n-- WITH ...\nmonthVMCount AS (\n  SELECT count(DISTINCT oid) AS vmCount\n  FROM entity e\n  INNER JOIN LATERAL (\n    SELECT true\n    FROM metric\n    WHERE\n      metric.entity_oid = e.oid\n      AND metric.time BETWEEN timestamptz $__timeTo() - interval '1 hour' - interval '1 month'\n        AND timestamptz $__timeTo()  - interval '1 month'\n    LIMIT 1\n  ) AS metric ON TRUE\n  WHERE\n    type = 'VIRTUAL_MACHINE'\n    AND environment = 'ON_PREM'\n    AND (timestamptz $__timeTo() - interval '1 hour', timestamptz $__timeTo())\n      OVERLAPS (first_seen, last_seen)\n),\n-- WITH...\nmonthAmount AS (\n  SELECT\n    timestamptz $__timeTo() - interval '1 month' as time,\n    sum(metric.capacity) as total,\n    sum(metric.current) as used,\n    sum(metric.capacity) - sum(metric.current) as available,\n    avg(metric.utilization) as utilization\n  FROM curStorage as entity\n  INNER JOIN LATERAL (\n    SELECT metric.type, metric.current, metric.capacity, metric.utilization\n    FROM metric\n    WHERE\n      metric.entity_oid = entity.oid\n      AND metric.type = 'STORAGE_AMOUNT'\n      AND metric.provider_oid IS NULL\n      AND metric.time BETWEEN timestamptz $__timeTo() - interval '1 hour' - interval '1 month'\n        AND timestamptz $__timeTo() - interval '1 month'\n    LIMIT 1\n  ) as metric ON TRUE\n),\n-- WITH...\nmonthAlloc AS (\n  SELECT sum(metric.current) AS allocated\n  FROM curStorage AS entity\n  INNER JOIN LATERAL (\n    SELECT metric.type, metric.current, metric.capacity, metric.utilization\n    FROM metric\n    WHERE\n      metric.entity_oid = entity.oid\n      AND metric.type = 'STORAGE_PROVISIONED'\n      AND metric.provider_oid IS NULL\n      AND metric.time BETWEEN timestamptz $__timeTo() - interval '1 hour' - interval '1 month'\n        AND timestamptz $__timeTo() - interval '1 month'\n    LIMIT 1\n  ) as metric ON TRUE\n)\nSELECT\n  time AS \"Time\",\n  total AS \"Total\",\n  used AS \"Used\",\n  available AS \"Available\",\n  allocated AS \"Allocated\",\n  vmCount/Allocated*1e6 AS \"VMs per TB\",\n  allocated/vmCount AS \"Storage per VM\"\nFROM curAmount, curAlloc, curVMCount\nUNION SELECT\n  time as \"Time\",\n  total as \"Total\",\n  used as \"Used\",\n  available as \"Available\",\n  allocated as \"Allocated\",\n  vmCount/Allocated*1e6 as \"VMs per TB\",\n  allocated/vmCount \"Storage per VM\"\nFROM monthAmount, monthAlloc, monthVMCount\n"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "table",
   "description": "The following indicators compare cluster capacity vs consumption. Indicator colors show: green where consumption is below N-2 server total resources, orange for above N-2 but below N-1, and red where consumption is above N-1.",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with cluster as (\n  select oid pm_oid, scope.scoped_oid cluster_oid\n   from entity e\n   join scope on scope.seed_oid  = e.oid and scope.scoped_type='COMPUTE_CLUSTER'\n   where e.type ='PHYSICAL_MACHINE'\n   and (timestamptz $__timeTo() - interval '1 hour', timestamptz $__timeTo()) overlaps (start,   finish)\n),\n-- WITH...\ncluster_pm as (\n   select e.oid as clusterOid, e.name as clusterName, c.pm_oid as pmOid\n   from entity e\n   join cluster c on c.cluster_oid = e.oid)\nselect\n   clusterName as \"Cluster\",\n   (sum(mem.capacity) - sum(mem.current))/NULLIF(max(mem.capacity),0) as \"Mem\",\n   (sum(cpu.capacity) - sum(cpu.current))/NULLIF(max(cpu.capacity),0) as \"CPU\",\n  (sum(net.capacity) - sum(net.current))/NULLIF(max(net.capacity),0) as \"Network\"\n-- (sum(storage.capacity) - sum(storage.current))/max(storage.capacity) AS storageN,\n-- (sum(net.capacity) - sum(net.current))/max(net.capacity) AS storageN\nfrom cluster_pm\nLEFT JOIN LATERAL (\n     SELECT current, capacity\n     FROM metric\n     WHERE metric.entity_oid = cluster_pm.pmOid\n     and metric.type = 'MEM'\n     and metric.time between timestamptz $__timeTo() - interval '1 hour' and timestamptz $__timeTo()\n   LIMIT 1\n ) as mem ON TRUE\nLEFT OUTER JOIN LATERAL (\n   SELECT current, capacity\n     FROM metric\n     WHERE metric.entity_oid = cluster_pm.pmOid\n     and metric.type = 'CPU'\n     and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n     timestamptz $__timeTo()\n     LIMIT 1\n) as cpu ON TRUE\n-- LEFT OUTER JOIN LATERAL (\n  --   SELECT current, capacity\n  --   FROM metric\n  --   WHERE\n  --     metric.entity_oid = cluster_pm.pmOid\n  --     AND metric.type = 'STORAGE_AMOUNT'\n  --     AND metric.time BETWEEN timestamptz $__timeTo() - interval '1 hour' AND timestamptz $__timeTo()\n  --   LIMIT 1\n  -- ) AS storage ON TRUE\nLEFT OUTER JOIN LATERAL (\n     SELECT current, capacity\n      FROM metric\n      WHERE metric.entity_oid = cluster_pm.pmOid\n      and metric.type = 'NET_THROUGHPUT'\n      and metric.time between timestamptz $__timeTo() - interval '1 hour' and timestamptz $__timeTo()\n      LIMIT 1\n) as net ON TRUE\ngroup by cluster_pm.clusterOid, cluster_pm.clusterName\n"
    }
   ]
  }
 ]
}