{
 "title": "SLO Daily Violations Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metric_type",
    "label": "Metric Type",
    "query": "SELECT DISTINCT type FROM metric WHERE $__timeFilter(time) ORDER BY 1"
   },
   {
    "name": "desired_factor",
    "label": "Target Utilization",
    "query": "SELECT generate_series || '%' as __text, generate_series*.01 as __value FROM generate_series(10,100,10)"
   },
   { "name": "ma_days", "label": "Moving Avg Days", "query": "3,7,14,30" },
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Environment Out of Compliance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT day as time, error as \"Daily Error\" AVG(error) OVER ( ORDER BY day ROWS BETWEEN $ ma_days - 1 PRECEDING AND CURRENT ROW) as \"Moving Error\" FROM ( SELECT DATE_TRUNC('day', time) as day, SUM( CASE WHEN current - capacity* $ desired_factor > 0 THEN current - capacity* $ desired_factor ELSE 0 END ) as error FROM metric WHERE type = $ {metric_type:singlequote} AND time BETWEEN $ __timeFrom() AND $ __timeTo() GROUP BY 1) as data;"
    }
   ]
  },
  {
   "title": "Actions by State per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', time) as time, count(DISTINCT action_oid) FILTER ( where state = 'READY') as \"Generated\", count(DISTINCT action_oid) FILTER ( where state = 'SUCCEEDED') as \"Successful\" FROM ( SELECT time, action_oid, state FROM action JOIN action_spec on action_spec.spec_oid = action.action_spec_oid and action_spec.hash = action.action_spec_hash WHERE time BETWEEN $ __timeFrom() AND $ __timeTo() AND ( $ __timeFrom(), $ __timeTo() ) OVERLAPS (first_seen, last_seen) AND state in ( 'SUCCEEDED', 'READY' ) ) as data GROUP BY 1"
    }
   ]
  },
  {
   "title": "Successful Actions by Type per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', time) as time, count(DISTINCT action_oid) FILTER ( where type = 'MOVE') as \"MOVE\", count(DISTINCT action_oid) FILTER ( where type = 'PROVISION') as \"PROVISION\", count(DISTINCT action_oid) FILTER ( where type = 'RESIZE') as \"RESIZE\", count(DISTINCT action_oid) FILTER ( where type = 'DEACTIVATE') as \"DEACTIVATE\" FROM ( SELECT time, action_oid, type FROM action JOIN action_spec on action_spec.spec_oid = action.action_spec_oid and action_spec.hash = action.action_spec_hash WHERE time BETWEEN $ __timeFrom() AND $ __timeTo() AND ( $ __timeFrom(), $ __timeTo() ) OVERLAPS (first_seen, last_seen) AND state = 'SUCCEEDED') as data GROUP BY 1"
    }
   ]
  },
  {
   "title": "Pending Actions by Type per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', time) as time, count(DISTINCT action_oid) FILTER ( where type = 'MOVE') as \"MOVE\", count(DISTINCT action_oid) FILTER ( where type = 'PROVISION') as \"PROVISION\", count(DISTINCT action_oid) FILTER ( where type = 'RESIZE') as \"RESIZE\", count(DISTINCT action_oid) FILTER ( where type = 'DEACTIVATE') as \"DEACTIVATE\" FROM ( SELECT time, action_oid, type FROM action JOIN action_spec on action_spec.spec_oid = action.action_spec_oid and action_spec.hash = action.action_spec_hash WHERE time BETWEEN $ __timeFrom() AND $ __timeTo() AND ( $ __timeFrom(), $ __timeTo() ) OVERLAPS (first_seen, last_seen) AND state = 'READY') as data GROUP BY 1"
    }
   ]
  }
 ]
}