{
 "title": "SLO Hourly Violations Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metric_type",
    "label": "Metric Type",
    "query": "SELECT DISTINCT type FROM metric WHERE $__timeFilter(time) ORDER BY 1"
   },
   {
    "name": "desired_factor",
    "label": "Target Utilization",
    "query": "SELECT generate_series || '%' as __text, generate_series*.01 as __value FROM generate_series(10,100,10)"
   },
   { "name": "ma_hours", "label": "Moving Avg Hours", "query": "1,6,12,24,48" },
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Environment Out of Compliance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT hour as time\n      ,error as \"Hourly Error\"\n      ,AVG(error) OVER (ORDER BY hour ROWS BETWEEN $ma_hours - 1 PRECEDING AND CURRENT ROW) as \"Moving Error\"\n\nFROM\n     (SELECT DATE_TRUNC('hour', time) as hour\n            ,SUM(CASE WHEN current - capacity*$desired_factor > 0\n                      THEN current - capacity*$desired_factor\n                      ELSE 0\n                 END) as error\n        FROM metric\n       WHERE type = ${metric_type:singlequote}\n         AND time BETWEEN $__timeFrom() AND $__timeTo()\n       GROUP BY 1) as data;"
    }
   ]
  },
  {
   "title": "Actions by State per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('hour', time) as time,\n    count(DISTINCT action_oid) FILTER (\n where\n    state = 'READY') as \"Generated\",\n    count(DISTINCT action_oid) FILTER (\n where\n    state = 'SUCCEEDED') as \"Successful\" FROM (\n    SELECT\n       time, action_oid, state\n    FROM\n       action\n       JOIN\n          action_spec\n          on action_spec.spec_oid = action.action_spec_oid\n          and action_spec.hash = action.action_spec_hash\n    WHERE\n       time BETWEEN $__timeFrom() AND $__timeTo()\n       AND\n       (\n          $__timeFrom(),\n          $__timeTo()\n       )\n       OVERLAPS (first_seen, last_seen)\n       AND state in\n       (\n          'SUCCEEDED',\n          'READY'\n       )\n ) as data GROUP BY 1"
    }
   ]
  },
  {
   "title": "Successful Actions by Type per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('hour', time) as time,\n    count(DISTINCT action_oid) FILTER (\n where\n    type = 'MOVE') as \"MOVE\",\n    count(DISTINCT action_oid) FILTER (\n where\n    type = 'PROVISION') as \"PROVISION\",\n    count(DISTINCT action_oid) FILTER (\n where\n    type = 'RESIZE') as \"RESIZE\",\n    count(DISTINCT action_oid) FILTER (\n where\n    type = 'DEACTIVATE') as \"DEACTIVATE\" FROM (\n    SELECT\n       time, action_oid, type\n    FROM\n       action\n       JOIN\n          action_spec\n          on action_spec.spec_oid = action.action_spec_oid\n          and action_spec.hash = action.action_spec_hash\n    WHERE\n       time BETWEEN $__timeFrom() AND $__timeTo()\n       AND\n       (\n          $__timeFrom(),\n          $__timeTo()\n       )\n       OVERLAPS (first_seen, last_seen)\n       AND state = 'SUCCEEDED') as data GROUP BY 1"
    }
   ]
  },
  {
   "title": "Pending Actions by Type per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('hour', time) as time,\n    count(DISTINCT action_oid) FILTER (\n where\n    type = 'MOVE') as \"MOVE\",\n    count(DISTINCT action_oid) FILTER (\n where\n    type = 'PROVISION') as \"PROVISION\",\n    count(DISTINCT action_oid) FILTER (\n where\n    type = 'RESIZE') as \"RESIZE\",\n    count(DISTINCT action_oid) FILTER (\n where\n    type = 'DEACTIVATE') as \"DEACTIVATE\" FROM (\n    SELECT\n       time, action_oid, type\n    FROM\n       action\n       JOIN\n          action_spec\n          on action_spec.spec_oid = action.action_spec_oid\n          and action_spec.hash = action.action_spec_hash\n    WHERE\n       time BETWEEN $__timeFrom() AND $__timeTo()\n       AND\n       (\n          $__timeFrom(),\n          $__timeTo()\n       )\n       OVERLAPS (first_seen, last_seen)\n       AND state = 'READY') as data GROUP BY 1"
    }
   ]
  }
 ]
}