{
 "title": "Physical Machine Utilization Week Over Week by Day",
 "description": "Host Utilization by day comparing week over week in a two week span",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "SELECT name as __text,\n       oid as __value \nFROM entity \nWHERE entity.type = 'GROUP' \nAND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) \nAND attrs -> 'member_types' ? 'PHYSICAL_MACHINE'\nGROUP BY name, oid \nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Physical Machine Avg Memory Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average memory utilization for physical machines ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,avg(m.utilization) AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'MEM'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '7 day', $__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ $Group ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ $Group ]::bigint[]) END\n     GROUP BY 1\n)\n\nSELECT CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN date_trunc('day', time + interval '7 day') \n            ELSE date_trunc('day', time) \n       END + interval '1 DAY' as \"time\"\n      ,\n       CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN 'Previous Week'\n            ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n       END as metric\n      ,avg(avg_util)\n  FROM data\n GROUP BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg CPU Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average CPU utilization by physical machine ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,avg(m.utilization) AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'CPU'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '7 day',$__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ $Group ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ $Group ]::bigint[]) END\n     GROUP BY 1\n)\n\nSELECT CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN date_trunc('day', time + interval '7 day') \n            ELSE date_trunc('day', time) \n       END + interval '1 DAY' as \"time\"\n      ,\n       CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN 'Previous Week'\n            ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n       END as metric\n      ,avg(avg_util)\n  FROM data\n GROUP BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Ballooning Utilization - Week over Week by Day ",
   "type": "graph",
   "description": "Average Ballooning utilization by physical machines  ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,avg(m.utilization) AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'BALLOONING'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '7 day',$__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ $Group ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ $Group ]::bigint[]) END\n     GROUP BY 1\n)\n\nSELECT CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN date_trunc('day', time + interval '7 day') \n            ELSE date_trunc('day', time) \n       END + interval '1 DAY' as \"time\"\n      ,\n       CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN 'Previous Week'\n            ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n       END as metric\n      ,avg(avg_util)\n  FROM data\n GROUP BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Swapping Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average Swapping utilization by physical machines ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,avg(m.utilization) AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'SWAPPING'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '7 day',$__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ $Group ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ $Group ]::bigint[]) END\n     GROUP BY 1\n)\n\nSELECT CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN date_trunc('day', time + interval '7 day') \n            ELSE date_trunc('day', time) \n       END + interval '1 DAY' as \"time\"\n      ,\n       CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN 'Previous Week'\n            ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n       END as metric\n      ,avg(avg_util)\n  FROM data\n GROUP BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg IO Throughput Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average IO Throughput utilization by physical machine ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,avg(m.utilization) AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'IO_THROUGHPUT'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '7 day',$__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ $Group ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ $Group ]::bigint[]) END\n     GROUP BY 1\n)\n\nSELECT CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN date_trunc('day', time + interval '7 day') \n            ELSE date_trunc('day', time) \n       END + interval '1 DAY' as \"time\"\n      ,\n       CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN 'Previous Week'\n            ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n       END as metric\n      ,avg(avg_util)\n  FROM data\n GROUP BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Net Throughput Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average Net Throughput utilization by physical machines ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,avg(m.utilization) AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'NET_THROUGHPUT'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '7 day',$__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ $Group ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ $Group ]::bigint[]) END\n     GROUP BY 1\n)\n\nSELECT CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN date_trunc('day', time + interval '7 day') \n            ELSE date_trunc('day', time) \n       END + interval '1 DAY' as \"time\"\n      ,\n       CASE \n            WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day') THEN 'Previous Week'\n            ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n       END as metric\n      ,avg(avg_util)\n  FROM data\n GROUP BY 1, 2"
    }
   ]
  }
 ]
}