{
 "title": "VM Over or Under Provisioning",
 "description": "This report shows Virtual Machines that are over or under provisioned, as indicated by their utilization levels of allocated resources.",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Over-provisioned VMs",
   "type": "table-old",
   "description": "Active VMs with CPU or Memory utilization peaks that are below 10%. Values indicating over- provisioning are highlighted with red text. ",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with vms_by_cluster as (\n    select distinct on (e.oid) g.name as cluster_name, e.oid as vm_oid, e.name as vm_name\n\tfrom entity g\n\tjoin entity e on g.\"type\" = 'COMPUTE_HOST_CLUSTER' and\n\t     array[g.oid] <@ e.scope\n\t     and e.\"type\" = 'VIRTUAL_MACHINE' and e.state = 'POWERED_ON'\n\t     and (e.first_seen, e.last_seen) overlaps ($__timeFrom(),$__timeTo()))\nselect max(cluster_name) as \"Cluster name\",\n       max(vm_name) as \"VM name\",\n       AVG(metric.capacity) filter (where metric.type = 'VMEM') as \"VMEM Capacity\",\n       AVG(metric.utilization) filter (where metric.type = 'VMEM') as \"VMEM Avg\",\n       max(metric.utilization) filter (where metric.type = 'VMEM') as \"VMEM Peak\",\n       AVG(metric.capacity) filter (where metric.type = 'VCPU') as \"VCPU Capacity\",\n       AVG(metric.utilization) filter (where metric.type = 'VCPU') as \"VCPU Avg\",\n       max(metric.utilization) filter (where metric.type = 'VCPU') as \"VCPU Peak\"\nfrom vms_by_cluster\njoin metric on\n       metric.entity_oid = vm_oid and \n       metric.\"type\" in ('VMEM', 'VCPU') and provider_oid isnull and $__timeFilter(metric.\"time\")\ngroup by vm_oid\nhaving max(metric.utilization) filter (where metric.type = 'VMEM') < 0.1 OR\n       max(metric.utilization) filter (where metric.type = 'VCPU') < 0.1\n"
    }
   ]
  },
  {
   "title": "Under-provisioned VMs",
   "type": "table-old",
   "description": "Active VMs with CPU or Memory utilization averages that are above 85%. Values indicating under-provisioning are highlighted in red text.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "with vms_by_cluster as (\n    select distinct on (e.oid) g.name as cluster_name, e.oid as vm_oid, e.name as vm_name\n\tfrom entity g\n\tjoin entity e on g.\"type\" = 'COMPUTE_HOST_CLUSTER' and\n\t     array[g.oid] <@ e.scope\n\t     and e.\"type\" = 'VIRTUAL_MACHINE' and e.state = 'POWERED_ON'\n\t     and (e.first_seen, e.last_seen) overlaps ($__timeFrom(),$__timeTo()))\nselect max(cluster_name) as \"Cluster name\",\n       max(vm_name) as \"VM name\",\n       AVG(metric.capacity) filter (where metric.type = 'VMEM') as \"VMEM Capacity\",\n       AVG(metric.utilization) filter (where metric.type = 'VMEM') as \"VMEM Avg\",\n       max(metric.utilization) filter (where metric.type = 'VMEM') as \"VMEM Peak\",\n       AVG(metric.capacity) filter (where metric.type = 'VCPU') as \"VCPU Capacity\",\n       AVG(metric.utilization) filter (where metric.type = 'VCPU') as \"VCPU Avg\",\n       max(metric.utilization) filter (where metric.type = 'VCPU') as \"VCPU Peak\"\nfrom vms_by_cluster\njoin metric on\n       metric.entity_oid = vm_oid and \n       metric.\"type\" in ('VMEM', 'VCPU') and provider_oid isnull and $__timeFilter(metric.\"time\")\ngroup by vm_oid\nhaving max(metric.utilization) filter (where metric.type = 'VMEM') > 0.85 OR\n       max(metric.utilization) filter (where metric.type = 'VCPU') > 0.85\n"
    }
   ]
  },
  {
   "title": "Clusters with Average Peaks",
   "type": "table-old",
   "description": "Group/Cluster information allowing individual VM peaks to be compared with the average of all of the peaks of the VMs in their corresponding cluster.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "with vms_by_cluster as (\n  select distinct on(e.oid) g.name as cluster_name, e.oid as vm_oid\n\tfrom entity g\n\tjoin entity e on g.\"type\" = 'COMPUTE_HOST_CLUSTER' and array[g.oid] <@ e.scope and e.\"type\" = 'VIRTUAL_MACHINE'\n\t  \t\t\t\tand e.\"type\" = 'VIRTUAL_MACHINE' and e.state = 'POWERED_ON'\n\t  \t\t\t\tand (e.first_seen, e.last_seen) overlaps ($__timeFrom(),$__timeTo())),\nvm_peaks as (\n    SELECT MAX(cluster_name) as cluster_name,\n\t       MAX(metric.utilization) filter (where metric.type = 'VMEM') as vmem_peak,\n\t       MAX(metric.utilization) filter (where metric.type = 'VCPU') as vcpu_peak\n\tFROM vms_by_cluster\n\tjoin metric on vm_oid = metric.entity_oid \n\t      and $__timeFilter(metric.\"time\")\n\t      and metric.\"type\" in ('VMEM', 'VCPU')\n\t      and provider_oid isnull\n\tgroup by vm_oid)\nselect cluster_name as \"Cluster\", avg(vcpu_peak) as \"Avg(Peak VCPU)\", avg(vmem_peak) as \"Avg(Peak VMem)\"\nfrom vm_peaks\ngroup by cluster_name\n\n"
    }
   ]
  }
 ]
}