{
 "title": "Virtual Machine Over or Under Provisioning",
 "description": "This dashboard shows virtual machines that are over or under provisioned, as indicated by their utilization levels of allocated resources.",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Over-provisioned VMs",
   "type": "table-old",
   "description": "Active VMs with CPU or Memory utilization peaks that are below 10%. Values indicating over- provisioning are highlighted with red text.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH vms_by_cluster AS (\n  SELECT DISTINCT ON (e.oid)\n   c.name AS cluster_name,\n   e.oid AS vm_oid,\n   e.name AS vm_name\n  FROM entity c,\n    entity e,\n    scope s\n  WHERE e.type = 'VIRTUAL_MACHINE'\n    AND c.type = 'COMPUTE_CLUSTER'\n    AND s.seed_oid = c.oid\n    AND s.scoped_oid = e.oid\n    AND (s.start, s.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n  ORDER BY e.oid, s.finish, s.start\n)\nSELECT\n  max(cluster_name) AS \"Cluster name\",\n  max(vm_name) AS \"VM name\",\n  avg(metric.capacity) FILTER (WHERE metric.type = 'VMEM') AS \"VMEM Capacity\",\n  avg(metric.utilization) FILTER (WHERE metric.type = 'VMEM') AS \"VMEM Avg\",\n  max(metric.utilization) FILTER (WHERE metric.type = 'VMEM') AS \"VMEM Peak\",\n  avg(metric.capacity * 1000000) FILTER (WHERE metric.type = 'VCPU') AS \"VCPU Capacity\",\n  avg(metric.utilization) FILTER (WHERE metric.type = 'VCPU') AS \"VCPU Avg\",\n  max(metric.utilization) FILTER (WHERE metric.type = 'VCPU') AS \"VCPU Peak\"\nFROM vms_by_cluster\nJOIN metric ON\n  metric.entity_oid = vm_oid\n  AND metric.\"type\" IN ('VMEM', 'VCPU')\n  AND provider_oid ISNULL\n  AND $__timeFilter(metric.\"time\")\nGROUP BY vm_oid\nHAVING\n  max(metric.utilization) FILTER (WHERE metric.type = 'VMEM') < 0.1 -- \"VMEM Peak\"\n  OR max(metric.utilization) FILTER (WHERE metric.type = 'VCPU') < 0.1 -- \"VCPU Peak\"\n"
    }
   ]
  },
  {
   "title": "Under-provisioned VMs",
   "type": "table-old",
   "description": "Active VMs with CPU or Memory utilization averages that are above 85%. Values indicating under-provisioning are highlighted in red text.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "WITH vms_by_cluster AS (\n  SELECT DISTINCT ON (e.oid)\n   c.name AS cluster_name,\n   e.oid AS vm_oid,\n   e.name AS vm_name\n  FROM entity c,\n    entity e,\n    scope s\n  WHERE e.type = 'VIRTUAL_MACHINE'\n    AND c.type = 'COMPUTE_CLUSTER'\n    AND s.seed_oid = c.oid\n    AND s.scoped_oid = e.oid\n    AND (s.start, s.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n  ORDER BY e.oid, s.finish, s.start\n)\nSELECT\n  max(cluster_name) AS \"Cluster name\",\n  max(vm_name) AS \"VM name\",\n  avg(metric.capacity) FILTER (WHERE metric.type = 'VMEM') AS \"VMEM Capacity\",\n  avg(metric.utilization) FILTER (WHERE metric.type = 'VMEM') AS \"VMEM Avg\",\n  max(metric.utilization) FILTER (WHERE metric.type = 'VMEM') AS \"VMEM Peak\",\n  avg(metric.capacity * 1000000) FILTER (WHERE metric.type = 'VCPU') AS \"VCPU Capacity\",\n  avg(metric.utilization) FILTER (WHERE metric.type = 'VCPU') AS \"VCPU Avg\",\n  max(metric.utilization) FILTER (WHERE metric.type = 'VCPU') AS \"VCPU Peak\"\nFROM vms_by_cluster\nJOIN metric ON\n  metric.entity_oid = vm_oid\n  AND metric.\"type\" IN ('VMEM', 'VCPU')\n  AND provider_oid IS NULL\n  AND $__timeFilter(metric.\"time\")\nGROUP BY vm_oid\nHAVING max(metric.utilization) FILTER (WHERE metric.type = 'VMEM') > 0.85\n  OR max(metric.utilization) FILTER (WHERE metric.type = 'VCPU') > 0.85;\n"
    }
   ]
  },
  {
   "title": "Clusters with Average Peaks",
   "type": "table-old",
   "description": "Group/Cluster information allowing individual VM peaks to be compared with the average of all of the peaks of the VMs in their corresponding cluster.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "WITH vms_by_cluster AS (\n  SELECT DISTINCT ON (e.oid)\n   c.name AS cluster_name,\n   e.oid AS vm_oid,\n   e.name AS vm_name\n  FROM entity c,\n    entity e,\n    scope s\n  WHERE e.type = 'VIRTUAL_MACHINE'\n    AND c.type = 'COMPUTE_CLUSTER'\n    AND s.seed_oid = c.oid\n    AND s.scoped_oid = e.oid\n    AND (s.start, s.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n  ORDER BY e.oid, s.finish, s.start\n),\nvm_peaks AS (\n  SELECT\n    max(cluster_name) AS cluster_name,\n    max(metric.utilization) FILTER (WHERE metric.type = 'VMEM') AS vmem_peak,\n    max(metric.utilization) FILTER (WHERE metric.type = 'VCPU') AS vcpu_peak\n  FROM vms_by_cluster\n  JOIN metric ON metric.entity_oid = vm_oid\n  WHERE\n    $__timeFilter(metric.\"time\")\n    AND metric.type IN ('VMEM', 'VCPU')\n    AND provider_oid IS NULL\n  GROUP BY vm_oid\n)\nSELECT\n  cluster_name AS \"Cluster\",\n  avg(vcpu_peak) AS \"Avg(Peak VCPU)\",\n  avg(vmem_peak) AS \"Avg(Peak VMem)\"\nFROM vm_peaks\nGROUP BY cluster_name\n"
    }
   ]
  }
 ]
}