{
 "title": "CPU Ready",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Cluster",
    "query": "select name as __text, oid as __value from entity where entity.type = 'COMPUTE_HOST_CLUSTER'  and ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) group by name, oid order by 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Physical Machine CPU Ready Percentage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  metric.type || ' ' || entity.name AS metric,\n  avg(metric.utilization) AS \"value\"\nFROM metric, entity\nWHERE\n  $__timeFilter(\"time\") AND\n  metric.type LIKE 'Q%_VCPU' AND\n  metric.entity_oid = entity.oid AND\n  metric.entity_hash = entity.hash AND\n  entity.type = 'PHYSICAL_MACHINE' AND\n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  CASE WHEN  ARRAY[ [[Cluster]] ] = ARRAY[ '0' ] THEN true ELSE (entity.scope && ARRAY[ [[Cluster]] ]::bigint[]) END\nGroup by metric\nORDER BY 2 desc, 1 "
    }
   ]
  },
  {
   "title": "VMs by CPU Ready Pct",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  entity.name as \"VM Name\",\n  avg(metric.consumed/200) as \"Avg CPU Wait Pct\"\nFROM metric, entity\nWHERE\n  $__timeFilter(\"time\") AND entity.oid = metric.entity_oid AND entity.hash = metric.entity_hash AND entity.type = 'VIRTUAL_MACHINE' AND \n  metric.type LIKE 'Q%_VCPU' AND\n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  CASE WHEN ARRAY[ [[Cluster]] ] = ARRAY[ '0' ] THEN true ELSE (entity.scope && ARRAY[ [[Cluster]] ]::bigint[]) END\nGROUP BY entity.oid, entity.name \nORDER BY 2 desc  "
    }
   ]
  },
  {
   "title": "Top Physical Machines by CPU Ready Pct",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  entity.name as \"Host\", \n  metric.type \"Queue Type\",\n  avg(metric.utilization) AS \"Avg CPU Ready Pct\",\n  max(metric.utilization) AS \"Max CPU Ready Pct\"\nFROM metric, entity\nWHERE\n  $__timeFilter(\"time\") AND\n  metric.type LIKE 'Q%_VCPU' AND\n  metric.entity_oid = entity.oid AND\n  metric.entity_hash = entity.hash AND\n  entity.type = 'PHYSICAL_MACHINE' AND \n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  CASE WHEN ARRAY[ [[Cluster]] ] = ARRAY[ '0' ] THEN true ELSE (entity.scope && ARRAY[ [[Cluster]] ]::bigint[]) END\nGroup by 2, 1\nORDER BY 2 asc, 4 desc"
    }
   ]
  },
  {
   "title": "VM CPU Ready",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  entity.oid as \"VM OID\",\n  entity.name as \"VM Name\",\n  max(entity.attrs->>'num_cpus') as \"Num vCPUs\",\n  avg(metric.consumed/200) as \"Avg CPU Wait Pct\",\n  max(metric.consumed/200) as \"Max CPU Wait Pct\"\nFROM metric, entity\nWHERE\n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  $__timeFilter(\"time\") AND entity.oid = metric.entity_oid AND entity.hash = metric.entity_hash and \n  entity.type = 'VIRTUAL_MACHINE' AND \n  metric.type LIKE 'Q%_VCPU' \n  AND CASE WHEN ARRAY[ [[Cluster]] ] = ARRAY[ '0' ] THEN true ELSE (entity.scope && ARRAY[ [[Cluster]] ]::bigint[]) END\nGROUP BY entity.oid, entity.name\nORDER BY 3"
    }
   ]
  }
 ]
}