{
 "title": "Datastore Group Summary",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "SELECT name as __text, \n       oid as __value \nFROM entity \nWHERE ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) \nAND $__timeTo() >= first_seen \nAND type = 'STORAGE_CLUSTER'\nOR (type = 'REGULAR' \n   AND attrs #>> '{expectedTypes, 0}' = 'STORAGE')"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Consumption",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT sum(used) as \"Storage Used\"\n      ,sum(capacity) as \"Storage Capacity\"\n      ,round((sum(used)/sum(capacity))::numeric, 4) as \"Utilization\"\nFROM\n        (SELECT e.oid\n              ,avg(m.current) AS used\n              ,avg(m.capacity) AS capacity\n        FROM entity e\n        JOIN metric m ON m.entity_oid = e.oid\n          AND m.type = 'STORAGE_AMOUNT'\n          AND m.entity_hash = e.hash\n          AND e.type = 'STORAGE'\n          AND $__timeFilter(m.\"time\")\n          --AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n          AND CASE WHEN ARRAY[ [[Group]] ]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n        GROUP BY 1) as data_tbl"
    }
   ]
  },
  {
   "title": "Performance Stats",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN type = 'STORAGE_ACCESS' THEN 'IOPS'\n            WHEN type = 'STORAGE_LATENCY' THEN 'Latency' END as \"Resource Type\"\n      ,sum(used_avg) as \"Avg\"\n      ,sum(used_min) as \"Min\"\n      ,sum(used_max) as \"Max\"\n      ,CASE WHEN type = 'STORAGE_ACCESS' THEN 'IOPS'\n            WHEN type = 'STORAGE_LATENCY' THEN 'ms' END as \"Unit\"\nFROM\n        (SELECT m.type\n              ,avg(m.current) AS used_avg\n              ,min(m.current) AS used_min\n              ,max(m.current) AS used_max\n        FROM entity e\n        JOIN metric m ON m.entity_oid = e.oid\n          AND m.type IN ('STORAGE_ACCESS', 'STORAGE_LATENCY')\n          AND m.entity_hash = e.hash\n          AND e.type = 'STORAGE'\n          AND $__timeFilter(m.\"time\")\n          --AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n          AND CASE WHEN ARRAY[ [[Group]] ]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n        GROUP BY 1) as data_tbl\nGROUP BY 1, 5;"
    }
   ]
  },
  {
   "title": "Consumption Trend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      date_trunc('hour', m.time) as \"time\",\n      ROUND((sum(m.current)/sum(m.capacity))::NUMERIC, 4) AS \"Storage Amount Used\"\nFROM entity e\nJOIN metric m ON m.entity_oid = e.oid\n  AND m.type = 'STORAGE_AMOUNT'\n  AND m.entity_hash = e.hash\n  AND e.type = 'STORAGE'\n  AND $__timeFilter(m.\"time\")\n  --AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND CASE WHEN ARRAY[ [[Group]] ]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Performance Trends",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT m.time\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_ACCESS') AS \"IOPS Avg\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_LATENCY') AS \"Latency Avg\"\nFROM entity e\nJOIN metric m ON m.entity_oid = e.oid\n  AND m.type IN ('STORAGE_ACCESS', 'STORAGE_LATENCY')\n  AND m.entity_hash = e.hash\n  AND e.type = 'STORAGE'\n  AND $__timeFilter(m.\"time\")\n  --AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND CASE WHEN ARRAY[ [[Group]] ]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Consumption Stats By Datastore",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT e.name as \"Datastore\"\n      ,avg(m.capacity) FILTER (WHERE m.type = 'STORAGE_AMOUNT') AS \"Storage Capacity\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_AMOUNT') AS \"Storage Used\"\n      ,avg(m.current / m.capacity) FILTER (WHERE m.type = 'STORAGE_AMOUNT') as \"Storage Utilization\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_PROVISIONED') as \"Storage Provisioned\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_PROVISIONED') / \n            avg(m.capacity) FILTER (WHERE m.type = 'STORAGE_AMOUNT') as \"Storage Over-Provisioned\"\nFROM entity e\nJOIN metric m ON m.entity_oid = e.oid\n  AND m.type IN ('STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n  AND m.entity_hash = e.hash\n  AND e.type = 'STORAGE'\n  AND $__timeFilter(m.\"time\")\n  --AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND CASE WHEN ARRAY[ [[Group]] ]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\nGROUP BY 1\nORDER BY 4 DESC"
    }
   ]
  },
  {
   "title": "Performance Stats By Datastore",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "rawSql": "SELECT e.name as \"Datastore\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_ACCESS') AS \"IOPS Avg\"\n      ,max(m.current) FILTER (WHERE m.type = 'STORAGE_ACCESS') AS \"IOPS Max\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_LATENCY') AS \"Latency Avg\"\n      ,max(m.current) FILTER (WHERE m.type = 'STORAGE_LATENCY') AS \"Latency Max\"\nFROM entity e\nJOIN metric m ON m.entity_oid = e.oid\n  AND m.type IN ('STORAGE_ACCESS', 'STORAGE_LATENCY')\n  AND m.entity_hash = e.hash\n  AND e.type = 'STORAGE'\n  AND $__timeFilter(m.\"time\")\n  --AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND CASE WHEN ARRAY[ [[Group]] ]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  }
 ]
}