{
 "title": "Datastore Summary",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Datastore",
    "query": "select name as __text, oid as __value from entity where ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) and entity.type = 'STORAGE' group by name, oid order by 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \nmax(metric.capacity) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS \"Capacity\",\navg(metric.current) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') AS \"Provisioned Used\",\navg(metric.current) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS \"Used\",\navg(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS') AS \"IOPS\",\navg(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY') AS \"Latency\"\nFROM metric, entity\nWHERE   \n  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n  entity.type = 'STORAGE' and \n  CASE WHEN ARRAY[ [[Datastore]] ] = ARRAY[ '0' ] THEN true ELSE (entity.oid = any (array[ [[Datastore]] ]::bigint[])) END and \n  entity.oid = metric.entity_oid and\n  $__timeFilter(\"time\")\n"
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \nunnest(array['1','2','3']) as \"order\",\nunnest(array['AVG','MIN','MAX']) as \"Aggregation\",\nunnest(array[avg(metric.utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'),\nmin(metric.utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'),\nmax(metric.Utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT')\n]) AS \"Utilization\",\nunnest(array[avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS'),\nmin(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS'),\nmax(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS')\n]) AS \"IOPS\",\nunnest(array[avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY'),\nmin(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY'),\nmax(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY')\n]) AS \"Latency\"\nFROM metric, entity\nWHERE entity.type = 'STORAGE' and \nCASE WHEN ARRAY[ [[Datastore]] ] = ARRAY[ '0' ] THEN true ELSE (entity.oid = any (array[ [[Datastore]] ]::bigint[])) END and \nentity.oid = metric.entity_oid and entity.hash = metric.entity_hash and\n  $__timeFilter(\"time\") and ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\nORDER BY \"order\" asc\n\n\n"
    }
   ]
  },
  {
   "title": "VM Summary",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\nmax(sub.name) as \"VM Name\",\nmax(sub.value) FILTER (WHERE sub.type = 'STORAGE_AMOUNT') AS \"Storage Used\",\navg(sub.value) FILTER (WHERE sub.type = 'STORAGE_ACCESS') AS \"Avg IOPS\",\nmax(sub.value) FILTER (WHERE sub.type = 'STORAGE_ACCESS') AS \"Max IOPS\",\navg(sub.value) FILTER (WHERE sub.type = 'STORAGE_LATENCY') AS \"Avg Latency\",\nmax(sub.value) FILTER (WHERE sub.type = 'STORAGE_LATENCY') AS \"Max Latency\"\nFROM (\nselect entity.oid as oid, entity.name as name, metric.type as type, metric.consumed as value \nfrom metric, entity\nWHERE entity.type = 'VIRTUAL_MACHINE' and (entity.scope && (array[ [[Datastore]] ]::bigint[])) \nand entity.oid = metric.entity_oid and entity.hash = metric.entity_hash and (metric.type = 'STORAGE_LATENCY' or metric.type = 'STORAGE_ACCESS') \nand $__timeFilter(\"time\") and ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\nunion\nselect entity.oid as oid, max(entity.name) as name, max(metric.type) as type, sum(metric.consumed) as value \nfrom metric, entity\nWHERE entity.type = 'VIRTUAL_MACHINE' and \nCASE WHEN ARRAY[ [[Datastore]] ] = ARRAY[ '0' ] THEN true ELSE (entity.scope && (array[ [[Datastore]] ]::bigint[])) END\nand entity.oid = metric.entity_oid and entity.hash = metric.entity_hash and metric.type = 'STORAGE_AMOUNT'\nand $__timeFilter(\"time\") and  ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\nGROUP BY time, entity.oid\n) sub\ngroup by sub.oid\n"
    }
   ]
  }
 ]
}