{
 "title": "Host/VM 30 Day Stats vs Thresholds",
 "description": "This report shows daily average utilization measurements for the past 30 days. Averages are grouped into two sections. One rolled up for physical machines and another rolled up for virtual machines. Note that all physical and virtual machines are included. This information is useful as a top-level assessment of the overall average loading of your entire environment over time.",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Physical Infrastructure Utilization Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select DATE(metric.\"time\") as \"time\", metric.\"type\", avg(utilization)\nfrom metric, entity\nwhere metric.entity_oid = entity.oid and\n      metric.entity_hash = entity.hash and \n      entity.\"type\" = 'PHYSICAL_MACHINE' and \n      provider_oid isnull and \n      $__timeFilter(\"time\") and\n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Virtual Infrastructure Utilization Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select DATE(metric.\"time\") as \"time\", metric.\"type\", avg(utilization)\nfrom metric, entity\nwhere metric.entity_oid = entity.oid and\n      metric.entity_hash = entity.hash and \n      entity.\"type\" = 'VIRTUAL_MACHINE' and \n      provider_oid isnull and \n      $__timeFilter(\"time\") and \n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Physical Machine Summary",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Virtual Machine Summary",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 21 },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Threshold Definitions",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT  *\nFROM    (\n        VALUES\n        (.2, .6, .3, .1, .2, .2, .03, .2, .6),\n        (.4, .8, .6, .25, .4, .4, .1, .4, .8)\n        ) AS q (\"CPU\", \"Mem\", \"Ballooning\", \"Swapping\", \"IO Throughput\", \"Net Throughput\", \"CPU Ready Q\", \"VCPU\", \"VMem\")"
    }
   ]
  }
 ]
}