{
 "title": "Monthly Overview and Cluster Summary",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "table-old",
   "description": "Test description",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with this_month_vms as (\nSELECT\n\tdistinct oid\nFROM entity\nINNER JOIN LATERAL (\n    SELECT true \n      FROM metric \n      WHERE metric.entity_oid = entity.oid\n      and metric.entity_hash = entity.hash \n      and metric.time between timestamptz $__timeTo() - interval '1 hour' and $__timeTo() \n      LIMIT 1\n) as foo ON true WHERE \n  (type = 'VIRTUAL_MACHINE') and\n  (timestamptz $__timeTo() - interval '1 hour', $__timeTo()) OVERLAPS (first_seen, last_seen)),\nlast_month_vms as (\nSELECT\n\tdistinct oid\nFROM entity\nINNER JOIN LATERAL (\n    SELECT true \n      FROM metric \n      WHERE metric.entity_oid = entity.oid\n      and metric.entity_hash = entity.hash \n      and metric.time between timestamptz $__timeTo() - interval '1 month' - interval '1 hour' \n                          and timestamptz $__timeTo() - interval '1 month'  \n      LIMIT 1\n) as foo on true WHERE \n  (type = 'VIRTUAL_MACHINE') and\n  (timestamptz $__timeTo() - interval '1 month' - interval '1 hour', \n   timestamptz $__timeTo() - interval '1 month') OVERLAPS (first_seen, last_seen)),\nthis_month_pm_count as (\nSELECT\n\tcount(distinct oid) as pmCount\nFROM entity\nINNER JOIN LATERAL (\n    SELECT true \n      FROM metric \n      WHERE metric.entity_oid = entity.oid\n      and metric.entity_hash = entity.hash \n      and metric.time between timestamptz $__timeTo() - interval '1 hour' and $__timeTo() \n      LIMIT 1\n) as foo ON true WHERE \n  (type = 'PHYSICAL_MACHINE') and\n  (timestamptz $__timeTo() - interval '1 hour', $__timeTo()) OVERLAPS (first_seen, last_seen)),\nlast_month_pm_count as (\nSELECT\n\tcount(distinct oid) as pmCount\nFROM entity\nINNER JOIN LATERAL (\n    SELECT true \n      FROM metric \n      WHERE metric.entity_oid = entity.oid\n      and metric.entity_hash = entity.hash \n      and metric.time between timestamptz $__timeTo() - interval '1 month' - interval '1 hour' \n                          and timestamptz $__timeTo() - interval '1 month'  \n      LIMIT 1\n) as foo on true WHERE \n  (type = 'PHYSICAL_MACHINE') and\n  (timestamptz $__timeTo() - interval '1 month' - interval '1 hour', \n   timestamptz $__timeTo() - interval '1 month') OVERLAPS (first_seen, last_seen))\nselect month as time, pmCount as \"Host Count\", vmCount as \"VM Count\", case when pmCount = 0 then -1 else vmCount::float4/pmCount end as \"VMs Per Host\", \nvmsAdded \"VMs Added This Month\", vmsRemoved \"VMs Removed This Month\"\nfrom \n(SELECT\n  timestamptz $__timeTo() as month,\n\t(select pmCount from this_month_pm_count) as pmCount,\n\t(select count(oid) from this_month_vms) as vmCount,\n\t(select count(*)\n    from (\n    select oid from this_month_vms\n    except \n    select oid from last_month_vms\n    )  foo \n  ) as vmsAdded,\n  (select count(*)\n    from (\n    select oid from last_month_vms\n    except \n    select oid from this_month_vms\n    )  foo \n  ) as vmsRemoved\n\nunion\nSELECT\n  timestamptz $__timeTo() - interval '1 month' as month,\n\t(select pmCount from last_month_pm_count) as pmCount,\n\t(select count(oid) from last_month_vms) as vmCount,\n\t-1 as vmsAdded,\n\t-1 as vmsRemoved\n) foo\n"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "with\ncurStorage as (select distinct oid\n       \t  \t  from entity\n\t\t  where (type = 'STORAGE') and\n\t\t  (timestamptz $__timeTo() - interval '1 hour',\n\t\t   timestamptz $__timeTo()) OVERLAPS (first_seen, last_seen)),\n\ncurVMCount as (select count(distinct oid) vmCount\n       \t  \t  from entity\n\t\t  INNER JOIN LATERAL (\n\t\t  \tSELECT true\n\t\t\tFROM metric \n\t      \t\tWHERE metric.entity_oid = entity.oid\n\t\t\tand metric.time between timestamptz $__timeTo() - interval '1 hour' and\n\t\t\ttimestamptz $__timeTo()\n\t    LIMIT 1\n\t      \t  ) as metric ON TRUE\n\t\t  where (type = 'VIRTUAL_MACHINE') and\n\t\t  (timestamptz $__timeTo() - interval '1 hour',\n\t\t   timestamptz $__timeTo()) OVERLAPS (first_seen, last_seen)),\n\ncurAmount as (select\n\t  timestamptz $__timeTo() as time,\n\t  sum(metric.capacity) as total,\n\t  sum(metric.current) as used,\n\t  sum(metric.capacity) - sum(metric.current) as available,\n\t  avg(metric.utilization) as utilization\n\t  FROM curStorage as entity\n\t  INNER JOIN LATERAL (\n\t      SELECT metric.type, metric.current, metric.capacity, metric.utilization\n\t      FROM metric \n\t      WHERE metric.entity_oid = entity.oid\n\t      \t    and metric.type = 'STORAGE_AMOUNT'\n      \t    \t    and metric.provider_oid IS NULL\n\t\t    and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n\t\t\ttimestamptz $__timeTo()\n\t      LIMIT 1\n\t      ) as metric ON TRUE),\n\ncurAlloc as (select\n\t  sum(metric.current) as allocated\n\t  FROM curStorage as entity\n\t  INNER JOIN LATERAL (\n\t      SELECT metric.type, metric.current, metric.capacity, metric.utilization\n\t      FROM metric \n\t      WHERE metric.entity_oid = entity.oid\n\t      \t    and metric.type = 'STORAGE_PROVISIONED'\n      \t    \t    and metric.provider_oid IS NULL\n\t\t    and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n\t\t\ttimestamptz $__timeTo()\n\t      LIMIT 1\n\t      ) as metric ON TRUE),\n\nmonthStorage as (select distinct oid\n       \t  \t  from entity\n\t\t  where (type = 'STORAGE') and\n\t\t  (timestamptz $__timeTo() - interval '1 hour' - interval '1 month',\n\t\t   timestamptz $__timeTo() - interval '1 month') OVERLAPS (first_seen, last_seen)),\n\nmonthVMCount as (select count(distinct oid) vmCount\n       \t  \t  from entity\n\t\t  INNER JOIN LATERAL (\n\t\t  \tSELECT true\n\t\t\tFROM metric \n\t      \t\tWHERE metric.entity_oid = entity.oid\n\t\t\tand metric.time between timestamptz $__timeTo() - interval '1 hour'\n\t\t\t- interval '1 month'\n\t\t\tand timestamptz $__timeTo()  - interval '1 month'\n\t    LIMIT 1\n\t      \t  ) as metric ON TRUE\n\t\t  where (type = 'VIRTUAL_MACHINE') and\n\t\t  (timestamptz $__timeTo() - interval '1 hour',\n\t\t   timestamptz $__timeTo()) OVERLAPS (first_seen, last_seen)),\n\nmonthAmount as (select\n\t  timestamptz $__timeTo() - interval '1 month' as time,\n\t  sum(metric.capacity) as total,\n\t  sum(metric.current) as used,\n\t  sum(metric.capacity) - sum(metric.current) as available,\n\t  avg(metric.utilization) as utilization\n\t  FROM curStorage as entity\n\t  INNER JOIN LATERAL (\n\t      SELECT metric.type, metric.current, metric.capacity, metric.utilization\n\t      FROM metric \n\t      WHERE metric.entity_oid = entity.oid\n\t      \t    and metric.type = 'STORAGE_AMOUNT'\n      \t    \t    and metric.provider_oid IS NULL\n\t\t    and metric.time between timestamptz $__timeTo() - interval '1 hour' - interval '1 month'\n\t\t    and timestamptz $__timeTo() - interval '1 month'\n\t      LIMIT 1\n\t      ) as metric ON TRUE),\n\nmonthAlloc as (select\n\t  sum(metric.current) as allocated\n\t  FROM curStorage as entity\n\t  INNER JOIN LATERAL (\n\t      SELECT metric.type, metric.current, metric.capacity, metric.utilization\n\t      FROM metric \n\t      WHERE metric.entity_oid = entity.oid\n\t      \t    and metric.type = 'STORAGE_PROVISIONED'\n      \t    \t    and metric.provider_oid IS NULL\n\t\t    and metric.time between timestamptz $__timeTo() - interval '1 hour'\n\t\t    - interval '1 month'\n\t\t    and timestamptz $__timeTo() - interval '1 month'\n\t      LIMIT 1\n\t      ) as metric ON TRUE)\n\nselect time as \"Time\", total as \"Total\", used as \"Used\", available as \"Available\", allocated as \"Allocated\", vmCount/Allocated*1e6 as \"VMs per TB\", allocated/vmCount \"Storage per VM\"\nfrom curAmount, curAlloc, curVMCount\nunion\nselect time as \"Time\", total as \"Total\", used as \"Used\", available as \"Available\", allocated as \"Allocated\", vmCount/Allocated*1e6 as \"VMs per TB\", allocated/vmCount \"Storage per VM\"\nfrom monthAmount, monthAlloc, monthVMCount\n"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "table-old",
   "description": "The following indicators compare cluster capacity vs consumption. Indicator colors show: green where consumption is below N-2 server total resources, orange for above N-2 but below N-1, and red where consumption is above N-1.",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "with cluster as (select oid, name from entity where type = 'COMPUTE_HOST_CLUSTER'),\n\ncluster_pm as (select cluster.oid as clusterOid, cluster.name as clusterName, entity.oid as pmOid\n     \t\t   from entity, cluster\n\t\t   where (type = 'PHYSICAL_MACHINE') and\n\t\t         (scope && ARRAY[cluster.oid] and\n\t\t\t (timestamptz $__timeTo() - interval '1 hour',\n       \t\t\t  timestamptz $__timeTo()) OVERLAPS (first_seen, last_seen)))\n\nselect clusterName as \"Cluster\", (sum(mem.capacity) - sum(mem.current))/max(mem.capacity) as \"Mem\",\n       \t\t    (sum(cpu.capacity) - sum(cpu.current))/max(cpu.capacity) as \"CPU\",\n       \t\t    (sum(net.capacity) - sum(net.current))/max(net.capacity) as \"Network\"\n       \t\t    --,\n--       \t\t    (sum(storage.capacity) - sum(storage.current))/max(storage.capacity) as storageN,\n--       \t\t    (sum(net.capacity) - sum(net.current))/max(net.capacity) as storageN\n     \t\t    from cluster_pm\n\n\t\t    LEFT JOIN LATERAL (\n\t\t    SELECT current, capacity\n\t\t    FROM metric \n\t      \t    WHERE metric.entity_oid = cluster_pm.pmOid\n\t\t    and metric.type = 'MEM'\n\t\t    and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n\t\t    timestamptz $__timeTo()\n\t\t    LIMIT 1\n\t      \t    ) as mem ON TRUE\n\n\t\t    LEFT OUTER JOIN LATERAL (\n\t\t    SELECT current, capacity\n\t\t    FROM metric \n\t      \t    WHERE metric.entity_oid = cluster_pm.pmOid\n\t\t    and metric.type = 'CPU'\n\t\t    and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n\t\t    timestamptz $__timeTo()\n\t\t    LIMIT 1\n\t      \t    ) as cpu ON TRUE\n\n--\t\t     LEFT OUTER JOIN LATERAL (\n--\t\t     SELECT current, capacity\n--\t\t     FROM metric \n--\t      \t     WHERE metric.entity_oid = cluster_pm.pmOid\n--\t\t     and metric.type = 'STORAGE_AMOUNT'\n--\t\t     and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n--\t\t     timestamptz $__timeTo()\n--\t\t     LIMIT 1\n--\t      \t     ) as storage ON TRUE\n\n\t\t     LEFT OUTER JOIN LATERAL (\n\t\t     SELECT current, capacity\n\t\t     FROM metric \n\t      \t     WHERE metric.entity_oid = cluster_pm.pmOid\n\t\t     and metric.type = 'NET_THROUGHPUT'\n\t\t     and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n\t\t     timestamptz $__timeTo()\n\t\t     LIMIT 1\n\t      \t     ) as net ON TRUE\n\t\t    group by cluster_pm.clusterOid, cluster_pm.clusterName\n"
    }
   ]
  }
 ]
}