{
 "title": "Physical Machine Utilization Day over Day by Hour",
 "description": "This report shows average hourly utilization measurements for Hosts compared day-over-day for the two consecutive days selected days. All machines in the selected group are included in the averages.",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "select name as __text, \n       oid as __value \nfrom entity \nwhere entity.type = 'GROUP' \nand ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) \ngroup by name, oid \norder by 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Physical Machine Avg Memory Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average Memory utilization for physical machines",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,avg(m.utilization) AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'MEM'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND ($__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n     GROUP BY 1\n)\n\nSELECT CASE WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR' THEN date_trunc('hour', time + INTERVAL '24 HOUR') ELSE date_trunc('hour', time) END as \"time\"\n      ,avg(avg_util) FILTER (WHERE $__timeFilter(time)) as \"Today\"\n      ,avg(avg_util) FILTER (WHERE time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR') as \"Yesterday\"\n  FROM data\n GROUP BY 1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg CPU Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average CPU utilization for physical machines ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,m.utilization AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'CPU'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND ($__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n)\n\nSELECT CASE WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR' THEN date_trunc('hour', time + INTERVAL '24 HOUR') ELSE date_trunc('hour', time) END as \"time\"\n      ,avg(avg_util) FILTER (WHERE $__timeFilter(time)) as \"Today\"\n      ,avg(avg_util) FILTER (WHERE time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR') as \"Yesterday\"\n  FROM data\n GROUP BY 1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Ballooning Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average Ballooning utilization for physical machines ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,m.utilization AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'BALLOONING'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND ($__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n)\n\nSELECT CASE WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR' THEN date_trunc('hour', time + INTERVAL '24 HOUR') ELSE date_trunc('hour', time) END as \"time\"\n      ,avg(avg_util) FILTER (WHERE $__timeFilter(time)) as \"Today\"\n      ,avg(avg_util) FILTER (WHERE time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR') as \"Yesterday\"\n  FROM data\n GROUP BY 1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Swapping Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average Swapping utilization for physical machines ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,m.utilization AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'SWAPPING'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND ($__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n)\n\nSELECT CASE WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR' THEN date_trunc('hour', time + INTERVAL '24 HOUR') ELSE date_trunc('hour', time) END as \"time\"\n      ,avg(avg_util) FILTER (WHERE $__timeFilter(time)) as \"Today\"\n      ,avg(avg_util) FILTER (WHERE time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR') as \"Yesterday\"\n  FROM data\n GROUP BY 1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg IO Throughput Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average IO Throughput utilization for physical machines ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,m.utilization AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'IO_THROUGHPUT'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND ($__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n)\n\nSELECT CASE WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR' THEN date_trunc('hour', time + INTERVAL '24 HOUR') ELSE date_trunc('hour', time) END as \"time\"\n      ,avg(avg_util) FILTER (WHERE $__timeFilter(time)) as \"Today\"\n      ,avg(avg_util) FILTER (WHERE time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR') as \"Yesterday\"\n  FROM data\n GROUP BY 1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Net Throughput Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average Net Throughout utilization for physical machines ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n   SELECT m.time\n          ,m.utilization AS avg_util\n      FROM entity e\n      JOIN metric m ON m.entity_oid = e.oid\n       AND m.entity_hash = e.hash\n       AND m.type = 'NET_THROUGHPUT'\n       AND e.type = 'PHYSICAL_MACHINE'\n       AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND ($__timeTo()::TIMESTAMPTZ)\n       AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (first_seen, last_seen)\n       AND CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n)\n\nSELECT CASE WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR' THEN date_trunc('hour', time + INTERVAL '24 HOUR') ELSE date_trunc('hour', time) END as \"time\"\n      ,avg(avg_util) FILTER (WHERE $__timeFilter(time)) as \"Today\"\n      ,avg(avg_util) FILTER (WHERE time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR' AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR') as \"Yesterday\"\n  FROM data\n GROUP BY 1"
    }
   ]
  }
 ]
}