{
 "title": "Utilization Week Over Week by Day",
 "description": "Host Utilization by day comparing week over week in a two week span",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "select name as __text, oid as __value from entity where entity.type = 'GROUP' and ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) and $__timeTo() >= first_seen group by name, oid order by 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT current_vals.time as \"time\",\n       current_avg as \"Current Week\",\n       offset_avg as \"Previous Week\"\nFROM\n    (SELECT\n      date_trunc('day', m.time) as \"time\",\n      avg(m.utilization) AS current_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'MEM' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      $__timeFilter(m.\"time\") AND\n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as current_vals\nJOIN\n    (SELECT\n      date_trunc('day', m.time + INTERVAL '7 DAY') as \"time\",\n      avg(m.utilization) AS offset_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'MEM' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      m.time BETWEEN ($__timeFrom()::TIMESTAMP - interval '7 day') AND ($__timeTo()::TIMESTAMP - interval '7 day') AND\n      ($__timeFrom()::TIMESTAMP - interval '7 day',$__timeTo()::TIMESTAMP - interval '7 day') OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as offset_vals\nON offset_vals.time = current_vals.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT current_vals.time as \"time\",\n       current_avg as \"Current Week\",\n       offset_avg as \"Previous Week\"\nFROM\n    (SELECT\n      date_trunc('day', m.time) as \"time\",\n      avg(m.utilization) AS current_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'CPU' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      $__timeFilter(m.\"time\") AND\n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as current_vals\nJOIN\n    (SELECT\n      date_trunc('day', m.time + INTERVAL '7 DAY') as \"time\",\n      avg(m.utilization) AS offset_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'CPU' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      m.time BETWEEN ($__timeFrom()::TIMESTAMP - interval '7 day') AND ($__timeTo()::TIMESTAMP - interval '7 day') AND\n      ($__timeFrom()::TIMESTAMP - interval '7 day',$__timeTo()::TIMESTAMP - interval '7 day') OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as offset_vals\nON offset_vals.time = current_vals.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Swapping Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT current_vals.time as \"time\",\n       current_avg as \"Current Week\",\n       offset_avg as \"Previous Week\"\nFROM\n    (SELECT\n      date_trunc('day', m.time) as \"time\",\n      avg(m.utilization) AS current_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'SWAPPING' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      $__timeFilter(m.\"time\") AND\n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as current_vals\nJOIN\n    (SELECT\n      date_trunc('day', m.time + INTERVAL '7 DAY') as \"time\",\n      avg(m.utilization) AS offset_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'SWAPPING' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      m.time BETWEEN ($__timeFrom()::TIMESTAMP - interval '7 day') AND ($__timeTo()::TIMESTAMP - interval '7 day') AND\n      ($__timeFrom()::TIMESTAMP - interval '7 day',$__timeTo()::TIMESTAMP - interval '7 day') OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as offset_vals\nON offset_vals.time = current_vals.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ballooning Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT current_vals.time as \"time\",\n       current_avg as \"Current Week\",\n       offset_avg as \"Previous Week\"\nFROM\n    (SELECT\n      date_trunc('day', m.time) as \"time\",\n      avg(m.utilization) AS current_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'BALLOONING' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      $__timeFilter(m.\"time\") AND\n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as current_vals\nJOIN\n    (SELECT\n      date_trunc('day', m.time + INTERVAL '7 DAY') as \"time\",\n      avg(m.utilization) AS offset_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'BALLOONING' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      m.time BETWEEN ($__timeFrom()::TIMESTAMP - interval '7 day') AND ($__timeTo()::TIMESTAMP - interval '7 day') AND\n      ($__timeFrom()::TIMESTAMP - interval '7 day',$__timeTo()::TIMESTAMP - interval '7 day') OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as offset_vals\nON offset_vals.time = current_vals.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "IO Throughput Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT current_vals.time as \"time\",\n       current_avg as \"Current Week\",\n       offset_avg as \"Previous Week\"\nFROM\n    (SELECT\n      date_trunc('day', m.time) as \"time\",\n      avg(m.utilization) AS current_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'IO_THROUGHPUT' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      $__timeFilter(m.\"time\") AND\n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as current_vals\nJOIN\n    (SELECT\n      date_trunc('day', m.time + INTERVAL '7 DAY') as \"time\",\n      avg(m.utilization) AS offset_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'IO_THROUGHPUT' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      m.time BETWEEN ($__timeFrom()::TIMESTAMP - interval '7 day') AND ($__timeTo()::TIMESTAMP - interval '7 day') AND\n      ($__timeFrom()::TIMESTAMP - interval '7 day',$__timeTo()::TIMESTAMP - interval '7 day') OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as offset_vals\nON offset_vals.time = current_vals.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Net Throughput Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT current_vals.time as \"time\",\n       current_avg as \"Current Week\",\n       offset_avg as \"Previous Week\"\nFROM\n    (SELECT\n      date_trunc('day', m.time) as \"time\",\n      avg(m.utilization) AS current_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'NET_THROUGHPUT' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      $__timeFilter(m.\"time\") AND\n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as current_vals\nJOIN\n    (SELECT\n      date_trunc('day', m.time + INTERVAL '7 DAY') as \"time\",\n      avg(m.utilization) AS offset_avg\n    FROM entity e\n    JOIN metric m ON m.entity_oid = e.oid AND\n      m.entity_hash = e.hash AND\n      m.type = 'NET_THROUGHPUT' AND\n      e.type = 'PHYSICAL_MACHINE'  AND\n      m.time BETWEEN ($__timeFrom()::TIMESTAMP - interval '7 day') AND ($__timeTo()::TIMESTAMP - interval '7 day') AND\n      ($__timeFrom()::TIMESTAMP - interval '7 day',$__timeTo()::TIMESTAMP - interval '7 day') OVERLAPS (first_seen, last_seen) AND\n      CASE WHEN ARRAY[ [[Group]] ] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[ [[Group]] ]::bigint[]) END\n    GROUP BY 1) as offset_vals\nON offset_vals.time = current_vals.time\nORDER BY 1"
    }
   ]
  }
 ]
}