use vmtdb ;
--
-- Dumping data for table `standard_reports`
--
delete from `standard_reports`;
LOCK TABLES `standard_reports` WRITE;

INSERT INTO `standard_reports` (`id`, `title`, `description`, `short_desc`, `category`, `filename`, `period`, `day_type`) VALUES 
    (140,'Host/VM - 30 Days Stats vs Thresholds','This report shows daily average utilization measurements for the past 30 days. Averages are grouped into two sections. One rolled up for physical machines and another rolled up for virtual machines.','30 days average utilization stats vs thresholds','Capacity Management/Hosts','daily_infra_30_days_avg_stats_vs_thresholds_grid','Daily',NULL), 
    (145,'Hosting Summary by Physical Machine','This report shows the ratio of VMs per Host over the prior 60 days, and shows the most recent measured hosting levels for each host.','Infra 60 Day Hosting Ratios','Workload Balancing','daily_infra_60_days_hosting_bar','Daily',NULL), 
    (146,'Monthly Overview with Cluster Summary','This report shows monthly statistics for the enterprise as a whole, and a monthly summary for each cluster.','Monthly Overview with Cluster Summary','Capacity Management/Hosts','monthly_cluster_summary','Monthly',NULL), 
    (147,'Monthly Overview','This report shows monthly statistics for the enterprise.','Monthly Overview','Capacity Management/Hosts','monthly_summary','Monthly',NULL), 
    (148,'VM Over/Under Provisioning 90 Days','This report shows Virtual Machines that are over and under provisioned as indicated by their utilization of CPU and Memory','VM Over/Under Provisioning 90 Days','Capacity Management/VMs','daily_vm_over_under_prov_grid','Daily',NULL), 
    (150,'VM Rightsizing Recommendations','This report shows rightsizing recommendations for Virtual Machines based on time range and threshold settings','VM Rightsizing Recommendations','Capacity Management/VMs','daily_vm_rightsizing_advice_grid','Daily',NULL), 
    (153,'Utilization Day Over Day by Hour','This report shows average hourly utilization measurements compared day-over-day for the two days indicated. All machines in the infrastructure are included in the averages.','Utilization Day Over Day by Hour','Performance Management/Enterprise','daily_infra_utilization_day_over_day_by_hour_line','Daily',NULL), 
    (154,'Utilization Levels by Hour','This report shows by-hour averages for CPU and Memory utlization measurements for Physical and Virtual machines. Averages are rolled up for all machines.','Infra Utilization Levels by Hour','Performance Management/Enterprise','daily_infra_utilization_levels_by_hour_line','Daily',NULL), 
    (155,'Host/VM - Top Bottom Utilized','This report shows the top and bottom physical and virtual machines by their Price Index measurements. Price Index is a derived value that reflects the consumption levels of key compute resources taken in combination. Larger values indicate machines on which resources are most utilized.','Host/VM Top Bottom Utilized','Performance Management/Hosts','daily_pm_vm_top_bottom_utilized_grid','Daily',NULL), 
    (156,'Host/VM - Resource Utilization Heatmap','This report shows the hottest physical and virtual machines according to their Price Index measurements.  Price Index is a derived value that reflects the consumption levels of key compute resources taken in combination. Larger values indicate machines on which resources are most utilized.','Host/VM Utilization Heatmap','Capacity Management/Hosts','daily_pm_vm_utilization_heatmap_grid','Daily',NULL), 
    (160,'Utilization Week Over Week by Day','This report shows average daily utilization measurements compared week-over-week for the two weeks indicated. All machines in the infrastructure are included in the averages.','Infra Utilization Week Over Week by Day','Performance Management/Enterprise','weekly_infra_utilization_week_over_week_by_day_line','Weekly',NULL), 
    (165,'Host Top Bottom Capacity','Shows a capacity-centered view of CPU and Memory utilization, providing actual quantities both used and in reserve.  ','Host Top Bottom Capacity','Capacity Management/Hosts','daily_pm_top_bottom_capacity_grid','Daily',NULL), 
    (166,'VM Top Bottom Capacity','Shows a capacity-centered view of VCPU and VMemory utilization, providing actual quantities both used and in reserve.  ','VM Top Bottom Capacity','Capacity Management/VMs','daily_vm_top_bottom_capacity_grid','Daily',NULL), 
    (167,'Storage Top Bottom Capacity','This report shows the top and bottom data stores based on their level of consumption as of the date indicated.','Storage Top Bottom Capacity','Capacity Management/Storage','daily_storage_top_bottom_capacity_grid','Daily',NULL), 
    (168,'Host Top CPU Ready Queue','Shows top machines by CPU ready queue utilization ','Host Top CPU Ready Queue','Performance Management/Hosts','daily_pm_top_cpu_ready_queue_grid','Daily',NULL), 
    (169,'Top Host Utilization by Resource','Shows top machines by utilization of each resource type','Top Host Utilization by Resource','Performance Management/Hosts','daily_pm_top_resource_utilization_bar','Daily',NULL), 
    (170,'Host/VM Groups - 30 Day Stats vs Thresholds','Shows a roll-up of average utilization values per day for 30 days for each grouping of machines.  Values are highlighted where they cross certain threshold values that may indicate a condition of over utilization of resources. ','Machine Groups 30 Day Avg Stats vs Thresholds','Capacity Management/Hosts','daily_cluster_30_days_avg_stats_vs_thresholds_grid','Daily',NULL), 
    (172,'Storage Associated with Dormant VMs','This report shows the amounts of storage used by virtual machines that have been dormant for several days.  This storage has the potential to be reclaimed, depending upon the final disposition of such VMs. ','Storage Associated with Dormant VMs','Capacity Management/Storage','daily_potential_storage_waste_grid','Daily',NULL), 
    (173,'Storage Top Disk Consumption','This report presents two independent views of information related to VDisk storage. The first highlights data stores that possess the largest amounts of VDisk storage.  The second lists Virtual Machines organized most to least in terms of their consumption of VDisk storage. ','Storage Top Disk','Capacity Management/Storage','daily_digest_storage_top_disk_grid','Daily',NULL), 
    (175,'Storage Top Log Consumption','This report presents two independent views of information related to Log storage. The first highlights data stores that possess the largest amounts of Log storage.  The second lists Virtual Machines organized most to least in terms of their consumption of Log storage. ','Storage Top Log','Capacity Management/Storage','daily_digest_storage_top_log_grid','Daily',NULL), 
    (176,'Storage Top Snapshot Consumption','This report presents two independent views of information related to Snapshot storage. The first highlights data stores that possess the largest amounts of Snapshot storage.  The second lists Virtual Machines organized most to least in terms of their consumption of Snapshot storage. ','Storage Top Snapshot','Capacity Management/Storage','daily_digest_storage_top_snapshot_grid','Daily',NULL), 
    (177,'Storage Top Swap Consumption','This report presents two independent views of information related to Swap storage. The first highlights data stores that possess the largest amounts of Swap storage.  The second lists Virtual Machines organized most to least in terms of their consumption of Swap storage. ','Storage Top Swap','Capacity Management/Storage','daily_digest_storage_top_swap_grid','Daily',NULL), 
    (178,'Storage Wasted Allocations','This report presents data stores that possess the largest amounts of wasted storage.  Wasted storage is taken as storage used for purposes not directly associated with supporting the operation of a VM.','Storage Waste','Capacity Management/Storage','daily_digest_storage_top_unused_grid','Daily',NULL), 
    (179,'Storage Access IO Latency','This report presents two independent views of information related to Latency in accessing storage. The first highlights data stores having the largest amounts of storage access latency.  The second lists Virtual Machines organized most to least in terms of latency in accessing storage. ','Digest Storage Top Latency','Performance Management/Storage','daily_digest_storage_top_latency_grid','Daily',NULL), 
    (180,'Storage Access IOPS','This report presents two independent views of information related to IOPS for storage. The first highlights data stores that possess the largest usage of IOPS.  The second lists Virtual Machines organized most to least in terms of their use of IOPS related to storage. ','Digest Storage Top Latency','Performance Management/Storage','daily_digest_storage_top_iops_grid','Daily',NULL), 
    (181,'Individual VM Monthly Summary','This report shows a monthly summary of Virtual Machines CPU, Memory and Storage measurements','End of the month CPU, Memory, Storage summary','Capacity Management/VMs','monthly_individual_vm_summary','Monthly', NULL), 
    (182,'Monthly Top Bottom 15 Hosts Capacity','Shows a capacity-centered view of CPU and Memory utilization, providing actual quantities both used and in reserve.  ','Host 15 Top Bottom Capacity','Capacity Management/Hosts','monthly_30_days_pm_top_bottom_capacity_grid','Monthly', NULL), 
    (183,'Monthly Top Bottom 15 VMs Capacity','Shows a capacity-centered view of CPU and Memory utilization, providing actual quantities both used and in reserve.  ','VM 15 Top Bottom Capacity','Capacity Management/VMs','monthly_30_days_vm_top_bottom_capacity_grid','Monthly', NULL), 
    (184,'VM Over/Under Provisioning 30 Days','This report shows Virtual Machines that are over and under provisioned as indicated by their utilization of CPU and Memory','VM Over/Under Provisioning 30 Days','Capacity Management/VMs','daily_vm_over_under_prov_grid_30_days','Daily', NULL), 
    (185,'Storage Access IO Latency - 30 Days','This report presents two independent views of information related to Latency in accessing storage. The first highlights data stores having the largest amounts of storage access latency.  The second lists Virtual Machines organized most to least in terms of latency in accessing storage. ','Digest Storage Top Latency','Performance Management/Storage','daily_digest_storage_top_latency_grid_30_days','Daily',NULL), 
    (186,'Storage Access IOPS - 30 Days','This report presents two independent views of information related to IOPS for storage. The first highlights data stores that possess the largest usage of IOPS.  The second lists Virtual Machines organized most to least in terms of their use of IOPS related to storage. ','Digest Storage Top Latency','Performance Management/Storage','daily_digest_storage_top_iops_grid_30_days','Daily',NULL), 
    (187,'Storage Access IO Latency - 7 Days','This report presents two independent views of information related to Latency in accessing storage. The first highlights data stores having the largest amounts of storage access latency.  The second lists Virtual Machines organized most to least in terms of latency in accessing storage. ','Digest Storage Top Latency','Performance Management/Storage','daily_digest_storage_top_latency_grid_7_days','Daily',NULL), 
    (188,'Storage Access IOPS - 7 Days','This report presents two independent views of information related to IOPS for storage. The first highlights data stores that possess the largest usage of IOPS.  The second lists Virtual Machines organized most to least in terms of their use of IOPS related to storage. ','Digest Storage Top Latency','Performance Management/Storage','daily_digest_storage_top_iops_grid_7_days','Daily',NULL), 
    (189,'Weekly Socket Audit Report','This report gives a socket count per PM for licensing purposes ','Socket Audit Report Weekly','Capacity Management/Hosts','weekly_socket_audit_report','Weekly',NULL), 
    (190, 'Monthly VMem Capacity', 'This report shows the VMem capacity over the last month, that was assigned to the VMs in the environment. Where the capacity for a VM was increased or decreased during the month, the higher value is used for the entire month. This report also lists all the clusters that were active in the month.', 'VMem Capacity', 'Capacity Management/VMs', 'monthly_VMem_capacity_cost', 'Monthly', NULL);
UNLOCK TABLES;

--
-- Dumping data for table `on_demand_reports`
--
delete from `on_demand_reports`;
LOCK TABLES `on_demand_reports` WRITE;
INSERT INTO `on_demand_reports` (`id`, `obj_type`, `scope_type`, `short_desc`, `filename`, `description`, `category`, `title`) VALUES 
    (1,'PhysicalMachine','Group','Host Group Summary','pm_group_profile','Host Group Summary','Performance Management/Hosts','Host Group Summary'),
    (2,'PhysicalMachine','Instance','Host Summary','pm_profile','Host Summary','Performance Management/Hosts','Host Summary'),
    (3,'Storage','Group','Datastore Group Summary','sd_group_profile','Datastore Group Summary','Performance Management/Storage','Datastore Group Summary'),
    (4,'Storage','Instance','Data Store Summary','sd_profile','Data Store Summary','Performance Management/Storage','Data Store Summary'),
    (5,'VirtualMachine','Group','VM Group Summary','vm_group_profile','VM Group Summary','Performance Management/VMs','VM Group Summary'),
    (6,'VirtualMachine','Instance','Virtual Machine Summary','vm_profile','Virtual Machine Summary','Performance Management/VMs','Virtual Machine Summary'),
    (7,'PhysicalMachine','Group','Host Group Capacity Usage Projection','pm_group_capacity_usage_projection','Host Group Capacity Usage Projection','Capacity Management/Hosts','Host Group Capacity Usage Projection'),
    (8,'PhysicalMachine','Group','Hosting Summary by Host Group','pm_group_hosting','Hosting Summary by Host Group','Capacity Management/Hosts','Hosting Summary by Host Group'),
    (9,'VirtualMachine','Group','Physical Resources Chargeback by VM Group','vm_group_profile_physical_resources','Monthly Virtual Machine summary of Physical Resources','Capacity Management/VMs','Physical Resources Chargeback'),
    (10,'VirtualMachine','Group','Individual VM Monthly Summary by VM Group','vm_group_individual_monthly_summary','Monthly Virtual Machine Group Summary Breakdown by Individual VM','Capacity Management/VMs','Individual VM Monthly Summary by VM Group'),
    (11,'VirtualMachine','Group','Month Based VM Group Over Under Provisioning','vm_group_daily_over_under_prov_grid_30_days','Month Based VM Group Over Under Provisioning','Capacity Management/VMs','Month Based VM Group Over Under Provisioning'),
    (12,'VirtualMachine','Group','Shows a capacity-centered view of CPU and Memory utilization, providing actual quantities both used and in reserve.  ','vm_group_30_days_vm_top_bottom_capacity_grid','Shows a capacity-centered view of CPU and Memory utilization, providing actual quantities both used and in reserve.  ','Capacity Management/VMs','VM 15 Top Bottom Capacity'),
    (13,'VirtualMachine','Group','This report shows Virtual Machines that are over and under provisioned as indicated by their utilization of CPU and Memory','vm_group_daily_over_under_prov_grid_given_days','This report shows Virtual Machines that are over and under provisioned as indicated by their utilization of CPU and Memory  ','VM Over/Under Provisioning 90 Days','VM Group Over/Under Provisioning by Number of Days Ago'),
    (14,'PhysicalMachine','Group','Monthly Individual Cluster Summary ','pm_group_monthly_individual_cluster_summary','Monthly Individual Cluster Summary','Performance Management/Hosts','Host Monthly Individual Cluster Summary'),
    (15,'PhysicalMachine','Group','Host Top Bottom Capacity Grid Per Cluster','pm_group_pm_top_bottom_capacity_grid_per_cluster','Host Top Bottom Capacity Grid Per Cluster','Performance Management/Hosts','Host Top Bottom Capacity Grid Per Cluster'),
    (16,'PhysicalMachine','Group','Host/VM Group - Resource Utilization Heatmap','pm_group_daily_pm_vm_utilization_heatmap_grid','Heatmap report per cluster','Capacity Management/Hosts','Host/VM Group - Resource Utilization Heatmap');
UNLOCK TABLES;


LOCK TABLES `report_attrs` WRITE;
INSERT INTO `report_attrs` (`id`, `report_id`, `report_type`, `name`, `default_value`, `att_type`)
VALUES
	(4,2,2,'num_days_ago','30','int'),
	(2,6,2,'num_days_ago','30','int'),
	(3,6,2,'show_charts','True','boolean'),
	(1,13,2,'num_days_ago','30','int');
UNLOCK TABLES;


