{
 "title": "Datastore Group Summary",
 "description": "Performance and capacity profile, including trends, for selected datastores.",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "SELECT name as __text,\n       oid as __value\nFROM entity_old as entity\nWHERE ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\nAND (type = 'STORAGE_CLUSTER'\nOR (type = 'GROUP'\n   AND attrs -> 'member_types' ? 'STORAGE'))\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Datastore Avg Consumption",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT sum(used) as \"Storage Used\"\n      ,sum(capacity) as \"Storage Capacity\"\n      ,round((sum(used)/NULLIF(sum(capacity),0))::numeric, 4) as \"Utilization\"\nFROM\n        (SELECT e.oid\n              ,avg(m.current) AS used\n              ,avg(m.capacity)::numeric AS capacity\n        FROM entity_old e\n        join metric_old m ON m.entity_oid = e.oid\n          AND m.type = 'STORAGE_AMOUNT'\n          AND m.entity_hash = e.hash\n          AND e.type = 'STORAGE'\n          AND $__timeFilter(m.\"time\")\n          AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n          AND CASE WHEN ARRAY[$Group]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[$Group]::bigint[]) END\n        GROUP BY 1) as data_tbl"
    }
   ]
  },
  {
   "title": "Datastore Performance Stats",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nunnest(array['AVG','MIN','MAX']) as \"Aggregation\",\nunnest(array[avg(metric.utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'),\nmin(metric.utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'),\nmax(metric.Utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT')\n]) AS \"Utilization\",\nunnest(array[avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS'),\nmin(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS'),\nmax(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS')\n]) AS \"IOPS\",\nunnest(array[avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY'),\nmin(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY'),\nmax(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY')\n]) AS \"Latency\"\nFROM metric_old as metric, entity_old as entity\nWHERE entity.type = 'STORAGE' and\nCASE WHEN ARRAY[$Group]::text[] = ARRAY[ '0' ] THEN true ELSE (entity.scope && array[$Group]::bigint[]) END and\nentity.oid = metric.entity_oid and entity.hash = metric.entity_hash and\n$__timeFilter(\"time\") and ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)"
    }
   ]
  },
  {
   "title": "Datastore Consumption Trend",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n      date_trunc('hour', m.time) as \"time\",\n      ROUND((sum(m.current)/sum(m.capacity))::NUMERIC, 4) AS \"Storage Amount Used\"\nFROM entity_old e\njoin metric_old m ON m.entity_oid = e.oid\n  AND m.type = 'STORAGE_AMOUNT'\n  AND m.entity_hash = e.hash\n  AND e.type = 'STORAGE'\n  AND $__timeFilter(m.\"time\")\n  AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND CASE WHEN ARRAY[$Group]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[$Group]::bigint[]) END\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Datastore Performance Trends",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT m.time\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_ACCESS') AS \"IOPS Avg\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_LATENCY') AS \"Latency Avg\"\nFROM entity_old e\njoin metric_old m ON m.entity_oid = e.oid\n  AND m.type IN ('STORAGE_ACCESS', 'STORAGE_LATENCY')\n  AND m.entity_hash = e.hash\n  AND e.type = 'STORAGE'\n  AND $__timeFilter(m.\"time\")\n  AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND CASE WHEN ARRAY[$Group]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[$Group]::bigint[]) END\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Consumption Stats By Datastore",
   "type": "table",
   "description": "Average values.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT e.name as \"Datastore\"\n      ,avg(m.capacity) FILTER (WHERE m.type = 'STORAGE_AMOUNT') AS \"Storage Capacity\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_AMOUNT') AS \"Storage Used\"\n      ,avg(m.utilization) FILTER (WHERE m.type = 'STORAGE_AMOUNT') as \"Storage Utilization\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_PROVISIONED') as \"Storage Provisioned\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_PROVISIONED') /\n            NULLIF(avg(m.capacity) FILTER (WHERE m.type = 'STORAGE_AMOUNT'), 0) as \"Storage Over-Provisioned\"\nFROM entity_old e\njoin metric_old m ON m.entity_oid = e.oid\n  AND m.type IN ('STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n  AND m.entity_hash = e.hash\n  AND e.type = 'STORAGE'\n  AND $__timeFilter(m.\"time\")\n  AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND CASE WHEN ARRAY[$Group]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[$Group]::bigint[]) END\nGROUP BY 1\nORDER BY 4 DESC"
    }
   ]
  },
  {
   "title": "Performance Stats By Datastore",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "rawSql": "SELECT e.name as \"Datastore\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_ACCESS') AS \"IOPS Avg\"\n      ,max(m.current) FILTER (WHERE m.type = 'STORAGE_ACCESS') AS \"IOPS Max\"\n      ,avg(m.current) FILTER (WHERE m.type = 'STORAGE_LATENCY') AS \"Latency Avg\"\n      ,max(m.current) FILTER (WHERE m.type = 'STORAGE_LATENCY') AS \"Latency Max\"\nFROM entity_old e\njoin metric_old m ON m.entity_oid = e.oid\n  AND m.type IN ('STORAGE_ACCESS', 'STORAGE_LATENCY')\n  AND m.entity_hash = e.hash\n  AND e.type = 'STORAGE'\n  AND $__timeFilter(m.\"time\")\n  AND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND CASE WHEN ARRAY[$Group]::text[] = ARRAY[ '0' ] THEN true ELSE (e.scope && ARRAY[$Group]::bigint[]) END\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  }
 ]
}