{
 "title": "Monthly Overview and Cluster Summary",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "table-old",
   "description": "This panel presents statistics for the virtual enterprise as a whole. Values are provided showing month over month with growth.",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with this_month_vms as (\nSELECT\n        distinct oid\nFROM entity_old as entity\nINNER JOIN LATERAL (\n    SELECT true\n      FROM metric_old as metric\n      WHERE metric.entity_oid = entity.oid\n      and metric.entity_hash = entity.hash\n      and metric.time between timestamptz $__timeTo() - interval '1 hour' and $__timeTo()\n      LIMIT 1\n) as foo ON true WHERE\n  (type = 'VIRTUAL_MACHINE') and\n  (timestamptz $__timeTo() - interval '1 hour', $__timeTo()) OVERLAPS (first_seen, last_seen)),\nlast_month_vms as (\nSELECT\n        distinct oid\nFROM entity_old as entity\nINNER JOIN LATERAL (\n    SELECT true\n      FROM metric_old as metric\n      WHERE metric.entity_oid = entity.oid\n      and metric.entity_hash = entity.hash\n      and metric.time between timestamptz $__timeTo() - interval '1 month' - interval '1 hour'\n                          and timestamptz $__timeTo() - interval '1 month'\n      LIMIT 1\n) as foo on true WHERE\n  (type = 'VIRTUAL_MACHINE') and\n  (timestamptz $__timeTo() - interval '1 month' - interval '1 hour',\n   timestamptz $__timeTo() - interval '1 month') OVERLAPS (first_seen, last_seen)),\nthis_month_pm_count as (\nSELECT\n        count(distinct oid) as pmCount\nFROM entity_old as entity\nINNER JOIN LATERAL (\n    SELECT true\n      FROM metric_old as metric\n      WHERE metric.entity_oid = entity.oid\n      and metric.entity_hash = entity.hash\n      and metric.time between timestamptz $__timeTo() - interval '1 hour' and $__timeTo()\n      LIMIT 1\n) as foo ON true WHERE\n  (type = 'PHYSICAL_MACHINE') and\n  (timestamptz $__timeTo() - interval '1 hour', $__timeTo()) OVERLAPS (first_seen, last_seen)),\nlast_month_pm_count as (\nSELECT\n        count(distinct oid) as pmCount\nFROM entity_old as entity\nINNER JOIN LATERAL (\n    SELECT true\n      FROM metric_old as metric\n      WHERE metric.entity_oid = entity.oid\n      and metric.entity_hash = entity.hash\n      and metric.time between timestamptz $__timeTo() - interval '1 month' - interval '1 hour'\n                          and timestamptz $__timeTo() - interval '1 month'\n      LIMIT 1\n) as foo on true WHERE\n  (type = 'PHYSICAL_MACHINE') and\n  (timestamptz $__timeTo() - interval '1 month' - interval '1 hour',\n   timestamptz $__timeTo() - interval '1 month') OVERLAPS (first_seen, last_seen))\nselect month as time, pmCount as \"Host Count\", vmCount as \"VM Count\", vmCount::float4/nullif(pmCount,0) as \"VMs Per Host\",\nvmsAdded \"VMs Added This Month\", vmsRemoved \"VMs Removed This Month\"\nfrom\n(SELECT\n  timestamptz $__timeTo() as month,\n        (select pmCount from this_month_pm_count) as pmCount,\n        (select count(oid) from this_month_vms) as vmCount,\n        (select count(*)\n    from (\n    select oid from this_month_vms\n    except\n    select oid from last_month_vms\n    )  foo\n  ) as vmsAdded,\n  (select count(*)\n    from (\n    select oid from last_month_vms\n    except\n    select oid from this_month_vms\n    )  foo\n  ) as vmsRemoved\n\nunion\nSELECT\n  timestamptz $__timeTo() - interval '1 month' as month,\n        (select pmCount from last_month_pm_count) as pmCount,\n        (select count(oid) from last_month_vms) as vmCount,\n        -1 as vmsAdded,\n        -1 as vmsRemoved\n) foo\n"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "with\ncurStorage as (select distinct oid\n                  from entity_old as entity\n                  where (type = 'STORAGE') and\n                  (timestamptz $__timeTo() - interval '1 hour',\n                   timestamptz $__timeTo()) OVERLAPS (first_seen, last_seen)),\n\ncurVMCount as (select count(distinct oid) vmCount\n                  from entity_old as entity\n                  INNER JOIN LATERAL (\n                        SELECT true\n                        FROM metric_old as metric\n                        WHERE metric.entity_oid = entity.oid\n                        and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n                        timestamptz $__timeTo()\n            LIMIT 1\n                  ) as metric ON TRUE\n                  where (type = 'VIRTUAL_MACHINE') and\n                  (timestamptz $__timeTo() - interval '1 hour',\n                   timestamptz $__timeTo()) OVERLAPS (first_seen, last_seen)),\n\ncurAmount as (select\n          timestamptz $__timeTo() as time,\n          sum(metric.capacity) as total,\n          sum(metric.current) as used,\n          sum(metric.capacity) - sum(metric.current) as available,\n          avg(metric.utilization) as utilization\n          FROM curStorage as entity\n          INNER JOIN LATERAL (\n              SELECT metric.type, metric.current, metric.capacity, metric.utilization\n              FROM metric_old as metric\n              WHERE metric.entity_oid = entity.oid\n                    and metric.type = 'STORAGE_AMOUNT'\n                    and metric.provider_oid IS NULL\n                    and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n                        timestamptz $__timeTo()\n              LIMIT 1\n              ) as metric ON TRUE),\n\ncurAlloc as (select\n          sum(metric.current) as allocated\n          FROM curStorage as entity\n          INNER JOIN LATERAL (\n              SELECT metric.type, metric.current, metric.capacity, metric.utilization\n              FROM metric_old as metric\n              WHERE metric.entity_oid = entity.oid\n                    and metric.type = 'STORAGE_PROVISIONED'\n                    and metric.provider_oid IS NULL\n                    and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n                        timestamptz $__timeTo()\n              LIMIT 1\n              ) as metric ON TRUE),\n\nmonthStorage as (select distinct oid\n                  from entity_old as entity\n                  where (type = 'STORAGE') and\n                  (timestamptz $__timeTo() - interval '1 hour' - interval '1 month',\n                   timestamptz $__timeTo() - interval '1 month') OVERLAPS (first_seen, last_seen)),\n\nmonthVMCount as (select count(distinct oid) vmCount\n                  from entity_old as entity\n                  INNER JOIN LATERAL (\n                        SELECT true\n                        FROM metric_old as metric\n                        WHERE metric.entity_oid = entity.oid\n                        and metric.time between timestamptz $__timeTo() - interval '1 hour'\n                        - interval '1 month'\n                        and timestamptz $__timeTo()  - interval '1 month'\n            LIMIT 1\n                  ) as metric ON TRUE\n                  where (type = 'VIRTUAL_MACHINE') and\n                  (timestamptz $__timeTo() - interval '1 hour',\n                   timestamptz $__timeTo()) OVERLAPS (first_seen, last_seen)),\n\nmonthAmount as (select\n          timestamptz $__timeTo() - interval '1 month' as time,\n          sum(metric.capacity) as total,\n          sum(metric.current) as used,\n          sum(metric.capacity) - sum(metric.current) as available,\n          avg(metric.utilization) as utilization\n          FROM curStorage as entity\n          INNER JOIN LATERAL (\n              SELECT metric.type, metric.current, metric.capacity, metric.utilization\n              FROM metric_old as metric\n              WHERE metric.entity_oid = entity.oid\n                    and metric.type = 'STORAGE_AMOUNT'\n                    and metric.provider_oid IS NULL\n                    and metric.time between timestamptz $__timeTo() - interval '1 hour' - interval '1 month'\n                    and timestamptz $__timeTo() - interval '1 month'\n              LIMIT 1\n              ) as metric ON TRUE),\n\nmonthAlloc as (select\n          sum(metric.current) as allocated\n          FROM curStorage as entity\n          INNER JOIN LATERAL (\n              SELECT metric.type, metric.current, metric.capacity, metric.utilization\n              FROM metric_old as metric\n              WHERE metric.entity_oid = entity.oid\n                    and metric.type = 'STORAGE_PROVISIONED'\n                    and metric.provider_oid IS NULL\n                    and metric.time between timestamptz $__timeTo() - interval '1 hour'\n                    - interval '1 month'\n                    and timestamptz $__timeTo() - interval '1 month'\n              LIMIT 1\n              ) as metric ON TRUE)\n\nselect time as \"Time\", total as \"Total\", used as \"Used\", available as \"Available\", allocated as \"Allocated\", vmCount/Allocated*1e6 as \"VMs per TB\", allocated/vmCount \"Storage per VM\"\nfrom curAmount, curAlloc, curVMCount\nunion\nselect time as \"Time\", total as \"Total\", used as \"Used\", available as \"Available\", allocated as \"Allocated\", vmCount/Allocated*1e6 as \"VMs per TB\", allocated/vmCount \"Storage per VM\"\nfrom monthAmount, monthAlloc, monthVMCount\n"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "table-old",
   "description": "The following indicators compare cluster capacity vs consumption. Indicator colors show: green where consumption is below N-2 server total resources, orange for above N-2 but below N-1, and red where consumption is above N-1.",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "with cluster as (select oid, name from entity where type = 'COMPUTE_CLUSTER' and last_seen >= timestamptz $__timeTo()),\n\ncluster_pm as (select distinct cluster.oid as clusterOid, cluster.name as clusterName, entity.oid as pmOid\n                   from entity_old as entity, cluster\n                   where (type = 'PHYSICAL_MACHINE') and\n                         (scope && ARRAY[cluster.oid] and\n                         (timestamptz $__timeTo() - interval '1 hour',\n                          timestamptz $__timeTo()) OVERLAPS (first_seen, last_seen)))\n\nselect clusterName as \"Cluster\", (sum(mem.capacity) - sum(mem.current))/NULLIF(max(mem.capacity),0) as \"Mem\",\n                    (sum(cpu.capacity) - sum(cpu.current))/NULLIF(max(cpu.capacity),0) as \"CPU\",\n                    (sum(net.capacity) - sum(net.current))/NULLIF(max(net.capacity),0) as \"Network\"\n                    --,\n--                          (sum(storage.capacity) - sum(storage.current))/max(storage.capacity) as storageN,\n--                          (sum(net.capacity) - sum(net.current))/max(net.capacity) as storageN\n                    from cluster_pm\n\n                    LEFT JOIN LATERAL (\n                    SELECT current, capacity\n                    FROM metric_old as metric\n                    WHERE metric.entity_oid = cluster_pm.pmOid\n                    and metric.type = 'MEM'\n                    and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n                    timestamptz $__timeTo()\n                    LIMIT 1\n                    ) as mem ON TRUE\n\n                    LEFT OUTER JOIN LATERAL (\n                    SELECT current, capacity\n                    FROM metric_old as metric\n                    WHERE metric.entity_oid = cluster_pm.pmOid\n                    and metric.type = 'CPU'\n                    and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n                    timestamptz $__timeTo()\n                    LIMIT 1\n                    ) as cpu ON TRUE\n\n--                   LEFT OUTER JOIN LATERAL (\n--                   SELECT current, capacity\n--                   FROM metric_old as metric\n--                   WHERE metric.entity_oid = cluster_pm.pmOid\n--                   and metric.type = 'STORAGE_AMOUNT'\n--                   and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n--                   timestamptz $__timeTo()\n--                   LIMIT 1\n--                   ) as storage ON TRUE\n\n                     LEFT OUTER JOIN LATERAL (\n                     SELECT current, capacity\n                     FROM metric_old as metric\n                     WHERE metric.entity_oid = cluster_pm.pmOid\n                     and metric.type = 'NET_THROUGHPUT'\n                     and metric.time between timestamptz $__timeTo() - interval '1 hour' and\n                     timestamptz $__timeTo()\n                     LIMIT 1\n                     ) as net ON TRUE\n                    group by cluster_pm.clusterOid, cluster_pm.clusterName\n"
    }
   ]
  }
 ]
}