package com.vmturbo.cost.component.reserved.instance.recommendationalgorithm.demand;

import java.util.List;

import javax.annotation.Nonnull;

import org.immutables.value.Value;

import com.vmturbo.common.protobuf.topology.TopologyDTO.TopologyEntityDTO;
import com.vmturbo.cost.calculation.integration.CloudTopology;
import com.vmturbo.cost.component.reserved.instance.recommendationalgorithm.inventory.RegionalRIMatcherCache;

/**
 * Represents the output of {@link RIBuyAnalysisContextProvider}, which will compute the demand contexts
 * to be analyzed for potential RI buy recommendations.
 */
@Value.Immutable
public interface RIBuyAnalysisContextInfo {

    /**
     * This is the cloud topology used in validating the demand clusters stored in the DB. It represents
     * the latest realtime cloud topology.
     *
     * @return The cloud topology used during context generation.
     */
    @Nonnull
    CloudTopology<TopologyEntityDTO> cloudTopology();

    /**
     * The {@link RegionalRIMatcherCache} used by the context provider in generating RI spec matchers,
     * in order to group demand clusters from the DB under a single buy recommendation.
     *
     * @return The {@link RegionalRIMatcherCache}, in order to provide access to RI inventory matchers
     * during uncovered demand calculations.
     */
    @Nonnull
    RegionalRIMatcherCache regionalRIMatcherCache();

    /**
     * The regional contexts generated by the context provider. A regional context represents a grouping
     * of demand clusters (unique demand in the DB) by (region OID, account grouping ID, RI spec to purchase)
     * @return The list of {@link RIBuyRegionalContext}. Order is not significant.
     */
    @Nonnull
    List<RIBuyRegionalContext> regionalContexts();


}
