
User:
    full_text_search:
        all: true
    fast_ops:
        all: true
    public_pages:
        all: true
    pm_stats_by_hours:
        all: true
    pm_stats_by_days:
        all: true
    vm_stats_by_hours:
        all: true
    vm_stats_by_days:
        all: true
    ds_stats_by_hours:
        all: true
    ds_stats_by_days:
        all: true
    audit_log_entries:
        all: true
    user_reports:
        all: true
    standard_reports:
        all: true
    on_demand_reports:
        all: true
    report_subscriptions:
        all: true
    version_infos:
        all: true
    vc_licenses:
        all: true
    notifications:
        all: true
    entity_assns:
        all: true
    classifications:
        all: true
    entities:
        all: true
    entity_attrs:
        all: true

#BEGIN-UID.auth_ext

    objects:
      all: true
    user_tables:
      all: true

#END-UID.auth_ext

