{
 "title": "Datastore Summary",
 "description": "Performance and capacity profile for datastores.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Datastore",
    "query": "SELECT name as __text, oid as __value\nFROM entity\nWHERE ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\n  AND entity.type = 'STORAGE'\nGROUP BY name, oid\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Datastore Summary",
   "type": "table",
   "description": "Capacity is max value. Provisioned Used, Used, IOPS and Latency are average values.",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  max(metric.capacity) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS \"Capacity\",\n  avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') AS \"Provisioned Used\",\n  avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS \"Used\",\n  avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS') AS \"IOPS\",\n  avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY') AS \"Latency\"\nFROM metric\nJOIN entity as e ON\n  e.type = 'STORAGE'\n  and e.oid = metric.entity_oid\nWHERE\n  e.oid = ${Datastore:raw} + 0\n  and ($__timeFrom(),$__timeTo()) OVERLAPS (e.first_seen, e.last_seen)\n  and metric.time BETWEEN timestamptz $__timeFrom() AND $__timeTo()\n"
    }
   ]
  },
  {
   "title": "Datastore Resource Utilization",
   "type": "table",
   "description": "Average, min and max values datastore utilization, IOPS and latency.",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unnest(array['1','2','3']) as \"order\",\n  unnest(array['AVG','MIN','MAX']) as \"Aggregation\",\n  unnest(array[\n    avg(metric.utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'),\n    min(metric.utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'),\n    max(metric.Utilization) FILTER (WHERE metric.type = 'STORAGE_AMOUNT')\n  ]) AS \"Utilization\",\n  unnest(array[\n    avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS'),\n    min(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS'),\n    max(metric.current) FILTER (WHERE metric.type = 'STORAGE_ACCESS')\n  ]) AS \"IOPS\",\n  unnest(array[\n    avg(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY'),\n    min(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY'),\n    max(metric.current) FILTER (WHERE metric.type = 'STORAGE_LATENCY')\n    ]) AS \"Latency\"\nFROM metric\nJOIN entity as e on\n  e.type = 'STORAGE'\n  and e.oid = metric.entity_oid\nWHERE\n  metric.time BETWEEN timestamptz $__timeFrom() AND $__timeTo()\n  AND ($__timeFrom(),$__timeTo()) OVERLAPS (e.first_seen, e.last_seen)\n  AND e.oid = ${Datastore:raw} + 0\nORDER BY \"order\" asc\n"
    }
   ]
  },
  {
   "title": "Virtual Machine Summary",
   "type": "table",
   "description": "Storage used, average and max IOPS and latency for VMs consuming resources from datastore.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH sub AS (\n  SELECT\n      m.entity_oid as oid,\n      e.name as name,\n      m.type as type,\n      m.consumed as value\n  FROM\n      metric m\n  JOIN scope s ON\n      m.entity_oid = s.scoped_oid\n      AND m.time BETWEEN s.start AND s.finish\n  JOIN entity e ON\n      m.entity_oid = e.oid\n  WHERE\n      -- fixed conditions\n      m.type in ('STORAGE_LATENCY','STORAGE_ACCESS','STORAGE_AMOUNT')\n      AND s.scoped_type = 'VIRTUAL_MACHINE'\n      -- conditions involving dashboard vars\n      AND m.time BETWEEN timestamptz $__timeFrom() AND $__timeTo()\n      AND ($__timeFrom(),$__timeTo()) OVERLAPS (s.start, s.finish)\n      AND s.seed_oid = ${Datastore:raw} + 0\n  GROUP BY m.time, m.entity_oid, e.name, m.type, m.consumed\n)\nSELECT\n    max(sub.name) as \"VM Name\",\n    max(sub.value) FILTER (WHERE sub.type = 'STORAGE_AMOUNT') AS \"Storage Used\",\n    avg(sub.value) FILTER (WHERE sub.type = 'STORAGE_ACCESS') AS \"Avg IOPS\",\n    max(sub.value) FILTER (WHERE sub.type = 'STORAGE_ACCESS') AS \"Max IOPS\",\n    avg(sub.value) FILTER (WHERE sub.type = 'STORAGE_LATENCY') AS \"Avg Latency\",\n    max(sub.value) FILTER (WHERE sub.type = 'STORAGE_LATENCY') AS \"Max Latency\"\nFROM sub\nGROUP BY sub.oid"
    }
   ]
  },
  {
   "title": "Wasted Files on Datastore",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  path as \"File Path\",\n  file_size_kb as \"File Size\",\n  modification_time as \"Last Modified Time\"\nFROM wasted_file\nWHERE storage_oid = ${Datastore:raw} + 0\nORDER BY 2 DESC"
    }
   ]
  }
 ]
}