{
 "title": "SLO Daily Violations Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "metric_type",
    "label": "Metric Type",
    "query": "SELECT unnest(enum_range(NULL::metric_type))::text"
   },
   {
    "name": "desired_factor",
    "label": "Target Utilization",
    "query": "SELECT generate_series || '%' as __text, generate_series*.01 as __value FROM generate_series(10,100,10)"
   },
   { "name": "ma_days", "label": "Moving Avg Days", "query": "3,7,14,30" }
  ]
 },
 "panels": [
  {
   "title": "Environment Out of Compliance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT day as time\n      ,error as \"Daily Error\"\n      ,AVG(error) OVER (ORDER BY day ROWS BETWEEN $ma_days - 1 PRECEDING AND CURRENT ROW) as \"Moving Error\"\nFROM\n     (SELECT DATE_TRUNC('day', time) as day\n            ,SUM(CASE WHEN current - capacity*$desired_factor > 0\n                      THEN current - capacity*$desired_factor\n                      ELSE 0\n                 END) / SUM((1-$desired_factor)*capacity) as error\n        FROM metric\n       WHERE type = ${metric_type:singlequote}\n         AND $__timeFilter(time)\n         AND consumed is NULL\n       GROUP BY 1) as data"
    }
   ]
  },
  {
   "title": "Actions by State per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', completion_time) as time\n      ,count(DISTINCT action_oid) FILTER (where final_state = 'FAILED') as \"Failed\"\n      ,count(DISTINCT action_oid) FILTER (where final_state = 'SUCCEEDED') as \"Successful\"\n  FROM completed_action\n WHERE $__timeFilter(completion_time)\n   AND final_state in ('SUCCEEDED', 'FAILED')\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Successful Actions by Type per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', completion_time) as time\n      ,count(DISTINCT action_oid) FILTER (where type = 'MOVE') as \"MOVE\"\n      ,count(DISTINCT action_oid) FILTER (where type = 'PROVISION') as \"PROVISION\"\n      ,count(DISTINCT action_oid) FILTER (where type = 'RESIZE') as \"RESIZE\"\n      ,count(DISTINCT action_oid) FILTER (where type = 'DEACTIVATE') as \"DEACTIVATE\"\n  FROM completed_action\n WHERE $__timeFilter(completion_time)\n   AND final_state = 'SUCCEEDED'\n GROUP BY 1"
    }
   ]
  }
 ]
}