{
 "title": "Physical Machine Utilization Day over Day by Hour",
 "description": "This dashboard compares average hourly utilization measurements for physical machines (aka hosts) day-over-day for the two consecutive days. All physical machines in the selected group are included in the averages.",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "SELECT name as __text,\n       oid as __value\nFROM entity\nWHERE entity.type = 'GROUP'\nAND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\nAND attrs -> 'member_types' ? 'PHYSICAL_MACHINE'\nGROUP BY name, oid\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Physical Machine Avg Memory Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average Memory utilization for physical machines",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n    SELECT\n      m.time,\n      m.utilization AS avg_util\n    FROM metric m\n    JOIN scope s ON s.scoped_oid = m.entity_oid\n        AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (start, finish)\n        AND m.time BETWEEN s.\"start\" AND s.finish\n    WHERE\n      s.scoped_type ='PHYSICAL_MACHINE'\n      AND m.type = 'MEM'\n      AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR')\n      AND date_trunc('HOUR', $__timeTo()::TIMESTAMPTZ)\n      AND s.seed_oid IN (SELECT * FROM unnest(ARRAY[ $Group ]::bigint[]))\n      --Remove duplicate joins on metric and scope table\n      GROUP BY m.time, m.utilization, m.entity_oid\n)\nSELECT\n    INTERVAL '1 HOUR' + CASE\n      WHEN time BETWEEN date_trunc('hour', $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND\n      date_trunc('hour', $__timeTo()::TIMESTAMPTZ - interval '24 HOUR')\n        THEN date_trunc('HOUR', time + interval '24 HOUR')\n      ELSE date_trunc('HOUR', time)\n    END as \"time\",\n    CASE\n      WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR'\n          AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR'\n        THEN 'Previous Day'\n      ELSE 'Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n    END as metric,\n    avg(avg_util)\nFROM\n    data\nGROUP\n    BY 1, 2\nORDER BY\n    1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg CPU Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average CPU utilization for physical machines",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n    SELECT\n      m.time,\n      m.utilization AS avg_util\n    FROM metric m\n    JOIN scope s ON s.scoped_oid = m.entity_oid\n        AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (start, finish)\n        AND m.time BETWEEN s.\"start\" AND s.finish\n    WHERE\n      s.scoped_type = 'PHYSICAL_MACHINE'\n      AND m.type = 'CPU'\n      AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR')\n      AND date_trunc('HOUR', $__timeTo()::TIMESTAMPTZ)\n      AND s.seed_oid IN (SELECT * FROM unnest(ARRAY[ $Group ]::bigint[]))\n      --Remove duplicate joins on metric and scope table\n      GROUP BY m.time, m.utilization, m.entity_oid\n)\nSELECT\n    INTERVAL '1 HOUR' + CASE\n      WHEN time BETWEEN date_trunc('hour', $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND\n      date_trunc('hour', $__timeTo()::TIMESTAMPTZ - interval '24 HOUR')\n        THEN date_trunc('HOUR', time + interval '24 HOUR')\n      ELSE date_trunc('HOUR', time)\n    END as \"time\",\n    CASE\n      WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR'\n          AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR'\n        THEN 'Previous Day'\n      ELSE 'Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n    END as metric,\n    avg(avg_util)\nFROM\n    data\nGROUP\n    BY 1, 2\nORDER BY\n    1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Ballooning Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average Ballooning utilization for physical machines",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n    SELECT\n      m.time,\n      m.utilization AS avg_util\n    FROM metric m\n    JOIN scope s ON s.scoped_oid = m.entity_oid\n        AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (start, finish)\n        AND m.time BETWEEN s.start AND s.finish\n    WHERE\n      s.scoped_type = 'PHYSICAL_MACHINE'\n      AND m.type = 'BALLOONING'\n      AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR')\n      AND date_trunc('HOUR', $__timeTo()::TIMESTAMPTZ)\n      AND s.seed_oid IN (SELECT * FROM unnest(ARRAY[ $Group ]::bigint[]))\n      --Remove duplicate joins on metric and scope table\n      GROUP BY m.time, m.utilization, m.entity_oid\n)\nSELECT\n    INTERVAL '1 HOUR' + CASE\n      WHEN time BETWEEN date_trunc('hour', $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND\n      date_trunc('hour', $__timeTo()::TIMESTAMPTZ - interval '24 HOUR')\n        THEN date_trunc('HOUR', time + interval '24 HOUR')\n      ELSE date_trunc('HOUR', time)\n    END as \"time\",\n    CASE\n      WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR'\n          AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR'\n        THEN 'Previous Day'\n      ELSE 'Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n    END as metric,\n    avg(avg_util)\nFROM\n    data\nGROUP\n    BY 1, 2\nORDER BY\n    1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Swapping Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average Swapping utilization for physical machines",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n    SELECT\n      m.time,\n      m.utilization AS avg_util\n    FROM metric m\n    JOIN scope s ON s.scoped_oid = m.entity_oid\n        AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (start, finish)\n        AND m.time BETWEEN s.start AND s.finish\n    WHERE\n      s.scoped_type = 'PHYSICAL_MACHINE'\n      AND m.type = 'SWAPPING'\n      AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR')\n      AND date_trunc('HOUR', $__timeTo()::TIMESTAMPTZ)\n      AND s.seed_oid IN (SELECT * FROM unnest(ARRAY[ $Group ]::bigint[]))\n      --Remove duplicate joins on metric and scope table\n      GROUP BY m.time, m.utilization, m.entity_oid\n)\nSELECT\n    INTERVAL '1 HOUR' + CASE\n      WHEN time BETWEEN date_trunc('hour', $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND\n      date_trunc('hour', $__timeTo()::TIMESTAMPTZ - interval '24 HOUR')\n        THEN date_trunc('HOUR', time + interval '24 HOUR')\n      ELSE date_trunc('HOUR', time)\n    END as \"time\",\n    CASE\n      WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR'\n          AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR'\n        THEN 'Previous Day'\n      ELSE 'Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n    END as metric,\n    avg(avg_util)\nFROM\n    data\nGROUP\n    BY 1, 2\nORDER BY\n    1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg IO Throughput Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average IO Throughput utilization for physical machines",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n    SELECT\n      m.time,\n      m.utilization AS avg_util\n    FROM metric m\n    JOIN scope s ON s.scoped_oid = m.entity_oid\n        AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (start, finish)\n        AND m.time BETWEEN s.start AND s.finish\n    WHERE\n      s.scoped_type = 'PHYSICAL_MACHINE'\n      AND m.type = 'IO_THROUGHPUT'\n      AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR')\n      AND date_trunc('HOUR', $__timeTo()::TIMESTAMPTZ)\n      AND s.seed_oid IN (SELECT * FROM unnest(ARRAY[ $Group ]::bigint[]))\n      --Remove duplicate joins on metric and scope table\n      GROUP BY m.time, m.utilization, m.entity_oid\n)\nSELECT\n    INTERVAL '1 HOUR' + CASE\n      WHEN time BETWEEN date_trunc('hour', $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND\n      date_trunc('hour', $__timeTo()::TIMESTAMPTZ - interval '24 HOUR')\n        THEN date_trunc('HOUR', time + interval '24 HOUR')\n      ELSE date_trunc('HOUR', time)\n    END as \"time\",\n    CASE\n      WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR'\n          AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR'\n        THEN 'Previous Day'\n      ELSE 'Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n    END as metric,\n    avg(avg_util)\nFROM\n    data\nGROUP\n    BY 1, 2\nORDER BY\n    1"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Net Throughput Utilization - Day over Day by Hour",
   "type": "graph",
   "description": "Average Net Throughout utilization for physical machines",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH data as (\n    SELECT\n      m.time,\n      m.utilization AS avg_util\n    FROM metric m\n    JOIN scope s ON s.scoped_oid = m.entity_oid\n        AND ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR', $__timeTo()::TIMESTAMPTZ) OVERLAPS (start, finish)\n        AND m.time BETWEEN s.\"start\" AND s.finish\n    WHERE\n      s.scoped_type = 'PHYSICAL_MACHINE'\n      AND m.type = 'NET_THROUGHPUT'\n      AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '24 HOUR')\n      AND date_trunc('HOUR', $__timeTo()::TIMESTAMPTZ)\n      AND s.seed_oid IN (SELECT * FROM unnest(ARRAY[ $Group ]::bigint[]))\n      --Remove duplicate joins on metric and scope table\n      GROUP BY m.time, m.utilization, m.entity_oid\n)\nSELECT\n    INTERVAL '1 HOUR' + CASE\n      WHEN time BETWEEN date_trunc('hour', $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR') AND\n      date_trunc('hour', $__timeTo()::TIMESTAMPTZ - interval '24 HOUR')\n        THEN date_trunc('HOUR', time + interval '24 HOUR')\n      ELSE date_trunc('HOUR', time)\n    END as \"time\",\n    CASE\n      WHEN time BETWEEN $__timeFrom()::TIMESTAMPTZ - interval '24 HOUR'\n          AND $__timeTo()::TIMESTAMPTZ - interval '24 HOUR'\n        THEN 'Previous Day'\n      ELSE 'Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n    END as metric,\n    avg(avg_util)\nFROM\n    data\nGROUP\n    BY 1, 2\nORDER BY\n    1"
    }
   ]
  }
 ]
}