{
 "title": "Physical Machine Utilization Week over Week by Day",
 "description": "This dashboard compares average daily utilization measurements for physical machines (aka hosts) week-over-week for two consecutive weeks. All physical machines in the selected group are included in the averages.",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "query": "SELECT name as __text,\n       oid as __value\nFROM entity\nWHERE entity.type = 'GROUP'\nAND ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\nAND attrs -> 'member_types' ? 'PHYSICAL_MACHINE'\nGROUP BY name, oid\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Physical Machine Avg Memory Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average memory utilization for physical machines",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics AS (\n  SELECT m.time, m.utilization\n    FROM metric m,\n    scope_to($__timeFrom()::timestamptz - INTERVAL '7 day', $__timeTo(), 'PHYSICAL_MACHINE', ARRAY[${Group}]::bigint[], '${Group:raw}' = '0') s\n    WHERE\n      m.entity_oid = s.oid\n      AND m.time BETWEEN s.from_time AND s.to_time\n      AND m.type = 'MEM'\n      AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n    GROUP BY m.time, m.entity_oid, m.utilization\n),\nDATA AS (\n  SELECT m.time, avg(m.utilization) AS avg_util\n  FROM metrics m\n  GROUP BY m.time\n)\nSELECT\n  INTERVAL '1 DAY' + CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN date_trunc('day', time + interval '7 day')\n    ELSE date_trunc('day', time)\n  END as \"time\",\n  CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN 'Previous Week'\n    ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n  END as metric,\n  avg(avg_util)\nFROM data\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg CPU Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average CPU utilization by physical machine",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics AS (\n  SELECT m.time, m.utilization\n  FROM metric m,\n    scope_to($__timeFrom()::timestamptz - INTERVAL '7 day', $__timeTo(), 'PHYSICAL_MACHINE', ARRAY[${Group}]::bigint[], '${Group:raw}' = '0') s\n  WHERE\n    m.entity_oid = s.oid AND m.time BETWEEN s.from_time AND s.to_time\n    AND m.type = 'CPU'\n    AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n  GROUP BY m.time, m.entity_oid, m.utilization\n),\nDATA AS (\n  SELECT\n    m.time,\n    avg(m.utilization) AS avg_util\n  FROM metrics m\n  GROUP BY m.time\n)\nSELECT\n  INTERVAL '1 DAY' + CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN date_trunc('day', time + interval '7 day')\n      ELSE date_trunc('day', time)\n  END as \"time\",\n  CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN 'Previous Week'\n    ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n  END as metric,\n  avg(avg_util)\nFROM data\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Ballooning Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average Ballooning utilization by physical machines",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics AS (\n  SELECT m.time, m.utilization\n  FROM metric m,\n    scope_to($__timeFrom()::timestamptz - INTERVAL '7 day', $__timeTo(), 'PHYSICAL_MACHINE', ARRAY[${Group}]::bigint[], '${Group:raw}' = '0') s\n  WHERE\n    m.entity_oid = s.oid\n    AND m.time BETWEEN s.from_time AND s.to_time\n    AND m.type = 'BALLOONING'\n    AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n  GROUP BY m.time, m.entity_oid, m.utilization\n),\nDATA AS (\n  SELECT\n    m.time,\n    avg(m.utilization) AS avg_util\n  FROM metrics m\n  GROUP BY m.time\n)\nSELECT\n  INTERVAL '1 DAY' + CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN date_trunc('day', time + interval '7 day')\n    ELSE date_trunc('day', time)\n  END as \"time\",\n  CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN 'Previous Week'\n    ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n  END as metric,\n  avg(avg_util)\nFROM data\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Swapping Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average Swapping utilization by physical machines",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics AS (\n  SELECT m.time, m.utilization\n  FROM metric m,\n    scope_to($__timeFrom()::timestamptz - INTERVAL '7 day', $__timeTo(), 'PHYSICAL_MACHINE', ARRAY[${Group}]::bigint[], '${Group:raw}' = '0') s\n  WHERE\n    m.entity_oid = s.oid\n    AND m.type = 'SWAPPING'\n    AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n  GROUP BY m.time, m.entity_oid, m.utilization\n),\nDATA AS (\n  SELECT\n    m.time,\n    avg(m.utilization) AS avg_util\n  FROM metrics m\n  GROUP BY m.time\n)\nSELECT\n  INTERVAL '1 DAY' + CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN date_trunc('day', time + interval '7 day')\n    ELSE date_trunc('day', time)\n  END as \"time\",\n  CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN 'Previous Week'\n    ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n  END as metric,\n  avg(avg_util)\nFROM data\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg IO Throughput Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average IO Throughput utilization by physical machine",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics AS (\n  SELECT m.time, m.utilization\n  FROM metric m,\n    scope_to($__timeFrom()::timestamptz - INTERVAL '7 day', $__timeTo(), 'PHYSICAL_MACHINE', ARRAY[${Group}]::bigint[], '${Group:raw}' = '0') s\n  WHERE\n    m.entity_oid = s.oid\n    AND m.time BETWEEN s.from_time AND s.to_time\n    AND m.type = 'IO_THROUGHPUT'\n    AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n  GROUP BY m.time, m.entity_oid, m.utilization\n),\nDATA AS (\n  SELECT\n    m.time,\n    avg(m.utilization) AS avg_util\n  FROM metrics m\n  GROUP BY m.time\n)\nSELECT\n  INTERVAL '1 DAY' + CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN date_trunc('day', time + interval '7 day')\n    ELSE date_trunc('day', time)\n  END as \"time\",\n  CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN 'Previous Week'\n    ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n  END as metric,\n  avg(avg_util)\nFROM data\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Physical Machine Avg Net Throughput Utilization - Week over Week by Day",
   "type": "graph",
   "description": "Average Net Throughput utilization by physical machines",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH metrics AS (\n  SELECT m.time, m.utilization\n  FROM metric m,\n    scope_to($__timeFrom()::timestamptz - INTERVAL '7 day', $__timeTo(), 'PHYSICAL_MACHINE', ARRAY[${Group}]::bigint[], '${Group:raw}' = '0') s\n  WHERE\n    m.entity_oid = s.oid\n    AND m.type = 'NET_THROUGHPUT'\n    AND m.time BETWEEN ($__timeFrom()::TIMESTAMPTZ - interval '7 day') AND date_trunc('day', $__timeTo()::TIMESTAMPTZ)\n  GROUP BY m.time, m.entity_oid, m.utilization\n),\nDATA AS (\n  SELECT\n    m.time,\n    avg(m.utilization) AS avg_util\n  FROM metrics m\n  GROUP BY m.time\n)\nSELECT\n  INTERVAL '1 DAY' + CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN date_trunc('day', time + interval '7 day')\n    ELSE date_trunc('day', time)\n  END as \"time\",\n  CASE\n    WHEN time BETWEEN date_trunc('day', $__timeFrom()::TIMESTAMPTZ - interval '7 day')\n      AND date_trunc('day', $__timeTo()::TIMESTAMPTZ - interval '7 day')\n    THEN 'Previous Week'\n    ELSE 'Week Ending ' || DATE($__timeTo()::TIMESTAMPTZ)::TEXT\n  END as metric,\n  avg(avg_util)\nFROM data\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  }
 ]
}