{
 "title": "Wasted Storage Files",
 "description": "This dashboard displays information on data stores organized by wasted storage amounts. Wasted amounts are those that are allocated on a data store, and occupy space, but are not associated with a virtual machine.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Datastore",
    "query": "SELECT DISTINCT storage_name as __text,\n       storage_oid as __value\nFROM wasted_file\nORDER BY storage_name"
   },
   {
    "name": "MinFileSize",
    "query": "SELECT  col || ' MB' as __text,\n                row as __value\nFROM (\n        VALUES (0,0),\n                   (1,1024)\n        ) AS q (col, row)\nUNION\nSELECT generate_series || ' MB' as __text,\n       generate_series*1024 as __value\n  FROM generate_series(10,100,10)\n ORDER BY __value"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Wasted Amount Per Datastore",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() as time,\n       storage_name as \"Datastore\",\n       SUM(file_size_kb) as \"Wasted Storage Amount\"\n  FROM wasted_file\n WHERE ARRAY[storage_oid]::text[] && Array[$Datastore]::text[]\n   AND (file_size_kb >= $MinFileSize OR $MinFileSize = 0)\n GROUP BY 1, 2\n ORDER BY 3 DESC"
    }
   ]
  },
  {
   "title": "Total Wasted Storage Per Datastore",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "rawSql": "SELECT storage_name as \"Datastore\",\n       SUM(file_size_kb) as \"Wasted Storage Amount\",\n       COUNT(file_size_kb) as \"Wasted File Count\"\n  FROM wasted_file\n WHERE ARRAY[storage_oid]::text[] && Array[$Datastore]::text[]\n   AND (file_size_kb >= $MinFileSize OR $MinFileSize = 0)\n GROUP BY storage_oid, storage_name\n ORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Wasted File Count Per Datastore",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() as time,\n       storage_name as \"Datastore\",\n       COUNT(*) as \"Wasted File Count\"\n  FROM wasted_file\n WHERE ARRAY[storage_oid]::text[] && Array[$Datastore]::text[]\n   AND (file_size_kb >= $MinFileSize OR $MinFileSize = 0)\n GROUP BY 1, storage_oid, storage_name\n ORDER BY 3 DESC"
    }
   ]
  },
  {
   "title": "Caution",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "options": {
    "content": "<p style=\"text-align: center; color: red; background-color: white\">\nThe information in this report is correct as of the time the\ndata was collected. The data can be up to one day older than the date\nof report generation. Before you delete files based on this report,\nverify that the files are indeed unused.</p>"
   }
  },
  {
   "title": "Individual Wasted Files",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT storage_name as \"Datastore\",\n       path as \"File Path\",\n       coalesce(file_size_kb::text, '-') as \"File Size\",\n       coalesce(to_char(modification_time, 'DD-MON-YYYY HH24:MI:SS TZH:TZM'), '-') as \"Last Modified Time\"\n  FROM wasted_file\n WHERE (file_size_kb >= $MinFileSize OR $MinFileSize = 0)\n   AND ARRAY[storage_oid]::text[] && Array[$Datastore]::text[]\n ORDER BY 3 DESC"
    }
   ]
  }
 ]
}