/*
** Add new supported entity types to EntityType enum
*/

ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'CONTAINER_SPEC';
ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'NAMESPACE';
ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'VIRTUAL_DATACENTER';
ALTER TYPE entity_type ADD VALUE IF NOT EXISTS 'WORKLOAD_CONTROLLER';
