package com.vmturbo.market.runner;

/**
 * Modes for how to run the market.
 * Used in Analysis.execute().
 */
public enum MarketMode {
    /**
     *  only run M2 to generate all actions.
     */
    M2Only,
    /**
     * only run SMA to generate cloud VM scale actions.  All other actions are generated by M2.
     */
    SMAOnly,
    /**
     * run M2 to generate all actions and run SMA only to dump SMA actions to log file.
     * This mode will dump both M2 and SMA cloud VM scale actions to the log file in CSV format.
     */
    M2withSMAActions;

    /**
     * Given a String, return the MarketMode enumerated type.  Default is M2Only.
     * @param value string
     * @return MarketMode enumerated type
     */
    public static MarketMode fromString(String value) {
        for (MarketMode mode: MarketMode.values()) {
            if (mode.name().equalsIgnoreCase(value)) {
                return mode;
            }
        }
        return M2Only;
    }

    /**
     * Is SMA enabled either as SMAOnly or as M2withSMAActions?
     * @param mode MarketMode
     * @return true if SMA is enabled, else false.
     */
    public static boolean isEnableSMA(MarketMode mode) {
        return mode == SMAOnly || mode == M2withSMAActions;
    }
}
