package com.vmturbo.market.cloudvmscaling.entities;

import java.util.List;
import java.util.Objects;

import javax.annotation.Nonnull;

/**
 * The Stable Marriage algorithm output context.
 * The output context contains a list of matches for this context
 */
public class SMAOutputContext {
    /**
     * base context.
     */
    private final SMAContext context;

    /**
     * This is the result of running SMA.
     */
    private List<SMAMatch> matches;

    /**
     * Constructor for output context.
     * @param context Each SMAOutputContext is associated with a context.
     * @param matches The matches generated by SMA.
     */
    public SMAOutputContext(final SMAContext context,
                            @Nonnull final List<SMAMatch> matches) {
        this.context = context;
        this.matches = Objects.requireNonNull(matches, "matches are null!");
    }

    @Nonnull
    public SMAContext getContext() {
        return context;
    }

    @Nonnull
    public List<SMAMatch> getMatches() {
        return matches;
    }

    @Override
    public String toString() {
        return "SMAOutputContext{" +
                "context=" + context +
                ", matches=" + matches.size() +
                '}';
    }

}
