{
 "title": "A/B Performance Comparison",
 "description": "Compare performance of dashboard query implementations",
 "time": { "from": "2020-01-01T05:00:00.000Z", "to": "2020-06-02T03:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "trial",
    "label": "trial",
    "query": "SELECT DISTINCT trial FROM grafana"
   },
   {
    "name": "a_label",
    "label": "\"A\" label",
    "query": "SELECT DISTINCT label FROM grafana"
   },
   {
    "name": "b_label",
    "label": "\"B\" label",
    "query": "SELECT DISTINCT label FROM grafana"
   },
   { "name": "dashboard", "query": "select dashboard from grafana" },
   { "name": "type", "label": "Query Type ", "query": "select query_type from grafana" },
   {
    "name": "name",
    "label": "Panel or Var Name",
    "query": "SELECT DISTINCT name FROM grafana where dashboard = any( array[ $dashboard ] ::text[]) and query_type = any ( array [ $type ]::text[] )"
   },
   {
    "name": "all",
    "label": "Var Values",
    "query": "All Values,Explicit Values,Either"
   }
  ]
 },
 "panels": [
  {
   "title": "Query time ratio - $b_label / $a_label",
   "type": "graph",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    {}
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp '2019-12-31T05:00Z' + (b.end_time - b.start_time) as \"time\",\n  b.label || ': ' || b.dashboard || '/' || b.name || case when coalesce(b.all_variable,True) then '[ALL]' else '' end as metric,\n  b.execution_time/a.execution_time\nFROM\n  grafana as b, grafana as a\nwhere\n  a.trial = b.trial\n  AND a.dashboard = b.dashboard\n  AND a.query_type = b.query_type\n  AND a.name = b.name\n  AND a.all_variable = b.all_variable\n  AND a.interval = b.interval\n  AND b.trial = $trial\n  AND b.label = '$b_label' AND a.label='$a_label'\n  AND b.dashboard = any( array[ $dashboard ] )\n  and b.query_type = any( array[ $type ] )\n  and b.name = any( array [ $name ] )\n  and ('$all' = 'Either' OR ('$all' = 'All Values') = b.all_variable)\norder by 1\n"
    }
   ]
  },
  {
   "title": "Performance Overview - A: $a_label vs. B: $b_label",
   "type": "table",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  a.id as \"A id\", b.id as \"B id\",\n  $__time(a.time),\n  a.trial,\n  a.label as \"A label\",\n  b.label as \"B label\",\n  (a.end_time - a.start_time)::interval as interval,\n  extract('epoch' from (a.end_time - a.start_time)::interval) as interval_secs,\n  a.execution_time AS \"A Time\",\n  b.execution_time AS \"B Time\",\n  b.execution_time / a.execution_time AS \"B/A ratio\",\n  a.dashboard,\n  a.query_type,\n  a.name,\n  a.all_variable,\n  a.variable\nFROM\n  grafana as a full outer join grafana as b\nON\n  a.trial = b.trial\n  AND a.dashboard = b.dashboard\n  AND a.query_type = b.query_type\n  AND a.name = b.name\n  AND a.all_variable = b.all_variable\n  AND a.interval = b.interval\nwhere\n  a.trial = $trial\n  AND a.label = '$a_label'\n  AND b.label = '$b_label'\n  AND a.dashboard = any( array[ $dashboard ] )\n  and a.query_type = any( array[ $type ] )\n  and a.name = any( array [ $name ] )\n  and ('$all' = 'Either' OR ('$all' = 'All Values') = a.all_variable)\n  ORDER BY a.dashboard, a.query_type, a.name, a.interval::interval\n"
    }
   ]
  },
  {
   "title": "Query time by interval - $a_label",
   "type": "graph",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp '2019-12-31T05:00Z' + (end_time - start_time) as \"time\",\n  label || ': ' || dashboard || '/' || name || case when coalesce(all_variable,True) then '[ALL]' else '' end as metric,\n  execution_time\nFROM\n  grafana\nwhere\n  trial = $trial\n  AND label = '$a_label'\n  AND dashboard = any( array[ $dashboard ] )\n  and query_type = any( array[ $type ] )\n  and name = any( array [ $name ] )\n  and ('$all' = 'Either' OR ('$all' = 'All Values') = all_variable)\norder by 1\n\n"
    }
   ]
  },
  {
   "title": "Query time by interval - $b_label",
   "type": "graph",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp '2019-12-31T05:00Z' + (end_time - start_time) as \"time\",\n  label || ': ' || dashboard || '/' || name || case when coalesce(all_variable,True) then '[ALL]' else '' end as metric,\n  execution_time\nFROM\n  grafana\nwhere\n  trial = $trial\n  AND label = '$b_label'\n  AND dashboard = any( array[ $dashboard ] )\n  and query_type = any( array[ $type ] )\n  and name = any( array [ $name ] )\n  and ('$all' = 'Either' OR ('$all' = 'All Values') = all_variable)\norder by 1\n\n"
    }
   ]
  }
 ]
}