apiVersion: 1
datasources:
# datasource used by embedded reporting dashboards to access reporting data
- name: Turbo Timescale
  url: '${HOST}:${PORT}'
  orgId: 1
  type: postgres
  access: proxy
  database: ${DATABASE}
  user: ${USER}
  basicAuth: false
  isDefault: true
  jsonData:
    sslmode: disable
    postgresVersion: 1200
    timescaledb: true
  secureJsonData:
    password: ${PASSWORD}
