package com.vmturbo.topology.processor.probes;

import com.vmturbo.platform.sdk.common.MediationMessage.ProbeInfo;

/**
 * An interface to be implemented by classes that wish to receive events
 * generated by the {@link ProbeStore}.
 */
public interface ProbeStoreListener {
    /**
     * A callback to be called when a probe has been registered with the {@link ProbeStore}.
     * Note that probe registration occurs in the communication transport thread context,
     * so these callbacks should quickly return control to the caller.
     *
     * @param probeId The ID of the probe that was registered.
     * @param probe The info for the probe that was registered with the {@link ProbeStore}.
     */
    void onProbeRegistered(long probeId, ProbeInfo probe);
}
