package com.vmturbo.topology.processor.targets;

import javax.annotation.Nonnull;

/**
 * An interface to be implemented by classes that wish to receive events generated by the
 * {@link TargetStore}.
 */
public interface TargetStoreListener {
    /**
     * A callback to be called when a target has been successfully added to the {@link TargetStore}.
     *
     * @param target The target that was added to the {@link TargetStore}.
     */
    default void onTargetAdded(@Nonnull final Target target) { }

    /**
     * A callback to be called when a target has been successfully removed from the
     * {@link TargetStore}.
     *
     * @param target The target that was removed from the {@link TargetStore}.
     */
    default void onTargetRemoved(@Nonnull final Target target) { }

    /**
     * A callback to be called when a target has been successfully updated in the
     * {@link TargetStore}.
     *
     * @param target The target hat was updated (new version) in the {@link TargetStore}
     */
    default void onTargetUpdated(@Nonnull final Target target) { }
}
