package com.vmturbo.cost.component.savings;

import java.util.concurrent.atomic.AtomicBoolean;

import javax.annotation.Nonnull;

import com.vmturbo.cost.component.savings.DataInjectionMonitor.ScriptEvent;

/**
 * Script event injection support.
 */
public interface ScenarioDataInjector {
    /**
     * Get the script event class.
     *
     * @return the script event class
     */
    Class getScriptEventClass();

    /**
     * Convert a script event to a SavingsEvent and add it to the journal.
     *
     * @param event event generated by the script
     * @param uuid resolved UUID of target of event
     * @param purgePreviousTestState true if the stats and entity for the entities in the UUID list
     */
    void handleScriptEvent(@Nonnull ScriptEvent event, @Nonnull Long uuid,
            @Nonnull AtomicBoolean purgePreviousTestState);
}
