{
 "title": "Cloud Summary",
 "tags": [
  "cloud",
  "actions"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "debug : Failed, prod : Succeeded"
   }
  ]
 },
 "panels": [
  { "title": "Achieved Savings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily Savings by Action Type (Estimated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n      ts_reduce_area(\r\n        ts_sum(\r\n        ts_reduce_avg(\r\n        ts_mask(\r\n          to_timerange(\r\n            e.end_time, \r\n            ${__to:date:seconds}\r\n          )) * -1 * cast(e.tags ->> '$.cost.delta' as decimal) / 3600, '1h'))\r\n          , '24h')\r\n        ,\r\n    e.tags ->> '$.type'\r\n  )\r\nFROM\r\n  events as e  \r\nWHERE\r\n  e.tags ->> '$.state' = ${environment:sqlstring}\r\n  and e.tags ->> '$.cost.delta' is not null     \r\nGroup by e.tags ->> '$.type'\r\n"
    }
   ]
  },
  {
   "title": "Cumulative Savings (Estimated)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_accum(\r\n      ts_reduce_area(\r\n        ts_sum(\r\n        ts_reduce_avg(\r\n        ts_mask(\r\n          to_timerange(\r\n            e.end_time, \r\n            ${__to:date:seconds}\r\n          )) * -1 * cast(e.tags ->> '$.cost.delta' as decimal) / 3600, '1h'))\r\n          , '24h'))\r\n        ,\r\n    e.tags ->> '$.type'\r\n  )\r\nFROM\r\n  events as e  \r\nWHERE\r\n  e.tags ->> '$.state' = ${environment:sqlstring}\r\n  and e.tags ->> '$.cost.delta' is not null     \r\nGroup by e.tags ->> '$.type'\r\n"
    }
   ]
  },
  {
   "title": "Savings by Subscription (Projected)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_reduce_avg(\r\n    ts_sum(\r\n    (      \r\n        ts_mask(\r\n          to_timerange(\r\n            e.end_time, \r\n            ${__to:date:seconds}\r\n        )\r\n      ) * -730 * cast(e.tags ->> '$.cost.delta' as decimal)\r\n    )), '24h'), \r\n      t.sub_name\r\n  )\r\nFROM\r\n  events as e  \r\n   inner join (\r\n    SELECT\r\n      e.xid as xid,\r\n      ba.name as sub_name\r\n    FROM\r\n       GRAPH('(ba:BusinessAccount)-[:owns]->(e:Entity)')      \r\n  ) t on e.tags -> '$.associated_xid' = t.xid\r\nWHERE\r\n  e.tags ->> '$.state' = ${environment:sqlstring} and\r\n  e.tags ->> '$.cost.delta' IS not NULL\r\nGROUP BY t.sub_name\r\n  "
    }
   ]
  },
  {
   "title": "Savings by Entity Type (Projected)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "USD/Month" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_sum(\r\n    (\r\n        ts_mask(\r\n          to_timerange(\r\n            e.end_time, \r\n            ${__to:date:seconds}\r\n        )\r\n      ) * -730 * cast(e.tags ->> '$.cost.delta' as decimal)\r\n    )), \r\n   t.entity_type\r\n  )\r\nFROM\r\n  events as e  \r\n   inner join (\r\n    SELECT\r\n      x.xid as xid,\r\n      x.entity_type as entity_type\r\n    FROM\r\n      GRAPH('(x:Entity)')    \r\n  ) t on e.tags -> '$.associated_xid' = t.xid\r\nWHERE\r\n  e.tags ->> '$.state' = ${environment:sqlstring} and\r\n   e.tags ->> '$.cost.delta' IS not NULL\r\nGROUP BY t.entity_type"
    }
   ]
  },
  {
   "title": "Pending Actions and Potential Savings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Action Count by Entity Type (Projected)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT  \r\n    relabel(\r\n      ts_reduce_max(\r\n    ts_sum(\r\n    (      \r\n        ts_mask(\r\n          to_timerange(\r\n            e.start_time, \r\n            e.end_time\r\n        )\r\n      )\r\n    )), '24h'), \r\n    concat(t.entity_type,' - ',e.tags ->> '$.type')\r\n  )\r\n  \r\nFROM\r\n  events as e\r\n  inner join (\r\n    SELECT\r\n      x.xid as xid,\r\n      x.entity_type as entity_type\r\n    FROM\r\n      GRAPH('(x:Entity)')    \r\n  ) t on e.tags -> '$.associated_xid' = t.xid\r\nWHERE\r\n  e.tags ->> '$.state' = 'Ready'\r\n  and e.tags ->> '$.cost.delta' IS not NULL\r\nGROUP BY t.entity_type\r\n  "
    }
   ]
  },
  {
   "title": "Potential Savings By Type (Projected)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "USD/month" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_sum(\r\n    (\r\n      ts_reduce_max(\r\n        ts_mask(\r\n          to_timerange(\r\n            e.start_time, \r\n            e.end_time\r\n        )\r\n      ), '1h') * -730 * cast(e.tags ->> '$.cost.delta' as decimal)\r\n    )), \r\n   concat(t.entity_type,' ',e.tags ->> '$.type')\r\n  )\r\nFROM\r\n  events as e  \r\n   inner join (\r\n    SELECT\r\n      x.xid as xid,\r\n      x.entity_type as entity_type\r\n    FROM\r\n      GRAPH('(x:Entity)')    \r\n  ) t on e.tags ->> '$.associated_xid' = t.xid\r\nWHERE\r\n  e.tags ->> '$.state' = 'Ready'\r\n  and e.tags ->> '$.cost.delta' IS not NULL\r\nGROUP BY e.tags ->> '$.type'\r\n  \r\n\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Pending Actions by Subscription",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\r\n  e.tags ->> '$.description' as Description,\r\n  e.tags -> '$.cost.delta' as Savings\r\nFROM\r\n  events as e\r\nWHERE\r\n  e.tags ->> '$.state' = 'Ready'\r\n  and e.tags ->> '$.cost.delta' is not null\r\nand end_time > 0 OR tags ->> '$.last_seen' < ${__from:date:seconds}\r\nORDER BY Savings DESC\r\nLIMIT 10"
    }
   ]
  },
  { "title": "Missed Savings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Daily Missed Savings by Action Type (Estimated)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n      ts_reduce_area(\r\n        ts_sum(\r\n        ts_reduce_avg(\r\n        ts_mask(\r\n          to_timerange(\r\n            e.start_time, \r\n            e.end_time\r\n          )) * -1 * cast(e.tags ->> '$.cost.delta' as decimal) / 3600, '1h'))\r\n          , '24h')\r\n        ,\r\n    e.tags ->> '$.type'\r\n  )\r\nFROM\r\n  events as e  \r\nWHERE\r\n  e.tags ->> '$.state' = 'Ready'\r\n  and e.tags ->> '$.cost.delta' is not null     \r\nGroup by e.tags ->> '$.type'\r\n"
    }
   ]
  },
  {
   "title": "Cumulative Missed Savings (Estimated)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_accum(\r\n      ts_reduce_area(\r\n        ts_sum(\r\n        ts_reduce_avg(\r\n        ts_mask(\r\n          to_timerange(\r\n            e.start_time, \r\n            e.end_time\r\n          )) * -1 * cast(e.tags ->> '$.cost.delta' as decimal) / 3600, '1h'))\r\n          , '24h'))\r\n        ,\r\n    e.tags ->> '$.type'\r\n  )\r\nFROM\r\n  events as e  \r\nWHERE\r\n  e.tags ->> '$.state' = 'Ready'\r\n  and e.tags ->> '$.cost.delta' is not null     \r\nGroup by e.tags ->> '$.type'\r\n"
    }
   ]
  },
  { "title": "All Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "All Actions",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "queryText": "SELECT \nfrom_unix_timestamp(start_time) as 'Time First Recommended', \nfrom_unix_timestamp(end_time) as 'End Time', \ntags ->> '$.type' as Type,\nif(tags ->> '$.state' = ${environment:sqlstring}, 'Succeeded', tags ->> '$.state')  as State,\ntags ->> '$.cost.delta' as 'Cost Delta (USD/hour)',\ntags ->> '$.description' as Description\nfrom events \nwhere tags ->> '$.cost.delta' IS NOT NULL\norder by 'End Time' DESC"
    }
   ]
  }
 ]
}