{
 "title": "On-Prem Summary (Review Version)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cost_per_gb", "label": "Cost Per RAM GB ($)", "query": "15" },
   { "name": "cost_per_core", "label": "Cost Per CPU Core ($)", "query": "10" },
   { "name": "cost_per_tb", "label": "Cost Per Storage TB ($)", "query": "100" },
   {
    "name": "environment",
    "query": "debug : Failed, prod : Succeeded"
   }
  ]
 },
 "panels": [
  { "title": "Impact and Show Back", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VPU and Memory Savings Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "select\r\n  ts_sum(\r\n    relabel(\r\n      ts_upsample(\r\n        ts_mask(\r\n          to_timerange(\r\n            end_time, \r\n            end_time\r\n            )\r\n          ) *-1 * cast(coalesce(tags ->> '$.commodity_deltas.Virtual Memory', tags ->> '$.commodity_deltas.Virtual CPU') as decimal), '24h'),\r\n        IF(tags ->> '$.commodity_deltas.Virtual Memory' IS NOT NULL, 'Virtual Memory', 'Virtual CPU'))),\r\n  IF(tags ->> '$.commodity_deltas.Virtual Memory' IS NOT NULL, 'Virtual Memory', 'Virtual CPU') as 'Delta Type'\r\nFROM\r\n  events\r\nWHERE\r\n  tags ->> '$.type' = 'Resize'\r\n  and tags ->> '$.state' in (${environment:sqlstring})\r\n  and NOT (\r\n    tags ->> '$.commodity_deltas.Virtual CPU' IS NULL AND tags ->> '$.commodity_deltas.Virtual Memory' IS NULL\r\n  )  \r\nGROUP BY IF(tags ->> '$.commodity_deltas.Virtual Memory' IS NOT NULL, 'Virtual Memory', 'Virtual CPU')"
    }
   ]
  },
  {
   "title": "Executed Resizes & Showback",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT\r\n      t.cluster as Cluster,\r\n      t.name as VM,\r\n      e.tags ->> '$.description' as Description,\r\n      IF(e.tags ->> '$.commodity_deltas.Virtual Memory' is not null, (e.tags ->> '$.commodity_deltas.Virtual Memory' / (1024*1024)) * ${cost_per_gb:sqlstring}, 0 ) as 'VMem Cost',\r\n      IF(e.tags ->> '$.commodity_deltas.Virtual CPU' is not null, (e.tags ->> '$.commodity_deltas.Virtual CPU') * ${cost_per_core:sqlstring}, 0 ) as 'VCPU Cost'\r\n  FROM\r\n      events as e\r\n  inner join (\r\n      SELECT\r\n        vm.xid as xid,\r\n        clus.name as cluster,\r\n        vm.name as name\r\n      FROM\r\n        GRAPH('(clus:Cluster)-[:has_member]->(pm:PhysicalMachine)-[:supports]->(vm:VirtualMachine)')\r\n  ) t on e.tags ->> '$.associated_xid' = t.xid\r\nWHERE\r\n  e.tags ->> '$.type' = 'Resize' and\r\n  e.tags ->> '$.state' in (${environment:sqlstring})\r\n"
    }
   ]
  },
  {
   "title": "Actions Executed & Labor Hours Saved",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "queryText": "select \r\n    e.tags ->> '$.category' as Category,\r\n    e.tags ->> '$.type' as Type,   \r\n    count(e.tags ->> '$.description') as 'Number of Actions',\r\n    count(e.tags ->> '$.description') * 10 as 'Labor Saved (hrs)'\r\nfrom \r\n    events as e\r\nwhere\r\n    e.tags ->> '$.state' in (${environment:sqlstring})\r\n    and e.tags ->> '$.cost.delta' is NULL\r\nGroup by category, type"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Action Executed by Category",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select \r\n   relabel(ts_upsample(ts_mask(to_timerange(e.end_time, e.end_time)), '24h'),CONCAT_WS(', ', e.tags ->> '$.type', e.tags ->> '$.category'))\r\nfrom \r\n    events as e\r\nwhere\r\n    e.end_time > 0\r\n    and e.tags ->> '$.state' in (${environment:sqlstring})\r\n    and e.tags ->> '$.cost.delta' is NULL"
    }
   ]
  },
  {
   "title": "Action Executed by Risk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select \r\n    --CONCAT_WS(' , ', e.tags ->> '$.type', e.tags ->> '$.category') as category,\r\n    --count(e.tags ->> '$.description') as count\r\n   \r\n    relabel(\r\n        ts_reduce_max(\r\n            ts_mask(\r\n                to_timerange(\r\n                    e.end_time, \r\n                    e.end_time\r\n                )\r\n            ), \r\n            '24h'\r\n        ), \r\n        CONCAT_WS(' , ', e.tags ->> '$.type', e.tags ->> '$.triggering_commodities[0]')\r\n    )\r\nfrom \r\n    events as e\r\nwhere\r\n    e.end_time > 0\r\n        and e.tags ->> '$.state' in (${environment:sqlstring})\r\n    and e.tags ->> '$.cost.delta' is NULL"
    }
   ]
  },
  {
   "title": "Pending Actions By Type & Category",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \r\n    relabel(\r\n        ts_sum(\r\n            ts_upsample(\r\n                ts_mask(\r\n                    to_timerange(\r\n                        e.start_time, \r\n                        e.end_time\r\n                    )\r\n                ), \r\n                '24h'\r\n            )\r\n        ), \r\n        CONCAT_WS(\r\n            ', ',\r\n            e.tags ->> '$.type',\r\n            e.tags ->> '$.category'\r\n        )\r\n    )\r\nfrom \r\n    events as e\r\nwhere\r\n    e.tags ->> '$.state' = 'Ready'\r\n    and end_time > 0 \r\nGroup By e.tags ->> '$.type', e.tags ->> '$.category'\r\n"
    }
   ]
  },
  {
   "title": "Pending Actions By Type & Risk",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select     \r\n    relabel(\r\n        ts_sum(\r\n            ts_upsample(\r\n                ts_mask(\r\n                    to_timerange(\r\n                        e.start_time, \r\n                        e.end_time\r\n                    )\r\n                ), \r\n                '24h'\r\n            )\r\n        ), \r\n        CONCAT_WS(\r\n            ', ',\r\n            e.tags ->> '$.type',\r\n            e.tags ->> '$.triggering_commodities[0]'\r\n        )\r\n    )\r\nfrom \r\n    events as e\r\nwhere\r\n    e.tags ->> '$.state' = 'Ready'\r\n    and end_time > 0 and e.tags ->> '$.triggering_commodities[0]' is NOT NULL\r\nGroup By e.tags ->> '$.type', e.tags ->> '$.triggering_commodities[0]'\r\n"
    }
   ]
  },
  { "title": "Wasted Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": " Wasted Storage Details",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "queryText": "SELECT\r\n  SUBSTRING_INDEX(SUBSTRING_INDEX(e.tags ->> '$.description',\"Storage\",-1),\"to\",1) AS 'Datastore',\r\n  COUNT(e.tags ->> '$.type') as 'Delete Action Count',\r\n  SUM(e.tags ->> '$.commodity_deltas.Storage Amount' * -1) as 'Wasted_Storage',\r\n  SUM(e.tags ->> '$.commodity_deltas.Storage Amount') * -1 * ${cost_per_tb}/1000/1000 as Savings\r\nFROM\r\n  events as e\r\nWHERE\r\n  e.tags ->> '$.type' = 'Delete'\r\n  and e.tags ->> '$.state' = 'Ready'\r\n  and e.tags ->> '$.description' LIKE '%wasted%'\r\nGROUP BY Datastore\r\nORDER BY 'Wasted_Storage'"
    }
   ]
  },
  {
   "title": " Wasted Storage Details with filename",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "queryText": "SELECT\r\n  SUBSTRING_INDEX(SUBSTRING_INDEX(e.tags ->> '$.description',\"Storage\",-1),\"to\",1) AS 'Datastore',\r\n  SUBSTRING_INDEX(SUBSTRING_INDEX(e.tags ->> '$.description',\"'\",2),\"'\",-1) AS 'File Name',\r\n  (e.tags ->> '$.commodity_deltas.Storage Amount' * -1) as 'Wasted_Storage',\r\n  (e.tags ->> '$.commodity_deltas.Storage Amount') * -1 * ${cost_per_tb}/1000/1000 as Savings\r\nFROM\r\n  events as e\r\nWHERE\r\n  e.tags ->> '$.type' = 'Delete'\r\n  and e.tags ->> '$.state' = 'Ready'\r\n  and e.tags ->> '$.description' LIKE '%wasted%'\r\nORDER BY Savings DESC"
    }
   ]
  },
  {
   "title": "Delete Actions by Size",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "queryText": "SELECT\r\n  CONCAT(CONCAT_WS(' - ', \r\n  SUBSTRING_INDEX(SUBSTRING_INDEX(e.tags ->> '$.description',\"Storage\",-1),\"to\",1), \r\n  SUBSTRING_INDEX(SUBSTRING_INDEX(e.tags ->> '$.description',\"'\",2),\"'\",-1),(e.tags ->> '$.commodity_deltas.Storage Amount' * -1/1000)),' GB') AS text,\r\n  (e.tags ->> '$.commodity_deltas.Storage Amount' * -1) as 'Wasted_Storage'\r\nFROM\r\n  events as e\r\nWHERE\r\n  e.tags ->> '$.type' = 'Delete'\r\n  and e.tags ->> '$.state' = 'Ready'\r\n  and e.tags ->> '$.description' LIKE '%wasted%'\r\nORDER BY 'Wasted Storage' DESC\r\nLIMIT 36"
    }
   ]
  }
 ]
}