# Create and Scale Volume to different storage types.
# This is only an example, in practice it may not be possible to scale down from ULTRA.
start 8-28 0:00
6 11:00 create-vol vol-1 volume_type=ULTRA storage_access=2000,0.7 storage_amount=5,0.8 io_throughput=7,9.1
7 10:00 resize-vol vol-1 volume_type=ULTRA storage_access=3000,0.9 storage_amount=40,1.7 io_throughput=6,3.1
8 10:00 resize-vol vol-1 volume_type=PREMIUM storage_amount=80,2.0
9 14:00 resize-vol vol-1 volume_type=STANDARDHDD storage_amount=20,1.0
10 15:00 stop