package com.vmturbo.mediation.conversion.util;

import com.vmturbo.platform.sdk.common.util.SDKProbeType;

/**
 * Hardcoded Cloud services. These CSs are created in aws/azure wrapper probe,
 * which are used to set up the owns relationship from cloud service and tiers.
 * We should follow the following rule:
 * for each new CS, its Id should be inserted in "Title" case format.
 */
public enum CloudService {

    AWS_EBS("aws::CS::EBS", "AWS EBS", SDKProbeType.AWS), // pjs: EBS doesn't seem to come in as
    AWS_A4B("aws::CS::A4B", "AWS A4B", SDKProbeType.AWS),
    AWS_AMPLIFY("aws::CS::AWSAmplify", "AWS Amplify", SDKProbeType.AWS),
    AWS_BACKUP("aws::CS::AWSBackup", "AWS Backup", SDKProbeType.AWS),
    AWS_BUDGETS("aws::CS::AWSBudgets", "AWS Budgets", SDKProbeType.AWS),
    AWS_CERTIFICATE_MANAGER("aws::CS::AWSCertificateManager", "AWS Certificate Manager", SDKProbeType.AWS),
    AWS_CLOUD_TRAIL("aws::CS::AWSCloudTrail", "AWS Cloud Trail", SDKProbeType.AWS),
    AWS_CODE_COMMIT("aws::CS::AWSCodeCommit", "AWS Code Commit", SDKProbeType.AWS),
    AWS_CODE_PIPELINE("aws::CS::AWSCodePipeline", "AWS Code Pipeline", SDKProbeType.AWS),
    AWS_CONFIG("aws::CS::AWSConfig", "AWS Config", SDKProbeType.AWS),
    AWS_COST_EXPLORER("aws::CS::AWSCostExplorer", "AWS Cost Explorer", SDKProbeType.AWS),
    AWS_DATA_TRANSFER("aws::CS::AWSDataTransfer", "AWS Data Transfer", SDKProbeType.AWS),
    AWS_DATABASE_MIGRATION_SVC("aws::CS::AWSDatabaseMigrationSvc", "AWS Database Migration Svc", SDKProbeType.AWS),
    AWS_DEVELOPER_SUPPORT("aws::CS::AWSDeveloperSupport", "AWS Developer Support", SDKProbeType.AWS),
    AWS_DIRECT_CONNECT("aws::CS::AWSDirectConnect", "AWS Direct Connect", SDKProbeType.AWS),
    AWS_DIRECTORY_SERVICE("aws::CS::AWSDirectoryService", "AWS Directory Service", SDKProbeType.AWS),
    AWS_ELEMENTAL_MEDIA_STORE("aws::CS::AWSElementalMediaStore", "AWS Elemental MediaStore", SDKProbeType.AWS),
    AWS_EVENTS("aws::CS::AWSEvents", "AWS Events", SDKProbeType.AWS),
    AWS_GLOBAL_ACCELERATOR("aws::CS::AWSGlobalAccelerator", "AWS Global Accelerator", SDKProbeType.AWS),
    AWS_GLUE("aws::CS::AWSGlue", "AWS Glue", SDKProbeType.AWS),
    AWS_IOT("aws::CS::AWSIoT", "AWS IoT", SDKProbeType.AWS),
    AWS_LAMBDA("aws::CS::AWSLambda", "AWS Lambda", SDKProbeType.AWS),
    AWS_QUEUE_SERVICE("aws::CS::AWSQueueService", "AWS Queue Service", SDKProbeType.AWS),
    AWS_SECRETS_MANAGER("aws::CS::AWSSecretsManager", "AWS Secrets Manager", SDKProbeType.AWS),
    AWS_SECURITY_HUB("aws::CS::AWSSecurityHub", "AWS Security Hub", SDKProbeType.AWS),
    AWS_SERVICE_CATALOG("aws::CS::AWSServiceCatalog", "AWS Service Catalog", SDKProbeType.AWS),
    AWS_STORAGE_GATEWAY("aws::CS::AWSStorageGateway", "AWS Storage Gateway", SDKProbeType.AWS),
    AWS_SUPPORT_BUSINESS("aws::CS::AWSSupportBusiness", "AWS Support Business", SDKProbeType.AWS),
    AWS_SYSTEMS_MANAGER("aws::CS::AWSSystemsManager", "AWS Systems Manager", SDKProbeType.AWS),
    AWS_TRANSFER("aws::CS::AWSTransfer", "AWS Transfer", SDKProbeType.AWS),
    AWS_X_RAY("aws::CS::AWSXRay", "AWS X Ray", SDKProbeType.AWS),
    AWS_ALEXA_WEB_INFO_SERVICE("aws::CS::AlexaWebInfoService", "Alexa Web Info Service", SDKProbeType.AWS),
    AWS_API_GATEWAY("aws::CS::AmazonApiGateway", "Amazon Api Gateway", SDKProbeType.AWS),
    AWS_APP_STREAM("aws::CS::AmazonAppStream", "Amazon App Stream", SDKProbeType.AWS),
    AWS_ATHENA("aws::CS::AmazonAthena", "Amazon Athena", SDKProbeType.AWS),
    AWS_CLOUD_FRONT("aws::CS::AmazonCloudFront", "Amazon Cloud Front", SDKProbeType.AWS),
    AWS_CLOUD_SEARCH("aws::CS::AmazonCloudSearch", "Amazon Cloud Search", SDKProbeType.AWS),
    AWS_CLOUD_WATCH("aws::CS::AmazonCloudWatch", "Amazon Cloud Watch", SDKProbeType.AWS),
    AWS_COGNITO("aws::CS::AmazonCognito", "Amazon Cognito", SDKProbeType.AWS),
    AWS_CONNECT("aws::CS::AmazonConnect", "Amazon Connect", SDKProbeType.AWS),
    AWS_DAX("aws::CS::AmazonDAX", "Amazon DAX", SDKProbeType.AWS),
    AWS_DOC_DB("aws::CS::AmazonDocDB", "Amazon Doc DB", SDKProbeType.AWS),
    AWS_DYNAMO_DB("aws::CS::AmazonDynamoDB", "Amazon Dynamo DB", SDKProbeType.AWS),
    AWS_EC2("aws::CS::AmazonEC2", "Amazon EC2", SDKProbeType.AWS),
    AWS_ECR("aws::CS::AmazonECR", "Amazon ECR", SDKProbeType.AWS),
    AWS_ECS("aws::CS::AmazonECS", "Amazon ECS", SDKProbeType.AWS),
    AWS_EFS("aws::CS::AmazonEFS", "Amazon EFS", SDKProbeType.AWS),
    AWS_EKS("aws::CS::AmazonEKS", "Amazon EKS", SDKProbeType.AWS),
    AWS_ES("aws::CS::AmazonES", "Amazon ES", SDKProbeType.AWS),
    AWS_ETS("aws::CS::AmazonETS", "Amazon ETS", SDKProbeType.AWS),
    AWS_ELASTIC_CACHE("aws::CS::AmazonElastiCache", "Amazon Elasti Cache", SDKProbeType.AWS),
    AWS_FSX("aws::CS::AmazonFSx", "Amazon FSx", SDKProbeType.AWS),
    AWS_GLACIER("aws::CS::AmazonGlacier", "Amazon Glacier", SDKProbeType.AWS),
    AWS_GUARD_DUTY("aws::CS::AmazonGuardDuty", "Amazon Guard Duty", SDKProbeType.AWS),
    AWS_INSPECTOR("aws::CS::AmazonInspector", "Amazon Inspector", SDKProbeType.AWS),
    AWS_KINESIS("aws::CS::AmazonKinesis", "Amazon Kinesis", SDKProbeType.AWS),
    AWS_KINESIS_ANALYTICS("aws::CS::AmazonKinesisAnalytics", "Amazon Kinesis Analytics", SDKProbeType.AWS),
    AWS_KINESIS_FIREHOSE("aws::CS::AmazonKinesisFirehose", "Amazon Kinesis Firehose", SDKProbeType.AWS),
    AWS_LEX("aws::CS::AmazonLex", "Amazon Lex", SDKProbeType.AWS),
    AWS_LIGHTSAIL("aws::CS::AmazonLightsail", "Amazon Lightsail", SDKProbeType.AWS),
    AWS_ML("aws::CS::AmazonML", "Amazon ML", SDKProbeType.AWS),
    AWS_MQ("aws::CS::AmazonMQ", "Amazon MQ", SDKProbeType.AWS),
    AWS_MSK("aws::CS::AmazonMSK", "Amazon MSK", SDKProbeType.AWS),
    AWS_MACIE("aws::CS::AmazonMacie", "Amazon Macie", SDKProbeType.AWS),
    AWS_MANAGED_BLOCKCHAIN("aws::CS::AmazonManagedBlockchain", "Amazon Managed Blockchain", SDKProbeType.AWS),
    AWS_NEPTUNE("aws::CS::AmazonNeptune", "Amazon Neptune", SDKProbeType.AWS),
    AWS_POLLY("aws::CS::AmazonPolly", "Amazon Polly", SDKProbeType.AWS),
    AWS_QLDB("aws::CS::AmazonQLDB", "Amazon QLDB", SDKProbeType.AWS),
    AWS_QUICK_SIGHT("aws::CS::AmazonQuickSight", "Amazon Quick Sight", SDKProbeType.AWS),
    AWS_RDS("aws::CS::AmazonRDS", "Amazon RDS", SDKProbeType.AWS),
    AWS_REDSHIFT("aws::CS::AmazonRedshift", "Amazon Redshift", SDKProbeType.AWS),
    AWS_REGISTRAR("aws::CS::AmazonRegistrar", "Amazon Registrar", SDKProbeType.AWS),
    AWS_REKOGNITION("aws::CS::AmazonRekognition", "Amazon Rekognition", SDKProbeType.AWS),
    AWS_ROUTE53("aws::CS::AmazonRoute53", "Amazon Route53", SDKProbeType.AWS),
    // an actual service in the cloud data. But keeping for
    // now since we prob. can't assume all storage tiers are S3
    AWS_S3("aws::CS::AmazonS3", "Amazon S3", SDKProbeType.AWS),
    AWS_S3_GLACIER_DEEP_ARCHIVE("aws::CS::AmazonS3GlacierDeepArchive", "Amazon S3 Glacier Deep Archive", SDKProbeType.AWS),
    AWS_SES("aws::CS::AmazonSES", "Amazon SES", SDKProbeType.AWS),
    AWS_SNS("aws::CS::AmazonSNS", "Amazon SNS", SDKProbeType.AWS),
    AWS_SWF("aws::CS::AmazonSWF", "Amazon SWF", SDKProbeType.AWS),
    AWS_SAGE_MAKER("aws::CS::AmazonSageMaker", "Amazon Sage Maker", SDKProbeType.AWS),
    AWS_SIMPLE_DB("aws::CS::AmazonSimpleDB", "Amazon Simple DB", SDKProbeType.AWS),
    AWS_STATES("aws::CS::AmazonStates", "Amazon States", SDKProbeType.AWS),
    AWS_SUMERIAN("aws::CS::AmazonSumerian", "Amazon Sumerian", SDKProbeType.AWS),
    AWS_TEXTRACT("aws::CS::AmazonTextract", "Amazon Textract", SDKProbeType.AWS),
    AWS_VPC("aws::CS::AmazonVPC", "Amazon VPC", SDKProbeType.AWS),
    AWS_WAM("aws::CS::AmazonWAM", "Amazon WAM", SDKProbeType.AWS),
    AWS_WORK_DOCS("aws::CS::AmazonWorkDocs", "Amazon Work Docs", SDKProbeType.AWS),
    AWS_WORK_MAIL("aws::CS::AmazonWorkMail", "Amazon Work Mail", SDKProbeType.AWS),
    AWS_WORK_SPACES("aws::CS::AmazonWorkSpaces", "Amazon Work Spaces", SDKProbeType.AWS),
    AWS_CLOUD_HSM("aws::CS::CloudHSM", "AWS Cloud HSM", SDKProbeType.AWS),
    AWS_CODE_BUILD("aws::CS::CodeBuild", "AWS Code Build", SDKProbeType.AWS),
    AWS_CONTACT_CENTER_TELECOMM("aws::CS::ContactCenterTelecomm", "AWS Contact Center Telecomm", SDKProbeType.AWS),
    AWS_ELASTIC_MAP_REDUCE("aws::CS::ElasticMapReduce", "AWS Elastic Map Reduce", SDKProbeType.AWS),
    AWS_OPS_WORKS("aws::CS::OpsWorks", "AWS Ops Works", SDKProbeType.AWS),
    AWS_SNOWBALL_EXTRA_DAYS("aws::CS::SnowballExtraDays", "AWS Snowball Extra Days", SDKProbeType.AWS),
    AWS_KMS("aws::CS::Awskms", "AWS Key Management Service", SDKProbeType.AWS),
    AWS_WAF("aws::CS::Awswaf", "AWS Web Application Firewall", SDKProbeType.AWS),
    AWS_COMPREHEND("aws::CS::Comprehend", "Amazon Comprehend", SDKProbeType.AWS),
    AWS_COMPREHEND_MEDICAL("aws::CS::Comprehendmedical", "Amazon Comprehend Medical", SDKProbeType.AWS),
    AWS_DATA_PIPELINE("aws::CS::Datapipeline", "AWS Data Pipeline", SDKProbeType.AWS),
    AWS_TRANSCRIBE("aws::CS::Transcribe", "Amazon Transcribe", SDKProbeType.AWS),
    AWS_MOBILE_ANALYTICS("aws::CS::Mobileanalytics", "Amazon Mobile Analytics", SDKProbeType.AWS),
    AWS_STORAGE_GATEWAY_DEEP_ARCHIVE("aws::CS::AWSStorageGatewayDeepArchive", "AWS Storage Gateway Deep Archive", SDKProbeType.AWS),
    AWS_INGESTION_SERVICE_SNOWBALL("aws::CS::IngestionServiceSnowball", "AWS Ingestion Service Snowball", SDKProbeType.AWS),
    AWS_IOT_DEVICE_DEFENDER("aws::CS::IoTDeviceDefender", "AWS IoT Device Defender", SDKProbeType.AWS),
    AWS_ELEMENTAL_MEDIA_PACKAGE("aws::CS::AWSElementalMediaPackage", "AWS Elemental Media Package", SDKProbeType.AWS),
    AWS_COGNITO_SYNC("aws::CS::AmazonCognitoSync", "Amazon Cognito Sync", SDKProbeType.AWS),
    AWS_IOT_1_CLICK("aws::CS::AWSIoT1Click", "AWS IoT 1 Click", SDKProbeType.AWS),
    AWS_CODE_GURU("aws::CS::CodeGuru", "AWS Code Guru", SDKProbeType.AWS),
    AWS_DEVICE_FARM("aws::CS::AWSDeviceFarm", "AWS Device Farm", SDKProbeType.AWS),
    AWS_INGESTION_SERVICE("aws::CS::IngestionService", "AWS Ingestion Service", SDKProbeType.AWS),
    AWS_GAME_LIFT("aws::CS::AmazonGameLift", "Amazon Game Lift", SDKProbeType.AWS),
    AWS_EI("aws::CS::AmazonEI", "Amazon EI", SDKProbeType.AWS),
    AWS_FORECAST("aws::CS::AmazonForecast", "Amazon Forecast", SDKProbeType.AWS),
    AWS_APP_SYNC("aws::CS::AWSAppSync", "AWS App Sync", SDKProbeType.AWS),
    AWS_IOT_DEVICE_MANAGEMENT("aws::CS::IoTDeviceManagement", "AWS IoT Device Management", SDKProbeType.AWS),
    AWS_DATA_EXCHANGE("aws::CS::AWSDataExchange", "AWS Data Exchange", SDKProbeType.AWS),
    AWS_WORK_LINK("aws::CS::AmazonWorkLink", "Amazon Work Link", SDKProbeType.AWS),
    AWS_CHIME_DIALIN("aws::CS::AmazonChimeDialin", "Amazon Chime Dialin", SDKProbeType.AWS),
    AWS_CHIME("aws::CS::AmazonChime", "Amazon Chime", SDKProbeType.AWS),
    AWS_IOT_EVENTS("aws::CS::AWSIoTEvents", "AWS IoT Events", SDKProbeType.AWS),
    AWS_TRANSLATE("aws::CS::Translate", "Amazon Translate", SDKProbeType.AWS),
    AWS_ROBO_MAKER("aws::CS::AWSRoboMaker", "AWS Robo Maker", SDKProbeType.AWS),
    AWS_ELEMENTAL_MEDIA_CONVERT("aws::CS::AWSElementalMediaConvert", "AWS Elemental Media Convert", SDKProbeType.AWS),
    AWS_IOT_THINGS_GRAPH("aws::CS::AWSIoTThingsGraph", "AWS IoT Things Graph", SDKProbeType.AWS),
    AWS_CHIME_CALL_ME("aws::CS::AmazonChimeCallMe", "Amazon Chime Call Me", SDKProbeType.AWS),
    AWS_KINESIS_VIDEO("aws::CS::AmazonKinesisVideo", "Amazon Kinesis Video", SDKProbeType.AWS),
    AWS_SUPPORT_ENTERPRISE("aws::CS::AWSSupportEnterprise", "AWS Support Enterprise", SDKProbeType.AWS),
    AWS_CLOUD_MAP("aws::CS::AWSCloudMap", "AWS Cloud Map", SDKProbeType.AWS),
    AWS_IOT_ANALYTICS("aws::CS::AWSIoTAnalytics", "AWS IoT Analytics", SDKProbeType.AWS),
    AWS_GREENGRASS("aws::CS::AWSGreengrass", "AWS Greengrass", SDKProbeType.AWS),
    AWS_DMS("aws::CS::AWSFMS", "AWS FMS", SDKProbeType.AWS),
    AWS_CODE_DEPLOY("aws::CS::AWSCodeDeploy", "AWS Code Deploy", SDKProbeType.AWS),
    AWS_ELEMENTAL_MEDIA_LIVE("aws::CS::AWSElementalMediaLive", "AWS Elemental MediaLive", SDKProbeType.AWS),
    AWS_SHIELD("aws::CS::AWSShield", "AWS Shield", SDKProbeType.AWS),
    AWS_DATA_SYNC("aws::CS::AWSDataSync", "AWS Data Sync", SDKProbeType.AWS),
    AWS_PINPOINT("aws::CS::AmazonPinpoint", "Amazon Pinpoint", SDKProbeType.AWS),
    AWS_MEDIA_CONNECT("aws::CS::AWSMediaConnect", "AWS Media Connect", SDKProbeType.AWS),
    AWS_CHIME_VOICE_CONNECTOR("aws::CS::AmazonChimeVoiceConnector", "Amazon Chime Voice Connector", SDKProbeType.AWS),
    AWS_ALEXA_TOP_SITES("aws::CS::AlexaTopSites", "Alexa Top Sites", SDKProbeType.AWS),
    AWS_CHIME_BUSINESS_CALLING("aws::CS::AmazonChimeBusinessCalling", "Amazon Chime Business Calling", SDKProbeType.AWS),
    AWS_ELEMENTAL_MEDIA_TAILOR("aws::CS::AWSElementalMediaTailor", "AWS Elemental Media Tailor", SDKProbeType.AWS),
    AWS_CLOUD_FORMATION("aws::CS::AWSCloudFormation", "AWS Cloud Formation", SDKProbeType.AWS),
    AWS_CLOUD_DIRECTORY("aws::CS::AmazonCloudDirectory", "Amazon Cloud Directory", SDKProbeType.AWS),


    AZURE_DATA_SERVICES("azure::CS::DataServices", "Azure Data Services", SDKProbeType.AZURE),
    AZURE_NETWORKING("azure::CS::Networking", "Azure Networking", SDKProbeType.AZURE),
    AZURE_IDENTITY("azure::CS::Identity", "Azure Identity", SDKProbeType.AZURE),
    AZURE_API_MANAGEMENT("azure::CS::APIManagement", "Azure API Management", SDKProbeType.AZURE),
    AZURE_ADVANCED_DATA_SECURITY("azure::CS::AdvancedDataSecurity", "Azure Advanced Data Security", SDKProbeType.AZURE),
    AZURE_ADVANCED_THREAT_PROTECTION("azure::CS::AdvancedThreatProtection", "Azure Advanced Threat Protection", SDKProbeType.AZURE),
    AZURE_APP_CENTER("azure::CS::AppCenter", "Azure App Center", SDKProbeType.AZURE),
    AZURE_APPLICATION_GATEWAY("azure::CS::ApplicationGateway", "Azure Application Gateway", SDKProbeType.AZURE),
    AZURE_APPLICATION_INSIGHTS("azure::CS::ApplicationInsights", "Azure Application Insights", SDKProbeType.AZURE),
    AZURE_AUTOMATION("azure::CS::Automation", "Azure Automation", SDKProbeType.AZURE),
    AZURE_ACTIVE_DIRECTORY_B2C("azure::CS::AzureActiveDirectoryB2C", "Azure Active Directory B2C", SDKProbeType.AZURE),
    AZURE_ACTIVE_DIRECTORY_DOMAIN_SERVICES("azure::CS::AzureActiveDirectoryDomainServices", "Azure Active Directory Domain Services", SDKProbeType.AZURE),
    AZURE_ANALYSIS_SERVICES("azure::CS::AzureAnalysisServices", "Azure Analysis Services", SDKProbeType.AZURE),
    AZURE_APP_SERVICE("azure::CS::AzureAppService", "Azure App Service", SDKProbeType.AZURE),
    AZURE_BASTION("azure::CS::AzureBastion", "Azure Bastion", SDKProbeType.AZURE),
    AZURE_BLOCKCHAIN("azure::CS::AzureBlockchain", "Azure Blockchain", SDKProbeType.AZURE),
    AZURE_BOT_SERVICE("azure::CS::AzureBotService", "Azure Bot Service", SDKProbeType.AZURE),
    AZURE_COSMOS_DB("azure::CS::AzureCosmosDB", "Azure Cosmos DB", SDKProbeType.AZURE),
    AZURE_DDOS_PROTECTION("azure::CS::AzureDDOSProtection", "Azure DDOS Protection", SDKProbeType.AZURE),
    AZURE_DNS("azure::CS::AzureDNS", "Azure DNS", SDKProbeType.AZURE),
    AZURE_DATA_EXPLORER("azure::CS::AzureDataExplorer", "Azure Data Explorer", SDKProbeType.AZURE),
    AZURE_DATA_FACTORY("azure::CS::AzureDataFactory", "Azure Data Factory", SDKProbeType.AZURE),
    AZURE_DATA_FACTORY_V2("azure::CS::AzureDataFactoryV2", "Azure Data Factory v2", SDKProbeType.AZURE),
    AZURE_DATA_SHARE("azure::CS::AzureDataShare", "Azure Data Share", SDKProbeType.AZURE),
    AZURE_DATABASE_MIGRATION_SERVICE("azure::CS::AzureDatabaseMigrationService", "Azure Database Migration Service", SDKProbeType.AZURE),
    AZURE_DATABASE_FOR_MARIADB("azure::CS::AzureDatabaseForMariaDB", "Azure Database for MariaDB", SDKProbeType.AZURE),
    AZURE_DATABASE_FOR_MYSQL("azure::CS::AzureDatabaseforMySQL", "Azure Database for MySQL", SDKProbeType.AZURE),
    AZURE_DATABASE_FOR_POSTGRESQL("azure::CS::AzureDatabaseForPostgreSQL", "Azure Database for PostgreSQL", SDKProbeType.AZURE),
    AZURE_DATABRICKS("azure::CS::AzureDatabricks", "Azure Databricks", SDKProbeType.AZURE),
    AZURE_DEVOPS("azure::CS::AzureDevOps", "Azure DevOps", SDKProbeType.AZURE),
    AZURE_FIREWALL("azure::CS::AzureFirewall", "Azure Firewall", SDKProbeType.AZURE),
    AZURE_FIREWALL_MANAGER("azure::CS::AzureFirewallManager", "Azure Firewall Manager", SDKProbeType.AZURE),
    AZURE_FRONT_DOOR_SERVICE("azure::CS::AzureFrontDoorService", "Azure Front Door Service", SDKProbeType.AZURE),
    AZURE_LAB_SERVICES("azure::CS::AzureLabServices", "Azure Lab Services", SDKProbeType.AZURE),
    AZURE_MACHINE_LEARNING("azure::CS::AzureMachineLearning", "Azure Machine Learning", SDKProbeType.AZURE),
    AZURE_MAPS("azure::CS::AzureMaps", "Azure Maps", SDKProbeType.AZURE),
    AZURE_MONITOR("azure::CS::AzureMonitor", "Azure Monitor", SDKProbeType.AZURE),
    AZURE_NETAPP_FILES("azure::CS::AzureNetAppFiles", "Azure NetApp Files", SDKProbeType.AZURE),
    AZURE_SEARCH("azure::CS::AzureSearch", "Azure Search", SDKProbeType.AZURE),
    AZURE_SITE_RECOVERY("azure::CS::AzureSiteRecovery", "Azure Site Recovery", SDKProbeType.AZURE),
    AZURE_SPRING_CLOUD("azure::CS::AzureSpringCloud", "Azure Spring Cloud", SDKProbeType.AZURE),
    AZURE_STACK("azure::CS::AzureStack", "Azure Stack", SDKProbeType.AZURE),
    AZURE_SYNTHETICS("azure::CS::AzureSynthetics", "Azure Synthetics", SDKProbeType.AZURE),
    AZURE_BACKUP("azure::CS::Backup", "Azure Backup", SDKProbeType.AZURE),
    AZURE_BANDWIDTH("azure::CS::Bandwidth", "Azure Bandwidth", SDKProbeType.AZURE),
    AZURE_BIZTALK_SERVICES("azure::CS::BizTalkServices", "Azure BizTalk Services", SDKProbeType.AZURE),
    AZURE_CLOUD_SERVICES("azure::CS::CloudServices", "Azure Cloud Services", SDKProbeType.AZURE),
    AZURE_COGNITIVE_SERVICES("azure::CS::CognitiveServices", "Azure Cognitive Services", SDKProbeType.AZURE),
    AZURE_CONTAINER_INSTANCES("azure::CS::ContainerInstances", "Azure Container Instances", SDKProbeType.AZURE),
    AZURE_CONTAINER_REGISTRY("azure::CS::ContainerRegistry", "Azure Container Registry", SDKProbeType.AZURE),
    AZURE_CONTENT_DELIVERY_NETWORK("azure::CS::ContentDeliveryNetwork", "Azure Content Delivery Network", SDKProbeType.AZURE),
    AZURE_COST_MANAGEMENT("azure::CS::CostManagement", "Azure Cost Management", SDKProbeType.AZURE),
    AZURE_DATA_BOX("azure::CS::DataBox", "Azure Data Box", SDKProbeType.AZURE),
    AZURE_DATA_CATALOG("azure::CS::DataCatalog", "Azure Data Catalog", SDKProbeType.AZURE),
    AZURE_DATA_LAKE_ANALYTICS("azure::CS::DataLakeAnalytics", "Azure Data Lake Analytics", SDKProbeType.AZURE),
    AZURE_DATA_LAKE_STORE("azure::CS::DataLakeStore", "Azure Data Lake Store", SDKProbeType.AZURE),
    AZURE_DATA_MANAGEMENT("azure::CS::DataManagement", "Azure Data Management", SDKProbeType.AZURE),
    AZURE_DATACENTER_CAPACITY("azure::CS::DatacenterCapacity", "Azure Datacenter Capacity", SDKProbeType.AZURE),
    AZURE_DIGITAL_TWINS("azure::CS::DigitalTwins", "Azure Digital Twins", SDKProbeType.AZURE),
    AZURE_DYNAMICS_365_FOR_CUSTOMER_INSIGHTS("azure::CS::Dynamics365ForCustomerInsights", "Dynamics 365 for Customer Insights", SDKProbeType.AZURE),
    AZURE_EVENT_GRID("azure::CS::EventGrid", "Azure Event Grid", SDKProbeType.AZURE),
    AZURE_EVENT_HUBS("azure::CS::EventHubs", "Azure Event Hubs", SDKProbeType.AZURE),
    AZURE_EXPRESSROUTE("azure::CS::ExpressRoute", "Azure ExpressRoute", SDKProbeType.AZURE),
    AZURE_FUNCTIONS("azure::CS::Functions", "Azure Functions", SDKProbeType.AZURE),
    AZURE_GITHUB("azure::CS::Github", "Azure GitHub", SDKProbeType.AZURE),
    AZURE_HDINSIGHT("azure::CS::HDInsight", "Azure HDInsight", SDKProbeType.AZURE),
    AZURE_HPCCACHE("azure::CS::HPCCache", "Azure HPCCache", SDKProbeType.AZURE),
    AZURE_INSIGHT_AND_ANALYTICS("azure::CS::InsightAndAnalytics", "Azure Insight and Analytics", SDKProbeType.AZURE),
    AZURE_IOT_CENTRAL("azure::CS::IoTCentral", "Azure IoT Central", SDKProbeType.AZURE),
    AZURE_IOT_HUB("azure::CS::IoTHub", "Azure IoT Hub", SDKProbeType.AZURE),
    AZURE_KEY_VAULT("azure::CS::KeyVault", "Azure Key Vault", SDKProbeType.AZURE),
    AZURE_KUSTO("azure::CS::Kusto", "Azure Kusto", SDKProbeType.AZURE),
    AZURE_LOAD_BALANCER("azure::CS::LoadBalancer", "Azure Load Balancer", SDKProbeType.AZURE),
    AZURE_LOG_ANALYTICS("azure::CS::LogAnalytics", "Azure Log Analytics", SDKProbeType.AZURE),
    AZURE_LOGIC_APPS("azure::CS::LogicApps", "Azure Logic Apps", SDKProbeType.AZURE),
    AZURE_MACHINE_LEARNING_SERVICE("azure::CS::MachineLearningService", "Azure Machine Learning Service", SDKProbeType.AZURE),
    AZURE_MACHINE_LEARNING_STUDIO("azure::CS::MachineLearningStudio", "Azure Machine Learning Studio", SDKProbeType.AZURE),
    AZURE_MEDIA_SERVICES("azure::CS::MediaServices", "Azure Media Services", SDKProbeType.AZURE),
    AZURE_MICROSOFT_AZURE_PEERING_SERVICE("azure::CS::MicrosoftAzurePeeringService", "Microsoft Azure Peering Service", SDKProbeType.AZURE),
    AZURE_MICROSOFT_GENOMICS("azure::CS::MicrosoftGenomics", "Microsoft Genomics", SDKProbeType.AZURE),
    AZURE_MIXED_REALITY("azure::CS::MixedReality", "Azure Mixed Reality", SDKProbeType.AZURE),
    AZURE_MULTI_FACTOR_AUTHENTICATION("azure::CS::Multi-FactorAuthentication", "Azure Multi-Factor Authentication", SDKProbeType.AZURE),
    AZURE_NAT_GATEWAY("azure::CS::NATGateway", "Azure NAT Gateway", SDKProbeType.AZURE),
    AZURE_NETWORK_WATCHER("azure::CS::NetworkWatcher", "Azure Network Watcher", SDKProbeType.AZURE),
    AZURE_NOTIFICATION_HUBS("azure::CS::NotificationHubs", "Azure Notification Hubs", SDKProbeType.AZURE),
    AZURE_PLAYFAB("azure::CS::PlayFab", "Azure PlayFab", SDKProbeType.AZURE),
    AZURE_POWER_BI("azure::CS::PowerBI", "Azure Power BI", SDKProbeType.AZURE),
    AZURE_POWER_BI_EMBEDDED("azure::CS::PowerBIEmbedded", "Azure Power BI Embedded", SDKProbeType.AZURE),
    AZURE_REDIS_CACHE("azure::CS::RedisCache", "Azure Redis Cache", SDKProbeType.AZURE),
    AZURE_RESERVATIONUSAGE("azure::CS::ReservationUsage", "Azure ReservationUsage", SDKProbeType.AZURE),
    AZURE_SQL_ADVANCED_THREAT_PROTECTION("azure::CS::SQLAdvancedThreatProtection", "Azure SQL Advanced Threat Protection", SDKProbeType.AZURE),
    AZURE_SQL_DB_EDGE("azure::CS::SQLDBEdge", "Azure SQL DB Edge", SDKProbeType.AZURE),
    AZURE_SQL_DATA_WAREHOUSE("azure::CS::SQLDataWarehouse", "Azure SQL Data Warehouse", SDKProbeType.AZURE),
    AZURE_SQL_DATABASE("azure::CS::SQLDatabase", "Azure SQL Database", SDKProbeType.AZURE),
    AZURE_SQL_SERVER_STRETCH_DATABASE("azure::CS::SQLServerStretchDatabase", "Azure SQL Server Stretch Database", SDKProbeType.AZURE),
    AZURE_SCHEDULER("azure::CS::Scheduler", "Azure Scheduler", SDKProbeType.AZURE),
    AZURE_SECURITY_CENTER("azure::CS::SecurityCenter", "Azure Security Center", SDKProbeType.AZURE),
    AZURE_SENTINEL("azure::CS::Sentinel", "Azure Sentinel", SDKProbeType.AZURE),
    AZURE_SERVICE_BUS("azure::CS::ServiceBus", "Azure Service Bus", SDKProbeType.AZURE),
    AZURE_SERVICE_FABRIC("azure::CS::ServiceFabric", "Azure Service Fabric", SDKProbeType.AZURE),
    AZURE_SERVICE_FABRIC_MESH("azure::CS::ServiceFabricMesh", "Azure Service Fabric Mesh", SDKProbeType.AZURE),
    AZURE_SIGNALR("azure::CS::SignalR", "Azure SignalR", SDKProbeType.AZURE),
    AZURE_SPATIAL_ANCHORS("azure::CS::SpatialAnchors", "Azure Spatial Anchors", SDKProbeType.AZURE),
    AZURE_SPECIALIZED_COMPUTE("azure::CS::SpecializedCompute", "Azure Specialized Compute", SDKProbeType.AZURE),
    AZURE_STORSIMPLE("azure::CS::StorSimple", "Azure StorSimple", SDKProbeType.AZURE),
    AZURE_STORAGE("azure::CS::Storage", "Azure Storage", SDKProbeType.AZURE),
    AZURE_STREAM_ANALYTICS("azure::CS::StreamAnalytics", "Azure Stream Analytics", SDKProbeType.AZURE),
    AZURE_TIME_SERIES_INSIGHTS("azure::CS::TimeSeriesInsights", "Azure Time Series Insights", SDKProbeType.AZURE),
    AZURE_TRAFFIC_MANAGER("azure::CS::TrafficManager", "Azure Traffic Manager", SDKProbeType.AZURE),
    AZURE_VNET_GATEWAY("azure::CS::VNetGateway", "Azure VNet Gateway", SDKProbeType.AZURE),
    AZURE_VPN_GATEWAY("azure::CS::VPNGateway", "Azure VPN Gateway", SDKProbeType.AZURE),
    AZURE_VIRTUAL_MACHINES("azure::CS::VirtualMachines", "Azure Virtual Machines", SDKProbeType.AZURE),
    AZURE_VIRTUAL_MACHINES_LICENSES("azure::CS::VirtualMachinesLicenses", "Azure Virtual Machines Licenses", SDKProbeType.AZURE),
    AZURE_VIRTUAL_NETWORK("azure::CS::VirtualNetwork", "Azure Virtual Network", SDKProbeType.AZURE),
    AZURE_VIRTUAL_WAN("azure::CS::VirtualWAN", "Azure Virtual WAN", SDKProbeType.AZURE),
    AZURE_VISUAL_STUDIO_ONLINE("azure::CS::VisualStudioOnline", "Visual Studio Online", SDKProbeType.AZURE),
    AZURE_VISUAL_STUDIO_SUBSCRIPTION("azure::CS::VisualStudioSubscription", "Visual Studio Subscription", SDKProbeType.AZURE),
    AZURE_WINDOWS_10_IOT_CORE_SERVICES("azure::CS::Windows10IoTCoreServices", "Windows 10 IoT Core Services", SDKProbeType.AZURE),
    AZURE_XAMARIN_UNIVERSITY("azure::CS::XamarinUniversity", "Azure Xamarin University", SDKProbeType.AZURE),


    GCP_STORAGE("gcp::CS::Storage", "GCP Storage", SDKProbeType.GCP),
    GCP_VIRTUAL_MACHINES("gcp::CS::VirtualMachines", "GCP VirtualMachines", SDKProbeType.GCP);

    private final String id;
    private final String displayName;
    private final SDKProbeType probeType;

    CloudService(String id, String displayName, SDKProbeType probeType) {
        this.id = id;
        this.displayName = displayName;
        this.probeType = probeType;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getId() {
        return id;
    }

    public SDKProbeType getProbeType() {
        return probeType;
    }
}
