{
 "title": "Daily Infrastructure Average Stats vs. Thresholds",
 "description": "This report shows daily average utilization measurements for the selected time range.. Averages are grouped into two sections. One rolled up for physical machines and another rolled up for virtual machines. Note that all physical and virtual machines are included. This information is useful as a top-level assessment of the overall average loading of your entire environment over time.",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Physical Infrastructure Utilization Metrics",
   "type": "graph",
   "description": "Average utilization for physical machines over selected time period.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select DATE(metric.\"time\") as \"time\", metric.\"type\" as metric, avg(utilization)\nFROM metric_old as metric, entity_old as entity\nwhere metric.entity_oid = entity.oid and\n      metric.entity_hash = entity.hash and\n      entity.\"type\" = 'PHYSICAL_MACHINE' and\n      provider_oid isnull and\n      $__timeFilter(\"time\") and\n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Legend",
   "type": "table",
   "description": "Percentage thresholds at which the color changes from Green to Yellow, and Yellow to Red",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT  *\nFROM    (\n        VALUES\n        (.2, .6, .3, .1, .2, .2, .03, .2, .6),\n        (.4, .8, .6, .25, .4, .4, .1, .4, .8)\n        ) AS q (\"CPU\", \"Mem\", \"Ballooning\", \"Swapping\", \"IO Throughput\", \"Net Throughput\", \"CPU Ready Q\", \"VCPU\", \"VMem\")"
    }
   ]
  },
  {
   "title": "Physical Machine Summary",
   "type": "table-old",
   "description": "Daily average for physical machines.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Virtual Infrastructure Utilization Metrics",
   "type": "graph",
   "description": "Average utilization for virtual machines over selected time period.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select DATE(metric.\"time\") as \"time\", metric.\"type\" as metric, avg(utilization)\nFROM metric_old as metric, entity_old as entity\nwhere metric.entity_oid = entity.oid and\n      metric.entity_hash = entity.hash and\n      entity.\"type\" = 'VIRTUAL_MACHINE' and\n      provider_oid isnull and\n      $__timeFilter(\"time\") and\n      ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen) and\n      entity.environment = 'ON_PREM'\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Virtual Machine Summary",
   "type": "table-old",
   "description": "Daily average for virtual machines.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "panelId": 3 }
   ]
  }
 ]
}