{
 "title": "Sample 1. VM Query Samples",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vmOnprem",
    "query": {}
   },
   {
    "name": "vmCloud",
    "query": {}
   },
   {
    "name": "vmAny",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# VMs\n\nThe following samples show how to query for VMs and their data using the data from Turbonomic ARM\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 3 },
   "options": {
    "content": "# List of VMs\n\n    SELECT \n      vm.oid, \n      vm.name \n    FROM \n      GRAPH('(vm:VirtualMachine)')        "
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 3 },
   "targets": [
    {
     "queryText": "SELECT \n  vm.oid, \n  vm.name \nFROM \n  GRAPH('(vm:VirtualMachine)')\nLIMIT 10"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
   "options": {
    "content": "# List of all commodities sold by Virtual Machines\n<pre>\n    SELECT \n      DISTINCT com.name \n    FROM \n      GRAPH('(vm:VirtualMachine)-[:sells]->(com:Commodity)') \n    ORDER BY com.name       \n</pre>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT \n  DISTINCT com.name as 'Commodities Sold'\nFROM \n  GRAPH('(vm:VirtualMachine)-[:sells]->(com:Commodity)') \nORDER BY com.name "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
   "options": {
    "content": "# List of all commodities bought by Virtual Machines\n<pre>\n    SELECT \n      DISTINCT com.name \n    FROM \n      GRAPH('(vm:VirtualMachine)-[bought:buys]->(com:Commodity)') \n    ORDER BY com.name       \n</pre>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 19 },
   "targets": [
    {
     "queryText": "SELECT \n  DISTINCT com.name as 'Commodities Bought'\nFROM \n  GRAPH('(vm:VirtualMachine)-[bought:buys]->(com:Commodity)') \nORDER BY com.name "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "options": {
    "content": "<h1> vCPU Utilization of a VM</h1>\n<pre>\n    SELECT       \n      vm.name,\n      com.utilization\n    FROM \n      GRAPH('(vm:VirtualMachine)-[:sells]->(com:Commodity)')\n    Where\n      com.name = 'VCPU'\n</pre>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "vCPU Utilization of a VM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 27 },
   "targets": [
    {
     "queryText": "SELECT       \n  relabel(com.utilization, vm.name)\nFROM \n  GRAPH('(vm:VirtualMachine)-[:sells]->(com:Commodity)')\nWHERE\n  com.name = 'VCPU'\nLIMIT 10"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
   "options": {
    "content": "<h1> vCPU and VMEM Utilization of a VM</h1>\n<pre>\n    SELECT       \n      relabel(com.utilization, concat(vm.name, ' ', com.name)      \n    FROM \n      GRAPH('(vm:VirtualMachine)-[:sells]->(com:Commodity)')\n    WHERE \n      com.name in ('VCPU', 'VMEM')\n</pre>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "vCPU and VMEM Utilization of a VM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 35 },
   "targets": [
    {
     "queryText": "SELECT       \n      relabel(com.utilization, concat(vm.name, ' ', com.name))\nFROM \n      GRAPH('(vm:VirtualMachine)-[:sells]->(com:Commodity)')\nWHERE \ncom.name in ('VCPU', 'VMEM')\nLIMIT 10"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 43 },
   "options": {
    "content": "<h1>Averaging VM Metrics</h1>\n<pre>\nSELECT\n    relabel(ts_avg(com.utilization), CONCAT(com.name,\" \", \"Utilization\"))\nFROM\n    GRAPH('(vm:VirtualMachine)-[:sells]->(com:Commodity)')\nWHERE\n    com.name in (\"VCPU\", \"VMEM\", \"CPU_READY\")  \nGROUP BY com.name\n    \n</pre>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Averaging VM Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 43 },
   "targets": [
    {
     "queryText": "SELECT\n    relabel(ts_avg(com.utilization), CONCAT(com.name,\" \", \"Utilization\"))\nFROM\n    GRAPH('(vm:VirtualMachine)-[:sells]->(com:Commodity)')\nWHERE\n    com.name in (\"VCPU\", \"VMEM\", \"CPU_READY\")  \nGROUP BY com.name\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Cloud VM Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 81 },
     "options": {
      "content": "<h1>VMs - Associated Business Account</h1>\n\n<pre>\nSELECT\n    pm.name as 'Host Name'\nFROM\n    GRAPH('(vm:VirtualMachine)<-[:supports]-(pm:PhysicalMachine)')\nWHERE\n    vm.name = ${vmCloud:sqlstring}\n</pre>\n\n\n\n# \n\n    "
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 81 },
     "targets": [
      {
       "queryText": "SELECT\n    ba.name as 'Business Account Name'\nFROM\n    GRAPH('(vm:VirtualMachine)<-[:owns]-(ba:BusinessAccount)')\nwhere \n    vm.name = ${vmCloud:sqlstring}\n\n"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 87 },
     "options": {
      "content": "<h1>VMs - Associated Zone</h1>\n\n<pre>\nSELECT\n    z.name as 'Zone Name'\nFROM\n    GRAPH('(vm:VirtualMachine)<-[:supports]-(z:AvailabilityZone)')\nWHERE \n    vm.name = ${vmCloud:sqlstring}\n</pre>\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 87 },
     "targets": [
      {
       "queryText": "SELECT\n    z.name as 'Zone Name'\nFROM\n    GRAPH('(vm:VirtualMachine)<-[:supports]-(z:AvailabilityZone)')\nwhere \n    vm.name = ${vmCloud:sqlstring}\n\n"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 93 },
     "options": {
      "content": "<h1>VMs - Associated Region</h1>\n\n<pre>\nSELECT\n    r.name as 'Region Name'\nFROM\n    GRAPH('(vm:VirtualMachine)<-[:supports]-(z:AvailabilityZone)<-[:owns]-(r:Region)')\nWHERE\n    vm.name = ${vmCloud:sqlstring}\n</pre>"
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 93 },
     "targets": [
      {
       "queryText": "SELECT\n    r.name as 'Region Name'\nFROM\n    GRAPH('(vm:VirtualMachine)<-[:supports]-(z:AvailabilityZone)<-[:owns]-(r:Region)')\nwhere \n    vm.name = ${vmCloud:sqlstring}\n\n"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 99 },
     "options": {
      "content": "<h1>VMs - Associated Volume</h1>\n\n<pre>\nSELECT\n    DISTINCT v.name as 'Volume Name'\nFROM\n    GRAPH('(vm:VirtualMachine)<-[:supports]-(v:VirtualVolume)')\nWHERE\n    vm.name = ${vmCloud:sqlstring}\n</pre>\n# \n\n    "
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 99 },
     "targets": [
      {
       "queryText": "SELECT\n  DISTINCT v.name as 'Volume Name'\nFROM\n  GRAPH('(vm:VirtualMachine)<-[:supports]-(v:VirtualVolume)')\nwhere\n  vm.name = ${vmCloud:sqlstring}"
      }
     ]
    }
   ]
  },
  {
   "title": "On-Prem VM Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 52 },
     "options": {
      "content": "<h1>VMs - Associated Host</h1>\n\n<pre>\nSELECT\n    pm.name as 'Host Name'\nFROM\n    GRAPH('(vm:VirtualMachine)<-[:supports]-(pm:PhysicalMachine)')\nWHERE\n    vm.name = '${vmOnprem:displayName}'\n</pre>"
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 52 },
     "targets": [
      {
       "queryText": "SELECT\n    pm.name as 'Host Name'\nFROM\n    GRAPH('(vm:VirtualMachine)<-[:supports]-(pm:PhysicalMachine)')\nWHERE\n    vm.name = ${vmOnprem:sqlstring}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 58 },
     "options": {
      "content": "<h1>VMs - Associated Datastore</h1>\n\n<pre>\n    SELECT\n        DISTINCT ds.name as 'Datastore Name'\n    FROM\n        GRAPH('(vm:VirtualMachine)<-[:supports]-(ds:Storage)')\n    WHERE\n        vm.name = ${vmOnprem:sqlstring}\n</pre>\n\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 58 },
     "targets": [
      {
       "queryText": "SELECT\n  DISTINCT ds.name as 'Datastore Name'\nFROM\n  GRAPH('(vm:VirtualMachine)<-[:supports]-(ds:Storage)-[:sells]->(com:Commodity)')\nwhere\n  vm.name = ${vmOnprem:sqlstring}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 64 },
     "options": {
      "content": "<h1> Host Metrics for a VM</h1>\n<pre>\nSELECT\n  relabel(com.utilization, CONCAT(com.name, \" Utilization\"))\nFROM\n  GRAPH('(vm:VirtualMachine)<-[:supports]-(pm:PhysicalMachine)-[:sells]->(com)')\nWHERE\n  vm.name = ${vmOnprem:sqlstring}\n  AND com.name in (\"CPU\", \"MEM\", \"SWAPPING\", \"BALLOONING\", \"Q1_VCPU\", \"Q2_VCPU\", \"Q4_VCPU\", \"Q8_VCPU\", \"Q16_VCPU\", \"Q32_VCPU\")  \n</pre>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Host Metrics for a VM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 64 },
     "targets": [
      {
       "queryText": "SELECT\n  relabel(com.utilization, CONCAT(com.name, \" Utilization\"))\nFROM\n  GRAPH('(vm:VirtualMachine)<-[:supports]-(pm:PhysicalMachine)-[:sells]->(com)')\nwhere\n  vm.name = ${vmOnprem:sqlstring}\n  AND com.name in (\"CPU\", \"MEM\", \"SWAPPING\", \"BALLOONING\", \"Q1_VCPU\", \"Q2_VCPU\", \"Q4_VCPU\", \"Q8_VCPU\", \"Q16_VCPU\", \"Q32_VCPU\")  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 72 },
     "options": {
      "content": "<h1>Storage Metrics for a VM</h1>\n<pre>\nSELECT\n  relabel(com.utilization, com.name)\nFROM\n  GRAPH('(vm:VirtualMachine)<-[:supports]-(ds:Storage)-[:sells]->(com:Commodity)')\nwhere\n  vm.name = ${vmOnprem:sqlstring}\n  AND com.name in (\"STORAGE_AMOUNT\", \"STORAGE_ACCESS\", \"STORAGE_LATENCY\")  \n\n</pre>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Storage Metrics for a VM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 72 },
     "targets": [
      {
       "queryText": "SELECT\n  relabel(com.utilization, com.name)\nFROM\n  GRAPH('(vm:VirtualMachine)<-[:supports]-(ds:Storage)-[:sells]->(com:Commodity)')\nwhere\n  vm.name = ${vmOnprem:sqlstring}\n  AND com.name in (\"STORAGE_AMOUNT\", \"STORAGE_ACCESS\", \"STORAGE_LATENCY\")  \n"
      }
     ]
    }
   ]
  }
 ]
}