{
 "title": "Sample 3. Actions Query Samples",
 "time": { "from": "2021-08-31T05:50:19.100Z", "to": "2021-08-31T17:50:19.100Z" },
 "panels": [
  {
   "title": "Total Actions",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "\n\n\n     SELECT count(*) as 'Total Actions' from Events    "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Actions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT count(*) as 'Total Actions' from Events  "
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "options": { "content": "\n\n    SELECT * FROM EVENTS" },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Events Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "targets": [
    { "queryText": "SELECT * FROM EVENTS" }
   ]
  },
  {
   "title": "EVENTS",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "options": {
    "content": "\n<pre>\n    SELECT \n        e.tags ->> '$.description' as 'Action Description', \n        e.tags ->> '$.state' as State,\n        e.tags ->> '$.type' as Type, \n        e.tags ->> '$.severity' as Severity \n    FROM\n        EVENTS as e\n</pre>"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Actions Details with State,Type & Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT \r\n    e.tags ->> '$.description' as 'Action Description', \r\n    e.tags ->> '$.state' as State,\r\n    e.tags ->> '$.type' as Type,\r\n    e.tags ->> '$.severity' as Severity\r\nFROM \r\n    EVENTS as e"
    }
   ]
  },
  {
   "title": "Cloud Actions",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "options": {
    "content": "\n<pre>\nSELECT \n    from_unix_timestamp(start_time) as 'Time First Recommended', \n    from_unix_timestamp(end_time) as 'End Time', \n    tags ->> '$.type' as Type,\n    tags ->> '$.state' as State,\n    tags ->> '$.cost.delta' as 'Cost Delta (USD/hour)',\n    tags ->> '$.description' as Description\nfrom events \n    where tags ->> '$.cost.delta' IS NOT NULL\norder by 'End Time' DESC\n</pre>\n\n"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Cloud Actions",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT \r\nfrom_unix_timestamp(start_time) as 'Time First Recommended', \r\nfrom_unix_timestamp(end_time) as 'End Time', \r\ntags ->> '$.type' as Type,\r\ntags ->> '$.state' as State,\r\ntags ->> '$.cost.delta' as 'Cost Delta (USD/hour)',\r\ntags ->> '$.description' as Description\r\nfrom events \r\nwhere tags ->> '$.cost.delta' IS NOT NULL\r\norder by 'End Time' DESC"
    }
   ]
  },
  {
   "title": "Total Actions By Type",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
   "options": {
    "content": "\n<pre>\nSELECT\n    count(*) as 'Total Actions',\n    e.tags ->> '$.type' as Type\nFROM \n    EVENTS as e\nGROUP BY Type\n</pre>"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Total Actions By Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 31 },
   "targets": [
    {
     "queryText": "SELECT \r\n    e.tags ->> '$.type' as Type,\r\n    count(*) as 'Total Actions'\r\nFROM \r\n    EVENTS as e\r\nGROUP BY Type"
    }
   ]
  },
  {
   "title": "Total Actions By Category",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 39 },
   "options": {
    "content": "\n<pre>\nSELECT \n    e.tags ->> '$.category' as Category,\n    count(*) as 'Total Actions'\nFROM\n    EVENTS as e\nGROUP BY Category\n</pre>"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Total Actions By Category",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 39 },
   "targets": [
    {
     "queryText": "SELECT \r\n    e.tags ->> '$.category' as Category,\r\n    count(*) as 'Total Actions'    \r\nFROM \r\n    EVENTS as e\r\nGROUP BY Category"
    }
   ]
  },
  {
   "title": "Total Actions By Severity",
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 46 },
   "options": {
    "content": "\n<pre>\nSELECT\n    e.tags ->> '$.severity' as Severity,\n    count(*) as 'Total Actions'    \nFROM \n    EVENTS as e\nGROUP BY Severity\n</pre>"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Total Actions By Severity",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 46 },
   "targets": [
    {
     "queryText": "SELECT \r\n    e.tags ->> '$.severity' as Severity,\r\n    count(*) as 'Total Actions'    \r\nFROM \r\n    EVENTS as e\r\nGROUP BY Severity"
    }
   ]
  },
  {
   "title": "Total Actions By  State",
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 52 },
   "options": {
    "content": "\n<pre>\nSELECT\n    e.tags ->> '$.severity' as State,\n    count(*) as 'Total Actions'\nFROM \n    EVENTS as e\nGROUP BY State\n</pre>"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Total Actions By State",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 52 },
   "targets": [
    {
     "queryText": "SELECT \r\n    e.tags ->> '$.state' as State,\r\n    count(*) as 'Total Actions'    \r\nFROM \r\n    EVENTS as e\r\nGROUP BY State"
    }
   ]
  },
  {
   "title": "Total Actions By  Mode",
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 57 },
   "options": {
    "content": "\n<pre>\nSELECT \n    e.tags ->> '$.mode' as Mode,\n    count(*) as 'Total Actions'    \nFROM\n    EVENTS as e\nGROUP BY Mode\n</pre>"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Total Actions By Mode",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 57 },
   "targets": [
    {
     "queryText": "SELECT \r\n    e.tags ->> '$.mode' as Mode,\r\n    count(*) as 'Total Actions'    \r\nFROM \r\n    EVENTS as e\r\nGROUP BY Mode"
    }
   ]
  },
  {
   "title": "onPrem Actions",
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 62 },
   "options": {
    "content": "    \n<pre>\nSELECT\n    count(*) as 'onPrem Actions'   \nfrom \n    events as e  \nwhere\n    e.tags ->> '$.cost.delta' is null\n</pre>"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "onPrem Actions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\r\n    count(*) as 'onPrem Actions'\r\nfrom \r\n    events as e\r\nwhere\r\n    e.tags ->> '$.cost.delta' is null\r\n"
    }
   ]
  },
  {
   "title": "Cloud Actions",
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 67 },
   "options": {
    "content": "    \n\n<pre>  \nSELECT\n    count(*) as 'Cloud Actions'  \nfrom \n    events as e \nwhere\n    e.tags ->> '$.cost.delta' is not null\n</pre>"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Cloud Actions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\r\n   count(*) as 'Cloud Actions'\r\nfrom \r\n    events as e\r\nwhere\r\n    e.tags ->> '$.cost.delta' is not null\r\n"
    }
   ]
  },
  {
   "title": "Total Actions over time by category",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 73 },
   "options": {
    "content": "\n<pre>\nSELECT\n  relabel(\n    ts_sum(\n      ts_reduce_max(ts_mask(to_timerange(e.start_time, e.end_time)),'1h')\n    ),\n        e.tags ->> '$.category'\n    )\nfrom \n    events as e\nGroup By e.tags ->> '$.category'\n</pre>\n\n"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Total Actions over tIme by Category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_sum(\r\n      ts_reduce_max(ts_mask(to_timerange(e.start_time, e.end_time)),'1h')\r\n    ),\r\n        e.tags ->> '$.category'\r\n    )\r\nfrom \r\n    events as e\r\nGroup By e.tags ->> '$.category'\r\n"
    }
   ]
  },
  {
   "title": "Total Actions over time by type",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 81 },
   "options": {
    "content": "\n<pre>\nSELECT\n  relabel(\n    ts_sum(\n      ts_reduce_max(ts_mask(to_timerange(e.start_time, e.end_time)),'1h')\n    ),\n        e.tags ->> '$.type'\n    )\nfrom \n    events as e\nGroup By e.tags ->> '$.type'\n\n</pre>\n\n"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Total Actions over time by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_sum(\r\n      ts_reduce_max(ts_mask(to_timerange(e.start_time, e.end_time)),'1h')\r\n    ),\r\n        e.tags ->> '$.type'\r\n    )\r\nfrom \r\n    events as e\r\nGroup By e.tags ->> '$.type'\r\n"
    }
   ]
  },
  {
   "title": "Total Actions over time by severity",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 89 },
   "options": {
    "content": "\n<pre>\nSELECT\n  relabel(\n    ts_sum(\n      ts_reduce_max(ts_mask(to_timerange(e.start_time, e.end_time)),'1h')\n    ),\n        e.tags ->> '$.severity'\n    )\nfrom \n    events as e\nGroup By e.tags ->> '$.severity'\n</pre>\n\n"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Total Actions over time by severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_sum(\r\n      ts_reduce_max(ts_mask(to_timerange(e.start_time, e.end_time)),'1h')\r\n    ),\r\n        e.tags ->> '$.severity'\r\n    )\r\nfrom \r\n    events as e\r\nGroup By e.tags ->> '$.severity'\r\n"
    }
   ]
  },
  {
   "title": "Total Actions over time by State",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 97 },
   "options": {
    "content": "\n<pre>\nSELECT\n  relabel(\n    ts_sum(\n      ts_reduce_max(ts_mask(to_timerange(e.start_time, e.end_time)),'1h')\n    ),\n        e.tags ->> '$.severity'\n    )\nfrom \n    events as e\nGroup By e.tags ->> '$.severity'\n</pre>\n\n"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Total Actions over time by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_sum(\r\n      ts_reduce_max(ts_mask(to_timerange(e.start_time, e.end_time)),'1h')\r\n    ),\r\n        e.tags ->> '$.state'\r\n    )\r\nfrom \r\n    events as e\r\nGroup By e.tags ->> '$.state'\r\n"
    }
   ]
  },
  {
   "title": "Actions Descriptions with Commodity Deltas",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 105 },
   "options": {
    "content": "\n<pre>\nSELECT\n  e.tags ->> '$.description' as Description,\n  json_extract(e.tags,'$.commodity_deltas') as 'Commodity Deltas'\nfrom \n    events as e\n</pre>\n\n"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Actions Descriptions with Commodity Deltas",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  e.tags ->> '$.description' as Description,\r\n  json_extract(e.tags,'$.commodity_deltas') as 'Commodity Deltas'\r\nfrom \r\n    events as e\r\nwhere \r\n   json_extract(e.tags,'$.commodity_deltas') is not null\r\n    and e.tags ->> '$.type' = 'Resize'"
    }
   ]
  },
  {
   "title": "Actions Descriptions with Triggering Commodities",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 113 },
   "options": {
    "content": "\n<pre>\nSELECT\n  e.tags ->> '$.description' as Description,\n  json_extract(e.tags,'$.triggering_commodities') as 'Triggering Commodities'\nfrom \n    events as e\n</pre>\n\n"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Actions Descriptions with Triggering Commodities",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  e.tags ->> '$.description' as Description,\r\n  json_extract(e.tags,'$.triggering_commodities') as 'Triggering Commodities'\r\nfrom \r\n    events as e"
    }
   ]
  },
  {
   "title": "Actions Descriptions with Triggering Commodities",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 121 },
   "options": {
    "content": "\n<pre>\n<p>\nSELECT\n  relabel(\n    ts_accum(\n      ts_reduce_area(\n        ts_sum(\n        ts_reduce_avg(\n        ts_mask(\n          to_timerange(\n            e.end_time, \n            ${__to:date:seconds}\n          )) * -1 * cast(e.tags ->> '$.cost.delta' as decimal) / 3600, '1h')), '24h')),\n    e.tags ->> '$.type'\n  )\nFROM\n  events as e  \nWHERE\n  e.tags ->> '$.cost.delta' is not null     \nGroup by e.tags ->> '$.type'\n  </p>\n</pre>\n\n"
   },
   "targets": [
    {
     "queryText": "SELECT \r\n  vm.oid, \r\n  vm.name \r\nFROM \r\n  GRAPH('(vm:VirtualMachine)')      "
    }
   ]
  },
  {
   "title": "Daily savings by actions type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  relabel(\r\n    ts_accum(\r\n      ts_reduce_area(\r\n        ts_sum(\r\n        ts_reduce_avg(\r\n        ts_mask(\r\n          to_timerange(\r\n            e.end_time, \r\n            ${__to:date:seconds}\r\n          )) * -1 * cast(e.tags ->> '$.cost.delta' as decimal) / 3600, '1h'))\r\n          , '24h'))\r\n        ,\r\n    e.tags ->> '$.type'\r\n  )\r\nFROM\r\n  events as e  \r\nWHERE\r\n  e.tags ->> '$.cost.delta' is not null     \r\nGroup by e.tags ->> '$.type'\r\n"
    }
   ]
  }
 ]
}